wormhole-foundation/wormhole

ethereum/contracts/Wormhole.sol, solana/bridge/src/processor.rs
Previously the quorum was not calculated correctly (3/4 instead of 2/3+). Also the quorum check was done incorrectly for sets < 3 since the division by 3 floored to 0.
=> bridge: fix quorum

ethereum/contracts/Wormhole.sol, solana/bridge/src/processor.rs
Previously we had rounding errors due to the usage of integers for calculating `n * 2/3`.
This was fixed by using one decimal fix point numbers during this part of the calucation.
Overflows were mitigated using a u16 cast on Rust. No mitigations are needed in Solidity since `.length` is a u256 (https://solidity.readthedocs.io/en/v0.5.3/types.html#array-members)
=> bridge: fix quorum calculation

bridge/cmd/guardiand/adminserver.go, bridge/cmd/guardiand/bridge.go, bridge/pkg/solana/watcher.go, devnet/bridge.yaml, solana/Cargo.lock, solana/agent/Cargo.toml, solana/agent/src/main.rs, solana/agent/src/socket.rs
This allows us to use UNIX filesystem permissions for access control.
Previously, any process in the network namespace could connect to it,
which is insecure for obvious reasons.
Verified that correct permissions are set:
```
total 8
31996269 4 drwxrwxrwx 2 root root 4096 Nov 23 21:58 .
14676759 4 drwxr-xr-x 1 root root 4096 Nov 23 21:58 ..
31996306 0 srwx------ 1 root root    0 Nov 23 21:58 agent.sock
```
Fixes #119
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/122)
=> solana/agent: listen on UNIX socket

solana/bridge/src/processor.rs
They need to persist for data availability (to be cross-submitted to other chains).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/137)
=> Don't evict governance VAA signatures

solana/bridge/src/processor.rs
The expiration set is set to the time when the set was changed + expiration constant. So the guardian set is expired when that time is in the past.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/155)
=> Fix guardian set expiration on Solana

dev-install.sh, ethereum/copy-from-container.sh, generate-abi.sh, generate-protos.sh, scripts/send-eth-lockups.sh, scripts/send-solana-lockups.sh, scripts/tail.sh, scripts/test-injection.sh, solana/devnet_setup.sh, solana/lockups.sh, tilt_modules/namespace/test/test.sh, tools/build.sh, web/.dockerignore
Hi, I've been trying to run the project according to `DEVELOP.md` on NixOS. I
managed to get most things to work, but Tilt had trouble executing
some of the jobs because of `/bin/bash` being used. NixOS will do the right
thing for `#!/usr/bin/env bash` and `#!/bin/sh` shell scripts but not direct
interpreter paths. Take it with a grain of salt, I replaced that with a "find
and replace in project" tool.
I saw that the web interface container tried to copy the context including
node_modules. I added it to an ignorefile.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/159)
=> Use /usr/bin/env for shell scripts; web/.dockerignore: node_modules

Tiltfile, bridge/cmd/guardiand/bridge.go, bridge/e2e/e2e_test.go, bridge/e2e/eth.go, bridge/e2e/solana.go, bridge/e2e/terra.go, bridge/go.mod, bridge/go.sum, bridge/pkg/ethereum/watcher.go, bridge/pkg/p2p/p2p.go, bridge/pkg/processor/broadcast.go, bridge/pkg/processor/cleanup.go, bridge/pkg/processor/injection.go, bridge/pkg/processor/lockup.go, bridge/pkg/processor/observation.go, bridge/pkg/processor/processor.go, bridge/pkg/solana/client.go, bridge/pkg/solana/submitter.go, bridge/pkg/solana/watcher.go
- Add an initial set of comprehensive Prometheus metrics.
- Fix a couple of testnet race conditions.
- Store guardian set with aggregation state (needed for settled miss metrics).
See individual commits. PR has a clean history and should be rebase-merged, not squashed.
Example output:
```
wormhole_aggregation_state_entries 6
wormhole_aggregation_state_expirations_total 0
wormhole_aggregation_state_retries_total 0
wormhole_aggregation_state_settled_signatures_total{addr="0xbeFA429d57cD18b7F8A4d91A2da9AB4AF05d0FBe",origin="ethereum",status="present"} 2
wormhole_aggregation_state_settled_signatures_total{addr="0xbeFA429d57cD18b7F8A4d91A2da9AB4AF05d0FBe",origin="solana",status="present"} 3
wormhole_aggregation_state_settled_signatures_total{addr="0xbeFA429d57cD18b7F8A4d91A2da9AB4AF05d0FBe",ori …
```
=> Prometheus metrics and test stability improvements

bridge/pkg/solana/client.go, solana/Cargo.lock, solana/agent/Cargo.toml, solana/agent/src/main.rs, solana/bridge/Cargo.toml, solana/bridge/src/instruction.rs, solana/cli/Cargo.toml, solana/cli/src/main.rs, third_party/solana/Dockerfile
Old commitment levels were deprecated and the fastest confirmation level is `Processed`.
Also the upgradeable loader now requires the program to be writeable.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/166)
=> upgrade solana sdk version

solana/bridge/src/processor.rs
This works around https://github.com/solana-labs/solana/issues/9711 which causes issues when the guardian set creation is subsidized and another CPI call is done subsequently
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/172)
=> don't subsidize guardian set creation

terra/Cargo.lock
This fixes the error about `Cargo.lock` changing despite the `--lock` flag being specified. This shows up in Tilt during `terra-terrad` build. Hey @ysavchenko, can you confirm that the trivial lockfile update doesn't break anything? (I haven't touched terra-facing code yet)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/194)
=> terra/Cargo.lock: Run `cargo update`

Tiltfile, solana/Dockerfile, solana/bridge/Cargo.toml, solana/bridge/src/entrypoint.rs, solana/cli/src/main.rs, solana/do.sh
This is a quick fix to move on to `cargo build-bpf` and get `master` to work again ASAP.
The Tiltfile change makes guardian convergence a bit faster
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/196)
=> Bpf sdk hotfix

solana/Dockerfile, solana/agent/Cargo.toml, solana/cli/Cargo.toml
Removing do.sh mostly works but seems we had an oopsie or two. 
Testing strategy:  E2E passes on a clean build
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/198)
=> Fix *.so copy in solana-devnet, correct crate feature for cli+agent

bridge_ui/src/components/Attest/CreatePreview.tsx, bridge_ui/src/components/Attest/Send.tsx, bridge_ui/src/utils/consts.ts
Warn user when attesting from solana and token has no on-chain metadata.
Remind user to update token-list when attesting to solana or terra.
=> bridge_ui: Notify user to set metadata when attesting

bridge_ui/src/utils/consts.ts
Recently changed the cloud functions to so each function is a separate instance (`mainnet-totals`, `mainnet-recent`, etc), rather than having one function with several routes (`/totals`, `/recent`).
=> bridge_ui: update cloud function URLs

terra/contracts/token-bridge/src/contract.rs
We remove [terra16q5pke2vueu23y8punvj70h0cp0s0rc7vrzl57](https://finder.terra.money/mainnet/address/terra16q5pke2vueu23y8punvj70h0cp0s0rc7vrzl57) from `wrapped_asset_address` because it has no admin. This was already removed from `wrapped_asset` here:
https://github.com/certusone/wormhole/commit/e2a16b67#diff-4d1ad320d9f5ab48ff71ac9974eb9a9b10739c15e740a137d85f4fd0354e98f5R111-R123
(they match up, the asset_address `BpuIV/6rgYT7aH9jRhjANdrEOdwa6ztVmKDwAAAAAAE==` in the terra contract decodes to `0x069b8857feab8184fb687f634618c035dac439dc1aeb3b5598a0f00000000001` )
=> terra/token_bridge: fix cw20 migrations

node/cmd/guardiand/logging.go, node/cmd/guardiand/node.go, node/pkg/p2p/p2p.go, node/pkg/processor/cleanup.go, node/pkg/telemetry/telemetry.go
**Stack**:
- #775 ⮜
- #744
- #774
<pre>
It appears that GCP Cloud Logging cannot handle the volume of logs
we're throwing at it... full text search slows to a crawl (LOL)
Reduce log level until we can move to something else.
commit-id:b71c3467
</pre>
=> node/pkg/telemetry: reduce log level to INFO

node/pkg/reporter/attestation_events.go, node/pkg/reporter/bigtablewriter.go
This change increases logging around the GCP PubSub message path, in order to help with debugging.
=> improve logging around GCP PubSub message path

node/pkg/reporter/bigtablewriter.go
turns out you need to supply credentials to write to GCP 🙃
=> supply credentials file to PubSub

clients/token_bridge/main.ts
Useful for generating testnet registration VAAs
=> clients/token_bridge: add option to specify guardian secret in generate_governance_vaa

solana/Dockerfile.wasm
wasm-bindgen 0.2.74 generates JavaScript bindings for SystemInstruction
exported from solana-program 1.9.4. The generated JavaScript references
a non-existent function (wasm.__wbg_systeminstruction_free) that
leads to an attempted import error when importing the wasm packed for
bundler. SystemInstruction isn't used in the sdk, so we remove the non-existent
function reference as a workaround.
=> solana-program 1.9.4 wasm-bindgen workaround

solana/pyth2wormhole/Cargo.lock, solana/pyth2wormhole/program/Cargo.toml, terra/Cargo.lock, terra/contracts/pyth-bridge/Cargo.toml
The v2 branch on the Git origin disappeared. Use the crate instead.
Updated lockfiles using `cargo update -w`.
---
**Stack**:
- #874
- #873 ⮜
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/873)
=> *: bump pyth-client to 0.2.2

Dockerfile.client, solana/Dockerfile, solana/Dockerfile.wasm, solana/pyth2wormhole/Cargo.lock, solana/pyth2wormhole/program/Cargo.toml, terra/Cargo.lock, terra/contracts/pyth-bridge/Cargo.toml
When `--locked` is specified, Cargo fails hard instead of silently
ignoring the lockfile.
The argument doesn't appear to work for the wasm-bindgen, since all
the builds still complete despite an invalid lockfile. The BPF builds
fail as expected when the lockfile needs to be updated.
---
**Stack**:
- #874 ⮜
- #873
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/874)
=> solana: compile wasm and contracts with --locked

clients/eth/main.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/865)
This change moves the int parsing logic up in the logic path.  Side benefit here is that it will now prevent negative numbers for each value.
=> Add stronger nonce/confidence parsing

node/pkg/vaa/governance_test.go
This adds a unit-test for default behavior governance component of vaa.  This is a pretty simple component, so the unit-testing is mostly verifying our defaults don't shift and helps explain how to interact with the lib.  In the future, if this lib adds more functionality, we can lock in more behavior expectations.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/867)
=> Add unit-test for governance

explorer/src/pages/index.tsx
Make the request to get stats when the page first loads.
It is currently waiting 30 seconds to make the first request
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/925)
=> Explorer - fetch stats on first load

event_database/cloud_functions/.gcloudignore, event_database/cloud_functions/addresses-transferred-to-cumulative.go, event_database/cloud_functions/addresses-transferred-to.go, event_database/cloud_functions/external-data.go, event_database/cloud_functions/go.mod, event_database/cloud_functions/go.sum, event_database/cloud_functions/nfts.go, event_database/cloud_functions/notional-transferred-to-cumulative.go, event_database/cloud_functions/notional-transferred-to.go, event_database/cloud_functions/notional-transferred.go, event_database/cloud_functions/notional-tvl-cumulative.go, event_database/cloud_functions/notional-tvl.go, event_database/cloud_functions/recent.go, event_database/cloud_functions/shared.go, event_database/cloud_functions/totals.go
Added two functions:
- `/notionaltvl` returns the locked assets per chain, and their notional value at the moment (prices fetched on demand from CoinGecko)
- `/notionaltvlcumulative` returns the locked assets per chain, by day, including what the assets were worth each day.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/899)
=> TVL calculation from transfer messages

node/pkg/processor/message.go, node/pkg/vaa/governance.go
The guardian should never sign messages emitted by the governance emitter coming from a chain.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/938)
=> Hardening against governance message spoofing

.github/workflows/build.yml
This potentially fixes an issue where force pushing a PR causes checks
within the same run to be cancelled.
---
**Stack**:
- #910
- #891
- #890
- #892 ⮜
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/892)
=> .github: extend concurrency group to include workflow step

.github/workflows/build.yml, DEVELOP.md, Tiltfile, devnet/node.yaml, node/pkg/common/guardianset.go
Proto timestamps are nanoseconds, not milliseconds.
---
**Stack**:
- #910
- #891 ⮜
- #890
- #892
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/891)
=> node/pkg/common: fix guardian set state cleanup

scripts/dev-setup.sh
* use minikube 1.24 due to [this nasty bug](https://github.com/kubernetes/minikube/issues/13542)
* support running on Debian 10, Debian 11, and RHEL8 or a derivative
Note that 69255572c358fb52d4b83ec537cf69e38423cda8 was written entirely by @kierdavis so the credit or flames are all hers :)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/875)
=> Ensure dev-setup.sh works on minimal RHEL8 as well

Dockerfile.client
It appears this is needed to get a local devnet working.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/989)
=> Bump Solana version to 1.9.4 in Dockerfile.client

bridge_ui/src/hooks/useTransactionFees.tsx
I threw together a script that looked at the terra token bridge gas for redeems over the last month:
min  = 3100639
max  = 4506069
mean = 3205947
std  =  204337
Gas prices don't change often (uusd = 0.15 for as long as I can remember and terra.js also hard-codes this as the default)
min UST estimate = 0.15 * 3100639 * 10^-6 = 0.46509585
max UST estimate = 0.15 * 4506069 * 10^-6 = 0.67591035
So let's just make the range 0.4 to 0.7 UST for now?
```import requests
import time
import pandas as pd
gas_data = []
offset = 0
for _ in range(300):
r = requests.get(f'https://fcd.terra.dev/v1/txs?offset={offset}&limit=100&account=terra10nmmwe8r3g99a9newtqa7a75xfgs2e8z87r2sf')
data = r.json()
for tx in data['txs']:
if tx['tx']['value']['memo'] == 'Wormhole - Complete Transfer': …
```
=> bridge_ui: Changed terra est. fees to be more accurate

solana/bridge/cpi_poster/src/lib.rs, solana/bridge/program/src/lib.rs, solana/bridge/program_stub/src/lib.rs, solana/migration/src/lib.rs, solana/modules/nft_bridge/program/src/lib.rs, solana/modules/token_bridge/program/src/lib.rs, solana/solitaire/program/src/macros.rs
The type of the `ix_data` binding withing the solitaire! macro expansion
is explicitly annotated with its type, which comes from the macro's
pattern binding `$kind`. However, this type annotation is entirely
optional, since `ix_data` is passed in as an argument to `$fn`, whose
type forecs `ix_data` anyway, and rust will happily infer that from the
application.
I propose we remove it, so the `solitaire!` entry point is easier to use. The syntax is made-up anyway and not particularly intuitive, so I think this is an improvement.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/927)
=> solitaire: Infer entry point argument type in solitaire! macro

explorer/src/components/ExplorerStats/ChainOverviewCard.tsx, explorer/src/components/ExplorerStats/ExplorerStats.tsx, explorer/src/pages/index.tsx
the polling interval on the index of wormholenetwork.com was 30 seconds, but the function timeout was 60 seconds, so the page could queue up a bunch of requests, causing the cloud functions to scale way up, and become unavailable. This changes removes the polling on the homepage.
This change also removes the polling for some of the /explorer page endpoints. Want to reduce the frequency of calls and see how that effects the functions availability.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/1019)
=> explorer - less calls to cloud functions

node/pkg/common/symmetric_test.go
Refactors symmetric unit-test to use testify and adds more of a framework for adding additional cases.
Breaking the tests out also guard against a theoretical bug scenario where both the encrypt and decrypt methods are effected by a bug in common code, anchoring us to binary blobs from a known good ciphertext.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/948)
=> Refactor Symmetric Unit-tests to Testify

terra/contracts/token-bridge/src/contract.rs
This was incorrectly sending the fee to the recipient.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/1031)
=> terra: Send relayer fee to message sender

.github/workflows/build.yml, terra/.gitignore, terra/Makefile, terra/README.md, terra/test/README.md, terra/test/jestconfig.json, terra/test/package-lock.json, terra/test/package.json, terra/test/src/__tests__/bridge.ts, terra/test/src/helpers/client.ts, terra/test/src/helpers/vaa.ts, terra/test/src/instantiate.ts, terra/test/tsconfig.json
Spoke with @evan-gray about adding tests similar to those in the ethereum directory.
The purpose is to conduct various contract tests by deploying and interacting with these contracts in a local terra node. I've only written a few tests to start using Jest.
This follows the same format @kcsongor did using a Makefile (so all you would have to do is run "make test").
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/1050)
=> Add framework for Terra contract testing

node/pkg/ethereum/by_transaction.go
The program would've crashed on `l.Address` before it
could reach the nilness check.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/1061)
=> node/pkg/ethereum: fix unreachable nil check

clients/solana/main.ts, clients/solana/package.json, clients/token_bridge/main.ts
The solana client (core bridge cli) is currently unable to send VAAs to mainnet, because it generates a fresh keypair and requests airdropped funds into it. This PR allows passing in a private key optionally, in which case the airdrop is not requested.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/1066)
=> clients/solana: allow submitting VAAs to mainnet

event_database/cloud_functions/notional-tvl-cumulative.go
Consumers may only care about the totals which results in a drastically
smaller response payload size.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/1075)
=> cloud_functions: Added totalsOnly param to notional-tvl-cumulative

solana/solitaire/program/src/types/accounts.rs
We consider an account to be initialised when it has data stored in it. It also doesn't make too much sense to call `is_initialized` on `Unitialized` or `Initialized` accounts, since the status of these is statically known.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/1099)
=> solitaire: fix initialisation check

event_database/cloud_functions/notional-tvl.go, event_database/functions_server/main.go
ComputeTVL is intended to be called periodically which writes the computed result to notional-tvl.json. TVL reads from notional-tvl.json and returns it as the response.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/1110)
=> cloud_functions: Split notional-tvl into read and write (to cache) entry points

node/hack/repair_eth/repair_eth.go
* Use a cookiejar for the http requests for services like polygonscan that front their api with a cloudflare waf
* Add the `-showError` boolean flag to print the http response body when there is an error to aid troubleshooting
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/1120)
=> Minor updates to repair_eth

node/cmd/guardiand/admintemplate.go
Adds auth proof generation for shutdown voting to the Guardian's `template` CLI.
Designed this to work with an armored key file (as is supplied to `guardiand`), and a hex string key (for integration testing/devnet scripting).
```bash
go run main.go template shutdown-proof --guardian-key=/guardian/key/file/path/secret.key --proof-pub-key=0x-public-key-to-encode-in-proof
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/1113)
=> guardian - generate auth proof for shutdown voting

event_database/cloud_functions/notional-tvl-cumulative.go, event_database/functions_server/main.go
Added two entry points: ComputeTvlCumulative and TvlCumulative.
The first computes the result and writes it to the results cache -
intended to be invoked periodically by a scheduled task.
The second reads from the results cache and returns it as the response.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/1118)
=> cloud_functions: notional-tvl-cumulative optimizations

node/pkg/ethereum/watcher.go
This fixes a null pointer dereference for a nil tx.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/1151)
=> node/pkg/ethereum: move up nil check for TransactionReceipt

sdk/js/CHANGELOG.md, sdk/js/package.json, sdk/js/src/algorand/Algorand.ts, sdk/js/src/nft_bridge/__tests__/integration.ts, sdk/js/src/nft_bridge/getForeignAsset.ts, sdk/js/src/nft_bridge/getOriginalAsset.ts, sdk/js/src/nft_bridge/transfer.ts, sdk/js/src/rpc/getSignedVAA.ts, sdk/js/src/rpc/getSignedVAAWithRetry.ts, sdk/js/src/token_bridge/__tests__/integration.ts, sdk/js/src/token_bridge/attest.ts, sdk/js/src/token_bridge/createWrapped.ts, sdk/js/src/token_bridge/getForeignAsset.ts, sdk/js/src/token_bridge/getIsTransferCompleted.ts, sdk/js/src/token_bridge/getIsWrappedAsset.ts, sdk/js/src/token_bridge/getOriginalAsset.ts, sdk/js/src/token_bridge/transfer.ts, sdk/js/src/utils/array.ts, sdk/js/src/utils/consts.ts, sdk/js/src/utils/parseVaa.ts
The main goal of this PR is to improve the type safety of some of the sdk functionality.
- `isEVMChain` now performs type refinement. This way, we can achieve exhaustivity checking in downstream code that relies on this check.
- This in turn allows the address conversion functions to have safer types, along with exhaustivity checking. The end result is that when a new chain is added, these functions will raise a type error, indicating that the new chain ids are not handled. No `null` value is returned from using the functions in an intended way (that is, passing in well-typed arguments). This obviates the need for callers to coalesce null cases to values like `""` which results in a debugging nightmare.
- Added some return types, in particular some of these types were inferred to be …
=> sdk: improve type safety + add documentation

bridge_ui/src/utils/metaMaskChainParameters.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/1175)
=> bridge_ui: Changed Karura and Acala testnet metamask chain IDs

node/hack/repair_eth/repair_eth.go
Otherwise there can be a nil pointer deref for polygon when it skips the message we want to ignore.
This sets the messages to a variable sized slice.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/1163)
=> repair_eth: work better when messages are skipped

event_database/cloud_functions/totals.go
Don't add today's totals to the warm cache, otherwise incomplete totals may
exist for today's date in the cache tomorrow. Only adding the totals to the
warm cache for yesterday or older fixes this.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/1184)
=> cloud_functions: don't add today's totals to warm cache

algorand/admin.py, algorand/test/test.py, algorand/test_contract.py, algorand/token_bridge.py, sdk/js/src/algorand/Algorand.ts
algorand has a newer standard : https://github.com/algorandfoundation/ARCs/blob/main/ARCs/arc-0004.md
The change here is to make the called payload3 contract follow the newer standard so that the pyteal/stub stuff just "does the right thing"
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/1187)
=> Algo/abi:  adding changes to support abi method selector

node/pkg/ethereum/pollimpl.go
We were getting a panic here: https://github.com/certusone/wormhole/blob/cdc6edd4255faa196bc993878e367f9fb617a8e3/node/pkg/ethereum/pollimpl.go#L248
Due to `m.Number` being nil.
```
Jun 24 15:39:27 [CENSORED] guardiand[2595664]: panic: runtime error: invalid memory address or nil pointer dereference
Jun 24 15:39:27 [CENSORED] guardiand[2595664]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x149e750]
Jun 24 15:39:27 [CENSORED] guardiand[2595664]: goroutine 709 [running]:
Jun 24 15:39:27 [CENSORED] guardiand[2595664]: github.com/certusone/wormhole/node/pkg/ethereum.(*PollImpl).getBlock(0xc00f0f8660, {0x2fdfd10, 0xc00f0f4500}, 0x0)
Jun 24 15:39:27 [CENSORED] guardiand[2595664]:         /opt/wormhole/wormhole/node/pkg/ethereum/pollimpl.go:248 +0x490
Jun 24 15:39:27 [CENSORED] …
```
=> node/pkg/ethereum: fix a bug discovered in testnet

Dockerfile.const, scripts/guardian-set-init.sh
Use prebuilt CLI executable instead of invoking with 'ts-node'. This way the script runs 10 times
faster, 40s->4s.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/1331)
=> Optimise guardian set init script

.github/workflows/guardiand-docker.yml, Tiltfile, node/Dockerfile, node/cmd/guardiand/node.go
In preparation for a development release of the node image, this PR introduces several changes:
* remove the cruft from the docker image by copying only the necessary files into a scratch stage
* add a `GO_BUILD_ARGS` build arg to the docker container which by default sets the `-race` flag, but allows turning it off
* enforce that `--unsafeDevMode` is enabled when running a development build of the binary.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/1332)
=> node: Prepare development binary release

.github/workflows/build.yml, Dockerfile.const, algorand/Dockerfile, algorand/sandbox-algorand/images/Dockerfile, algorand/sandbox-algorand/images/algod/Dockerfile, algorand/sandbox-algorand/images/indexer/Dockerfile, scripts/check-docker-pin.sh, third_party/redis/Dockerfile
This PR introduces the following:
- Pins all our unpinned Docker image dependancies
- Adds a script to check the repo for unpinned dependancies
- Adds a job in the CI build workflow that runs the script, which will fail the build if we have an unpinned Docker image dep
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/1337)
=> Docker FROM image pinning

.github/workflows/build.yml
The latest nightly broke the ugprade test, not yet sure how. For now,
just pin the older version
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/1344)
=> CI: pin foundry version

solana/Dockerfile, solana/Dockerfile.base
The docker image is internal now, but should be made public before merging this.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/1351)
=> solana: Use prebuilt docker file for main builder

Dockerfile.client, Dockerfile.proto, cosmwasm/devnet/Dockerfile, ethereum/Dockerfile, event_database/functions_server/Dockerfile, node/Dockerfile, relayer/spy_relayer/Dockerfile, solana/Dockerfile, terra/devnet/Dockerfile, third_party/abigen-celo/Dockerfile, third_party/abigen/Dockerfile, third_party/redis/Dockerfile
Reference: https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#add-or-copy
COPY is generally preferred unless we need to make use of the more powerful features within ADD, which it appears we are not using.  The most common example case is that ADD can pull in remote files and auto-magically explode tarballs, neither of which we are doing here, so it's nice to just sidestep those two use cases, which could be abused.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/1338)
=> Move from ADD to COPY on Dockerfiles

node/cmd/guardiand/node.go, node/pkg/terra/watcher.go
This change ensures that the injective watcher uses the correct url for getting the blockheight.
It also removes the guardian set info bits from the terra^Wcosmwasm watcher since those only make sense on Ethereum.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/1350)
=> Update injective url/s

relayer/spy_relayer/README.md
change nodeKey path from /tmp/node.key -> /node.key
the former gives an error that the path does not exist when run on my mac
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/1355)
=> Update spy_relayer readme guardian run command 

node/pkg/common/devnet_consts.go, node/pkg/common/mainnet_consts.go, node/pkg/common/testnet_consts.go
Create separate variables for the known tokenbridge and nft bridge
emitters and dynamically build KnownEmitters from those lists.  Having
separate variables for the tokenbridge and nft emitters will make it
easier to look them up without having to iterate over the whole emitter
list every time.
Also add a devnet_consts file to list the known emitters in the
development network.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/1317)
=> node/pkg/common: Refactor KnownEmitters

solana/bridge/program/src/accounts/claim.rs, solana/bridge/program/src/api/governance.rs, solana/bridge/program/src/instructions.rs, solana/bridge/program/src/vaa.rs, solana/bridge/program/src/wasm.rs, solana/modules/nft_bridge/program/src/api/complete_transfer.rs, solana/modules/nft_bridge/program/src/api/governance.rs, solana/modules/nft_bridge/program/src/instructions.rs, solana/modules/token_bridge/program/src/api/complete_transfer.rs, solana/modules/token_bridge/program/src/api/complete_transfer_payload.rs, solana/modules/token_bridge/program/src/api/create_wrapped.rs, solana/modules/token_bridge/program/src/api/governance.rs, solana/modules/token_bridge/program/src/api/transfer_payload.rs, solana/modules/token_bridge/program/src/instructions.rs, solana/solitaire/program/src/lib.rs, solana/solitaire/program/src/processors/peel.rs, solana/solitaire/program/src/types/context.rs, solana/solitaire/rocksalt/src/lib.rs
This PR contains two commits, both atomic changes. The change requires understanding `FromAccounts` and `Peel` so this PR is written to be as helpful as possible in explaining the change.
Commit 1 - [f44088a](https://github.com/certusone/wormhole/pull/1318/commits/f44088a7a9c39522661bf42e5573f65e8339ecd2)
================================================================================
This commit aims to remove the recursive `FromAccount` behavior. The commit is medium sized as it also includes changes to all instructions affected by the change so all programs still compile.
**Justification**
Removing this code helps with several things:
- It allows removing the `'c` lifetime sprinkled through the entire codebase which is difficult to work with.
- It would allow removing `rocksalt` in …
=> Remove Recursive `Peel` to reduce Claim complexity.

node/hack/discord_test/discord.go, node/pkg/notify/discord/notify.go, node/pkg/processor/broadcast.go, node/pkg/processor/cleanup.go, node/pkg/processor/injection.go, node/pkg/processor/message.go, node/pkg/processor/observation.go, node/pkg/processor/processor.go, node/pkg/processor/vaa.go, node/pkg/vaa/structs.go
We need to reuse almost all of the gossip infrastructure for accounting
transactions, with the only difference being that accounting will use a
`Transfer` message rather than a `VAA`.
Make the observation stored in the processor state generic so that it
can be either a VAA or a Transfer.  The rest of the code is shared.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/1316)
=> node: processor: Make observation state generic

event_database/cloud_functions/external-data.go, event_database/cloud_functions/notional-transferred-to.go, event_database/cloud_functions/notional-tvl-cumulative.go, event_database/cloud_functions/notional-tvl.go, event_database/cloud_functions/shared.go
Use daily token prices to compute TVL instead of the prices fetched
at token transfer time, if available.
Added inactive tokenlist to exclude tokens that have essentially been
deactivated by CoinGecko (market data no longer available).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/1366)
=> cloud_functions: use daily token prices to compute cumulative TVL

.github/workflows/relayer-docker.yml, relayer/spy_relayer/Dockerfile
Publishing this (along with [these docs](https://github.com/certusone/wormhole/tree/c5a7d3e517138d1980ff4d379a3a6b10f0c11498/relayer/spy_relayer#relayer) being updated) should make it much easier for wormhole community members or partners to run a relayer.
Once we get this published, I'll add additional documentation on how to run a production version of this relayer in kubernetes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/1371)
=> Transfer payload v1 relayer container image

cosmwasm/contracts/token-bridge/_tests/integration.rs, cosmwasm/contracts/token-bridge/src/contract.rs, cosmwasm/contracts/token-bridge/src/lib.rs, cosmwasm/contracts/token-bridge/src/msg.rs, cosmwasm/contracts/token-bridge/src/state.rs, cosmwasm/contracts/token-bridge/src/testing/tests.rs, cosmwasm/contracts/token-bridge/src/token_address.rs, cosmwasm/contracts/wormhole/src/contract.rs, cosmwasm/contracts/wormhole/src/msg.rs, cosmwasm/contracts/wormhole/src/state.rs, cosmwasm/contracts/wormhole/tests/integration.rs, cosmwasm/test/src/__tests__/bridge.ts, cosmwasm/tools/deploy.js, cosmwasm/tools/deploy_single.js, terra/contracts/nft-bridge/src/contract.rs
Prior to this change, these values were hardcode in the contract, as
the only supported chain was terra 2. This change allows the contract to
be deployed to other cosmwasm chains without having to recompile the
contract for each one.
The migration code ensures that terra2 is upgraded appropriately.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/1369)
=> cosmwasm: move chain id and fee denom to storage

sdk/js/CHANGELOG.md, sdk/js/package-lock.json, sdk/js/package.json, sdk/js/src/cosmos/address.ts, sdk/js/src/cosmos/index.ts, sdk/js/src/index.ts, sdk/js/src/terra/address.ts, sdk/js/src/token_bridge/getOriginalAsset.ts, sdk/js/src/utils/array.test.ts, sdk/js/src/utils/array.ts, sdk/js/src/utils/consts.ts
Add support for wormhole chain to the sdk.  Since the `humanAddress` and `canonicalAddress` functions in the terra package are also needed for wormhole chain, move them into a new cosmos package.  Also, stop hard coding "terra" in `humanAddress` and take the human-readable part as a parameter instead.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/1386)
=> Add wormhole chain to the sdk

Tiltfile, dashboards/Wormhole.json, devnet/node-metrics.yaml
Added metrics collection + visualization for the guardian.
I got this working previously when I wanted to see guardianset update metrics, decided to add this as it may be helpful for visualizing wormchain data.
The Grafana configmap is the whole default grafana config file, not much is changed from the default (only to allow anon access), but figured I would include it so it is obvious what the options are. I'm open to ripping that out, lmk what you think.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/1391)
=> add Prometheus + Grafana for Guardian metrics

tools/build.sh, tools/go.mod, tools/go.sum, tools/tools.go
Switches to use the extracted cobra-cli command since it is being removed from the github.com/spf13/cobra module (xref https://github.com/spf13/cobra/issues/1597)
The first commit updates `tools` to the current spf13/cobra and tidies, the second commit switches to the corresponding cobra-cli version
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/936)
=> Switch `tools` to standalone cobra-cli dependency

sdk/js/src/token_bridge/__tests__/terra-integration.ts, terra/contracts/token-bridge/src/contract.rs
Before this check, users were able to lose funds by sending money to an
address that's shorter than 32 bytes.
This commit is essentially a backport of the fix from the new cosmwasm contract.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/1403)
=> terra: Ensure that recipient address is 32 bytes.

whitepapers/0007_governor.md
Opening this PR for open feedback on a security feature that Guardians can optionally opt into that would limit the amount of notional value that can be transferred out of a given chain in a given time frame -- this would reduce the damage to the bridge during an existential threat scenario.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/1412)
=> Chain Governor

node/pkg/governor/governor.go, node/pkg/governor/governor_prices.go, node/pkg/governor/governor_test.go
The governor was not properly handling the case where there are multiple tokens using the same CoinGecko symbol.
The governor previously had a map from CoinGecko symbol to a reference to a token object. The change is to make that a map from the CoinGecko symbol to an array of references to tokens, and to update all of those tokens when the CoinGecko price is udpated.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/1418)
=> Governor should handle duplicate coin gecko ids

node/cmd/guardiand/adminserver.go, node/cmd/guardiand/node.go, node/pkg/common/obsvReqSendC.go, node/pkg/common/obsvReqSendC_test.go
Change-Id: Ifb0d038fa3adeddc6226e2289fe9dbfc8e39b4e7
Jeff noticed a while ago that too many reobservation requests can hang the guardian. This is because an attempt to write to the channel hangs if the channel has reached capacity. This PR addresses by making sure the channel is not full before writing to it.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/1429)
=> node: don't allow obs reqs if the queue is full

devnet/eth-devnet.yaml, ethereum/README.md, ethereum/contracts/mock/MockBatchedVAASender.sol, ethereum/migrations/10_deploy_batched_vaa_sender.js, ethereum/package.json, ethereum/scripts/deploy_batched_vaa_sender.js, ethereum/scripts/send_batched_vaa.js, ethereum/test/wormhole.js
Added an EVM contract that calls wormhole core's `publishMessage` several times, in order to produce VAAs that should be batched.
Also added a truffle script that invokes the new contract's method, and some tests.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/1425)
=> add EVM contract for batched VAA development

cosmwasm/contracts/token-bridge/src/contract.rs, cosmwasm/contracts/token-bridge/src/msg.rs, sdk/js/src/token_bridge/__tests__/terra2-integration.ts, sdk/js/src/token_bridge/getIsTransferCompleted.ts
The `getIsTransferCompleted*`  family of functions in the js sdk that query cosmwasm functions (terra1, terra2, and soon injective) require simulating a redeem transaction to see if they fail with `VAAAlreadyExecuted`  to determine whether the VAA in question has already been redeemed.
This is obviously suboptimal -- this PR introduces a first class query to the cosmwasm token bridge contract so that this information can just be queried without requiring a signer and a tx simulation.
There's an accompanying sdk function to query this information for terra2. No such contract change or sdk change has been made for terra classic, and it might not be worth doing it anyway. Open to discussion though.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" …
=> cosmwasm: Expose 'is VAA redeemed' query

bridge_ui/src/components/Recovery.tsx
Otherwise if there's an exception, the `handleError` case will never be executed.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/1456)
=> bridge_ui: Recovery should await fetchSignedVAA fix

node/cmd/guardiand/node.go, node/pkg/common/obsvReqSendC.go, node/pkg/common/obsvReqSendC_test.go, node/pkg/processor/broadcast.go, node/pkg/processor/cleanup.go, node/pkg/processor/processor.go
This PR fixes a bug in the processor package where the guardian network would never reach quorum on an observation if not enough guardians observed the tx when it first happened.  Instead the guardians that did observe the tx would keep re-broadcasting their signatures over the network every 5 minutes for 120 hours or until someone manually submitted a re-observation request.
The fix is to send the re-observation request whenever we re-broadcast a local observation.  This allows guardians that missed the tx the first time to re-observe it in their local RPC node.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/1438)
=> Re-observation

node/cmd/guardiand/node.go, node/cmd/guardiand/reobserve.go, node/cmd/guardiand/reobserve_test.go
Commit "1753bb3: Send re-observation request when re-broadcasting local
observations" changed the processor code to automatically send
re-observation requests.  If multiple guardians do this around the same
time that would lead to multiple re-observation requests for the same
transaction.
Deduplicate re-observation requests by keeping a cache of the requests
that were received in the last 11 minutes.  Any request that's already
in the cache will not be forwarded to the chain-specific observation
code.  The 11 minute value was chosen because the guardians will send
these requests approximately every 5 minutes.
Also move the re-observation code into a standalone function so that it
can be more easily tested.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" …
=> node: Deduplicate re-observation requests

devnet/node.yaml, node/cmd/guardiand/node.go
This promotes pythnet to mainnet. There is no token or nft bridge, so a lot of the normal machinery isn't hooked up by design.
In manually testing this, I noticed the help text for the solana rpc node and websocket flags were wrong. FYI: @jayantk 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/1459)
=> Promote Pythnet to Mainnet

aptos/contracts/sources/State.move
This might require running
```
aptos move clean
```
before building again.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/1473)
=> aptos: Fix compile after stdlib version upgrade

node/pkg/governor/mainnet_chains_test.go, node/pkg/governor/mainnet_tokens_test.go
These unit-tests are mainly just to ensure a mainnet config update doesn't result in a regression of config expectations.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wormhole-foundation/wormhole/1461)
=> Add mainnet chains and token config unit-tests

clients/js/main.ts, node/cmd/guardiand/adminverify.go, scripts/register-all-chains.sh, scripts/register-chain-governance.sh
Change-Id: If99e78b031dcd4049a9ee40b09914eeb93e7518a
Also changing the guardian verify VAA command to print the digest in the same format as the execute VAA command.
Much of the magic in register-chain-governance.sh was taken directly from contract-upgrade-governance.sh, which has previously been reviewed.
=> Script to generate change registration governance

aptos/Dockerfile, aptos/token_bridge/sources/bridge_state.move, aptos/token_bridge/sources/vaa.move, aptos/wormhole/sources/set.move, aptos/wormhole/sources/state.move, scripts/check-docker-pin.sh
Added a slightly cleaner way to do replay protection by replacing the `Table<vector<u8>, bool>` with a custom `Set` type, which should just make the code a little easier to reason about (in particular now there's no such thing as a key being present but the value being false).
Also added a `token_bridge::vaa` module with some common utilities. In particular, `parse_verify_and_replay_protect` should be called by all token bridge functions that take VAA bytes, because it does the parsing, the verification, emitter checking, and replay protection all in one go. These checks need to be done by all token bridge functions so might as well share this bit out.
=> aptos: token bridge VAA utils

node/pkg/publicrpc/publicrpcserver.go, proto/gossip/v1/gossip.proto, proto/publicrpc/v1/publicrpc.proto
Added a gossip message for broadcasting signed BatchVAAs, and a publicrpc endpoint for getting signed BatchVAAs.
The gossip messages follow the same paradigms as the messages for original VAAs. The new gossip messages are:
- `SignedBatchObservation`, broadcast when a guardian sees and signs a BatchVAA. This is how individual guardian signatures are shared among the guardianset to build quorum. Same paradigm as broadcasting a signed VAA with the `SignedObservation` GossipMessage. This is basically a guardian broadcasting "i saw a thing on chain, signed it".
- `SignedBatchVAAWithQuorum`, broadcast when a guardian achieves quorum on a BatchVAA (after collecting individual signatures via the `SignedBatchObservation` message). Same paradigm as broadcasting a VAA that has reached quorum with …
=> proto - BatchVAA gossip and publicrpc

ethereum/contracts/Setters.sol, ethereum/test/wormhole.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/1432)
=> ethereum: add check for the zero address in storeGuardianSet

sdk/js/package-lock.json, sdk/js/package.json, sdk/js/src/rpc/getSignedBatchVAA.ts, sdk/js/src/rpc/getSignedBatchVAAWithRetry.ts, sdk/js/src/rpc/index.ts
- Pulled in the latest version of `js-proto-web` that has the BatchVAA protos.
- Added new RPC methods `getSignedBatchVAA` & `getSignedBatchVAAWithRetry`.
- Bumped the version of the sdk.
=> sdk/js - add getSignedBatchVAA and bump version

ethereum/contracts/bridge/Bridge.sol, ethereum/contracts/bridge/token/TokenImplementation.sol, ethereum/contracts/bridge/token/TokenState.sol, ethereum/forge-test/TokenImplementation.t.sol
Modify TokenBridgeImplementation to adopt EIP712 and ERC20Permit. Add supporting forge unit tests validating `permit` implementation.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/1470)
=> Support ERC20Permit for Gasless Approvals

.github/workflows/build.yml, node/pkg/common/obsvReqSendC_test.go
Fix a racy test and enable data race detection when running unit tests in CI.
=> Fix race condition in test

aptos/token_bridge/sources/contract_upgrade.move, aptos/token_bridge/sources/newtypes/string32.move, aptos/wormhole/sources/contract_upgrade.move, aptos/wormhole/sources/deserialize.move, aptos/wormhole/sources/guardian_pubkey.move, aptos/wormhole/sources/keccak256.move, aptos/wormhole/sources/serialize.move, aptos/wormhole/sources/u16.move, aptos/wormhole/sources/u256.move, aptos/wormhole/sources/u32.move, aptos/wormhole/sources/vaa.move, aptos/wormhole/sources/wormhole.move
This PR sets up the code to support formal verification by the move prover. The prover can't reason about bitwise operations (and just bails when the project contains them), so I did some changes to replace them with supported numeric operations.
For now, there is a single invariant proven, namely that
```rust
spec String32 {
invariant string::length(string) == 32;
}
```
i.e. that `String32` indeed always contains 32 characters. The prover neatly understands the semantics of move modules, and requires that each constructor of `String32` (and each mutable borrow in the `String32` module) holds this invariant. This required adding a loop invariant to `right_pad`.
Currently the prover doesn't get executed in CI, trying to think what the best way is to set it up, I've built a docker image …
=> aptos: prove

node/cmd/guardiand/node.go, node/cmd/guardiand/reobserve.go, node/cmd/guardiand/reobserve_test.go, node/pkg/processor/cleanup.go, node/pkg/processor/processor.go
Add rate-limiting for sending out re-observation requests and also make the receiver non-blocking.
=> Reobservation rate-limit

aptos/wormhole/sources/u256.move
The removal of this function in #1613 is non-backwards compatible, and the devnet deployment still has that function. To keep the contracts upgradeable on devnet, we restore this function and revert immediately.
=> aptos: restore removed 'div' function in u256

aptos/scripts/upgrade, aptos/token_bridge/sources/contract_upgrade.move, aptos/wormhole/sources/contract_upgrade.move, clients/js/cmds/aptos.ts
In addition to the bytecodes, now we also include the metadata file's content in the upgrade hash. This is more of a sanity thing, as there's no reason not to include it, even if there's no immediately apparent attack vector without it.
=> aptos: include metadata in upgrade hash

node/pkg/common/chainlock.go, node/pkg/processor/cleanup.go, node/pkg/processor/message.go, node/pkg/processor/processor.go, node/pkg/processor/vaa.go, node/pkg/solana/client.go
Given solana unreliable messages overwrite the account, they cannot be reobserved. 
This change prevents sending reobservation requests for unreliable messages.
=> node: prevent reobservation of unreliable messages

node/pkg/governor/governor.go, node/pkg/governor/governor_monitoring.go, node/pkg/p2p/p2p.go, proto/gossip/v1/gossip.proto
Change-Id: I2b8b1ea84a0c411101a7027acd3a27a6d6464d59
=> node: governor publish gossip

node/pkg/processor/cleanup.go, node/pkg/processor/message.go, node/pkg/processor/observation.go, node/pkg/processor/processor.go, node/pkg/processor/vaa.go, node/pkg/publicrpc/publicrpcserver.go
This PR stores PythNet VAAs in memory rather than writing them to the guardiand database. It does this for ChainID == Pythnet rather than using the new IsUnreliable flag because that flag is not present in the SignedVAAWithQuorum gossip message (and changing that message might break various things).
Change-Id: Ief4357ab4c909d25dc9182490c322ef253ac23d3
=> node: don't store pythnet VAAs in the database

Dockerfile.node
Not sure why this started failing, but figured keeping the package was safer in the immediate term.
=> node: fix dockerfile

node/cmd/guardiand/node.go
I hear that not all indexers require tokens
=> node: don't require algorandIndexerToken

node/cmd/guardiand/node.go, node/pkg/watchers/evm/connectors/poller.go, node/pkg/watchers/evm/watcher.go
The provider we are using for Arbitrum testnet limits the number of queries we can do. This was causing the poller connector to hang while calling eth_getBlockByNumber(). This PR adds a timeout to those calls so that the runnable will die and get restarted.
Change-Id: Ia324f1ac482fa9c5bea2b501970f0b22b16e67ce
=> node: poller timeout

clients/js/package-lock.json, clients/js/package.json, scripts/guardian-set-init.sh
This PR upgrades the client/js npm package to use wormhole-sdk@0.7.0.  This introduced an issue where injective depends on a package that depends on an older version of secp256k1.  This older package prints a console message that gets caught in guardian-set-init.sh script.  Consequently, the guardian-set-init.sh script is being updated to remove that text.
The script changes were tested and verified to be correct locally and in the docker image.
=> clients/js: upgrade to latest wormhole-sdk

aptos/deployer/sources/deployer.move, aptos/scripts/deploy_testnet, aptos/token_bridge/sources/deploy_coin.move, aptos/token_bridge/sources/structs/asset_meta.move, aptos/wormhole/sources/cursor.move, aptos/wormhole/sources/deserialize.move, aptos/wormhole/sources/emitter.move, aptos/wormhole/sources/external_address.move, aptos/wormhole/sources/guardian_pubkey.move, aptos/wormhole/sources/guardian_set_upgrade.move, aptos/wormhole/sources/serialize.move, aptos/wormhole/sources/state.move, aptos/wormhole/sources/vaa.move, aptos/wormhole/sources/wormhole.move, clients/js/networks.ts
The contracts are now deployed on the long-lived testnet.
Emitter addresses are now represented as u64 instead of u128, this is to streamline the watcher component (will be a separate PR).
There was a fun issue with deployment. I first deployed the contract bytecodes, but the init functions were failing with a `MISSING_DEPENDENCY` runtime error. It turns out that vector operations are not native functions, but implemented as Move VM opcodes directly (whereas natives are implemented by the backend as magic). There's a rewriter pass in the move compiler that replaces vector operations with the opcodes, defined here: https://github.com/move-language/move/blob/main/language/move-compiler/src/naming/fake_natives.rs#L99-L116. Notice that the rewriter matches on the AST _before_ address …
=> aptos: testnet

node/pkg/watchers/solana/client.go
When the solana watcher is restarted (due to network errors, for
example) then the `lastSlot` state is lost.  This means that any
transactions in between the last processed slot and the most recent slot
will be lost and require manual re-observation.  Fix this by making the
`lastSlot` state persistent across watcher restarts.
=> node: solana: Store `lastSlot` more persistently

cosmwasm/contracts/token-bridge/src/contract.rs, cosmwasm/contracts/token-bridge/src/msg.rs, cosmwasm/contracts/token-bridge/src/state.rs, cosmwasm/test/src/__tests__/bridge.ts, cosmwasm/tools/deploy.js, cosmwasm/tools/deploy_xpla.js
Previously, the cosmwasm contracts only had to handle Terra Classic or Terra 2, both of which natives have 6 decimals. But with more cosmwasm chains on the horizon (like XPLA) with larger decimal sizes (18 in the [axpla case](https://docs.xpla.io/docs/develop/core-modules/#conventions)), the code needs to handle normalization to 8 decimals on the way out and in.
=> cosmwasm: support natives over 8 decimals

node/cmd/guardiand/node.go
The xpla readiness was correctly registered for testnet, but not for mainnet. This fixes that small omission.
=> Fix xpla readiness for mainnet

Dockerfile.node
Looks like this action has been failing for a while. https://github.com/wormhole-foundation/wormhole/actions/runs/3239158698/jobs/5308206975
I expect this change will fix it.
=> docker: fix guardiand build action

sui/token_bridge/README.md, sui/token_bridge/sources/attest_token.move, sui/token_bridge/sources/bridge_state.move, sui/token_bridge/sources/complete_transfer.move, sui/token_bridge/sources/register_chain.move, sui/token_bridge/sources/treasury.move, sui/token_bridge/sources/vaa.move, sui/token_bridge/sources/wrapped.move, sui/wormhole/Move.toml
- Implement more of the token bridge, including `treasury.move`, which contains `TreasuryCapStore`, `CoinStore`, and related functions like minting and burning wrapped assets
- Tailored design to the dynamic Child object access pattern, we will be able to use it in `complete_transfer` and `transfer_tokens`, they will only need to take `BridgeState` as an arg, instead of the IDs of `TreasuryCapStore<CoinType>` or `CoinStore<CoinType>`
- RegisterChain.move
- README comments
=> Sui: dynamic child object setup, treasury.move, TreasuryCapStore, CoinStore

relayer/spy_relayer/README.md
Since the testnet guardian node key changed post restart.
=> Fix the spy documentation for testnet

clients/js/evm.ts
Use the generated interface functions instead of defining our own
=> clients/js: EVM query contract refactor

cosmwasm/devnet/config/config.toml, terra/devnet/config/config.toml, terra/tools/deploy.js
Reducing terra block times helps tilt startup times as transactions are sent block by block.
I intentionally did not set `skip_timeout_commit` to `true` as this would create blocks as fast as possible and `create_empty_blocks = false` is not an option as the ABCI apphash changes every block on terra which forces block creation.
=> tilt: shorten terra block time

scripts/contract-upgrade-governance.sh, scripts/register-chain-governance.sh
the injection command prints out in this format, so it's easier to read for guardians this way
=> scripts: uppercase digest in governance generator

.github/workflows/build.yml, aptos/scripts/package.json, clients/js/package.json, cosmwasm/test/package.json, cosmwasm/tools/package.json, ethereum/package.json, lp_ui/package.json, near/package.json, node/hack/governor/package.json, relayer/spy_relayer/package.json, scripts/check-npm-package-scopes.sh, terra/test/package.json, terra/tools/package.json, testing/contract-integrations/package.json, testing/rollback/package.json, testing/weth-switch/package.json, tools/package.json, wormhole_chain/testing/js/package-lock.json, wormhole_chain/testing/js/package.json, wormhole_chain/testing/js/src/__tests__/basicTransfer.ts, wormhole_chain/testing/js/src/__tests__/sdkTests.ts, wormhole_chain/testing/js/src/__tests__/validators.ts, wormhole_chain/testing/js/src/bootstrap.ts, wormhole_chain/testing/js/src/utils/walletHelpers.ts, wormhole_chain/ts-sdk/package.json
Adding a check to ensure that packages in the repo are always scoped to the wormhole-foundation (or certusone, the current scope of the javasscript sdk and related packages) as is good practice.
=> ci: unscoped npm package check

sdk/js/src/cosmwasm/query.testnet.test.ts
The purpose of this PR is to intentionally skip the `testnet - injective submit a vaa` sdk-ci test because it breaks the Tilt integration tests due to `ALGO_MNEMONIC` being unset.
=> sdk/js: add .skip

cosmwasm/Makefile, cosmwasm/contracts/cw20-wrapped/src/contract.rs, cosmwasm/contracts/token-bridge/src/contract.rs, solana/migration/src/api/add_liquidity.rs, solana/migration/src/api/migrate_tokens.rs, solana/migration/src/api/remove_liquidity.rs, solana/modules/token_bridge/program/src/api/complete_transfer.rs, solana/solitaire/program/src/error.rs
4. Use of panics on invalid inputs
Description In several places, the code panics when an arithmetic overflow or underflow occurs. Panics should be reserved for programmer errors (e.g., assertion violations). Panicking on user errors dilutes the utility of the panic operation. An example appears in figure 4.1. Thecomplete_nativefunction useschecked_subto verify that the transfer includes sufficient funds to cover the fee. However, complete_nativepanics if there are insufficient funds.Thus, the function could panic on either a programmer error or a user error.
Also added 9. cw20-wrapped tests do not build
**for tob-9**
Removed the arguments and ran cargo test. Works seamlessly
=> tob-worm-4-panics: using options rather than unwrap & tob-worm-9: cosmwasm test build

node/pkg/governor/mainnet_chains.go
Moonbeam limits are exhausted daily and now that multiple DEXs are accepting wrapped assets from chains with $5m notional limits, it would be keen to up the Moonbeam limits to match.
=> Node: update governor limits for Moonbeam

.github/CODEOWNERS
Adding codeowners for the guardiand node such that reviews get auto-requested and we have a better workflow for approvals. I think we discussed this before but wanted to make the first step here.
I generally picked the authors of specific pieces of code and added leo and myself as fallback reviewers becuase most of the untagged code was originally written by any one of us two.
Happy to add @jynnantonix @bruce-riley as fallback owners as well, lmk what you think.
=> github: add CODEOWNERS for node

Tiltfile, algorand/sandbox-algorand/images/algod/Dockerfile, cosmwasm/devnet/config/config.toml, devnet/eth-devnet.yaml, devnet/eth-devnet2.yaml, devnet/near-devnet.yaml, devnet/node.yaml, devnet/solana-devnet.yaml, devnet/terra-devnet.yaml, devnet/terra2-devnet.yaml, ethereum/mine.js, node/pkg/watchers/algorand/watcher.go, terra/devnet/config/config.toml, testing/sdk.sh, testing/spydk.sh, wormchain/validators/first_validator/config/config.toml, wormchain/validators/kubernetes/wormchain-guardian-devnet.yaml, wormchain/validators/kubernetes/wormchain-validator2-devnet.yaml, wormchain/validators/second_validator/config/config.toml
This should resolve the minimal tilt guardian from not becoming ready without `--wormchain`
Also the test logs were very annoying to debug with all the info statements, so this PR aims to make the test logs more meaningful and not stream infinitely intermingled with the real errors.
=> Tilt / CI improvements

node/go.mod, node/go.sum, node/hack/repair_solana/repair.go, node/pkg/watchers/solana/client.go
Upgrade the solana-go library to a version that handles Solana V0 transactions.
Change-Id: Ia83b193d524e4c8571bfb8f3dd3075da8b5581cf
=> Node: Upgrade to solana-go v1.7.1

Tiltfile, devnet/spy-listener.yaml, devnet/spy-relayer.yaml, devnet/spy-wallet-monitor.yaml, relayer/spy_relayer/.dockerignore, relayer/spy_relayer/.env.docker.sample, relayer/spy_relayer/Dockerfile, relayer/spy_relayer/docker-compose.yml, scripts/check-docker-pin.sh
This PR enables spy_relayer stack to be run using docker-compose.
For basic usage, you just run `docker-compose up` and it will run the whole stack written on README.md.
https://github.com/wormhole-foundation/wormhole/tree/dev.v2/relayer/spy_relayer#run-the-apps
=> spy_relayer: Enable docker-compose usage

sdk/js/src/solana/wormhole/accounts/emitter.ts, sdk/js/src/solana/wormhole/accounts/index.ts, sdk/js/src/solana/wormhole/accounts/sequence.ts, testing/solana-test-validator/sdk-tests/2_token_bridge.ts
In PR #1375 I forgot to add SequenceTracker deserialization found in [sequence.rs](https://github.com/wormhole-foundation/wormhole/blob/dev.v2/solana/bridge/program/src/accounts/sequence.rs).
This adds a way to deserialize this account and corresponding tests to verify the account data.
=> sdk/js: add SequenceTracker

node/pkg/processor/cleanup.go, node/pkg/processor/observation.go, node/pkg/processor/observation_test.go, node/pkg/processor/quorum_test.go, sdk/vaa/quorum.go, sdk/vaa/structs.go
This addresses issue https://github.com/wormhole-foundation/wormhole/issues/1764
The relevant pieces of node/pkg/processor/observation.go::handleInboundSignedVAAWithQuorum() were pulled into
sdk/vaa/structs.go:Verify()
Downside:  CalculateQuorum() was copied from node/pkg/processor/quorum.go to sdk/vaa/structs.go.  Should be a better way than copying functions.
Resolution:
Moving CalculateQuorum() to a new file in the sdk and making sure test run correctly.
=> sdk/vaa: add verify function to vaa

sui/token_bridge/sources/bridge_state.move, sui/token_bridge/sources/structs/asset_meta.move, sui/token_bridge/sources/transfer_tokens.move, sui/token_bridge/sources/treasury.move, sui/token_bridge/sources/wrapped.move, sui/wormhole/sources/myvaa.move, sui/wormhole/sources/state.move, sui/wormhole/sources/structs.move
- make use of dynamic fields to store token bridge owned `TreasuryCapStore` and `CoinStore` in BridgeState
- update Sui unit tests in BridgeState to use new `test_scenario` functions
- update to Sui 0.12.0, code compiles and tests pass
=> sui token bridge: dynamic fields and unit test updates

whitepapers/0008_batch_messaging.md
The purpose of this PR is to update `0008_batch_messaging.md` to reflect the batch hash computation changes found in this [commit](https://github.com/wormhole-foundation/wormhole/pull/1680/commits/7c996390fdadf9e8d2eaea4cc9d70a8f51580af4).
=> Update 0008_batch_messaging.md to reflect batch hash change

node/pkg/watchers/evm/connectors/poller.go
Somehow this change to poller.go did not get committed with the previous PR.
=> node: arbitrum watcher fix

ethereum/scripts/deploy_test_token.js
Noticed this error happening in tilt sometimes:
[tests] Error: Returned error: VM Exception while processing transaction: the tx doesn't have the correct nonce. account has nonce of: 17 tx has nonce of: 16
It's not safe to submit txs in parallel, because the nonce can get out of sync. Instead we should submit them serially.
=> ethereum: deploy test token nonce race condition fix

node/pkg/processor/cleanup.go, node/pkg/processor/processor.go
These messages were added when we stopped writing PythNet messages to the DB. Since things have been working smoothly, these can be changed to debugs to reduce unnecessary logging.
=> Node: Delete PYTHNET log messages

sdk/js/CHANGELOG.md, sdk/js/package.json, sdk/js/src/utils/consts.ts
Remove Ropsten support from the SDK. 
Once this PR has been merged and the SDK released, a separate PR will be used to remove support from client/js and the relayer.
Additionally, PR 1818 is removing support from the node / guardian code.
=> SDK: Remove support for Ropsten

solana/Dockerfile, solana/devnet_setup.sh
Running registrations in parallel reduces the time the process takes from ~90s to ~9s, which is a 10x improvement. Closes #1826
=> solana/tilt: run registrations in parallel (fixes #1826)

node/cmd/guardiand/node.go, node/cmd/spy/spy.go, node/pkg/common/guardianset.go, node/pkg/common/guardianset_test.go
This commit adds support for observing heartbeat updates to a GuardianSetState via a channel. See #1768 for more details on motivation.
=> node: support for heartbeat spying fixes #1768

node/pkg/watchers/solana/client.go
The "Transaction failed, skipping it" message comes out a lot in mainnet! Looking at the failures, they look legit, so changing the message to a debug to reduce logging.
Change-Id: I31ed7c57102dbdcd5956270e99859b9bdeaafb13
=> Node: Don't log "Transaction failed" in solana

node/pkg/governor/governor.go, node/pkg/governor/governor_prices.go
In mainnet, we are seeing some guardians getting rate limited by CoinGecko. This PR changes the CoinGecko limit from every five minutes to every 15 minutes. It also improves handling when the query fails, so it only logs a single error and prints the actual error text.
Change-Id: I4f97a012284c75d544a1fe7d43e5914210c4b441
=> Governor: Increase the CoinGecko interval

node/pkg/watchers/evm/connectors/poller.go
The Arbitrum poller is occasionally failing, but the error text is not getting logged when the runnable dies. 
Additionally, the poller retries three times before dying, but we are not seeing the log error from any of them. Adding a 250 ms delay between retries.
Change-Id: Id067d0be18a7c391ef90a82cc78f0684c72ab2ad
=> Node: Arbitrum poller failling without details

wormchain/Makefile, wormchain/README.md
Before, `wormchaind version` returned no value.  Now it will return the correct version, e.g. `v2.13.1`.
=> include latest tag as wormchain version

sui/token_bridge/sources/bridge_state.move, sui/wormhole/sources/emitter.move
- give `EmitterCapability` a `key` ability so it is considered a Sui object and can be input to an `entry` function
- delete `ConsumedVAA` type
=> sui: fix entry function arg is not object bug 

node/cmd/guardiand/node.go, node/pkg/watchers/evm/connectors/poller.go, node/pkg/watchers/evm/connectors/polygon.go, node/pkg/watchers/evm/connectors/polygonabi/RootChain.go, node/pkg/watchers/evm/watcher.go
This PR changes the Polygon watcher to use checkpointing on Ethereum to determine when Polygon blocks are final. For details on Polygon finality, please see the prologue of node/pkg/watchers/evm/connectors/polygon.go.
To enable this feature, the guardians must specify two additional config parameters. If those parameters are not present, the Polygon watcher works as it previously did. It is likely that checkpointing will not be enabled in testnet because it can take a very long time for a transaction to be confirmed.
Note that this PR adds a new parameter to the EVM Watcher, extraParams. This is meant to be a generalized way to pass chain specific parameters into the watcher without having to keep adding additional parameters. If you have a better way to do this, please let me know.
=> Node: Polygon watcher redesign

cosmwasm/Cargo.toml, cosmwasm/contracts/mock-bridge-integration/Cargo.toml, cosmwasm/contracts/shutdown-token-bridge/Cargo.toml, cosmwasm/contracts/shutdown-wormhole/Cargo.toml, cosmwasm/contracts/token-bridge/Cargo.toml, cosmwasm/contracts/wormhole/Cargo.toml
Put all the local overrides at the workspace level rather than having
to specify the path in each individual crate.  This will also make it
easier for us to publish to crates.io when that time comes.
=> cosmwasm: Override local deps at the workspace level

sdk/js-proto-node/.npmrc, sdk/js-proto-web/.npmrc, sdk/js/.npmrc, sdk/js/package-lock.json, sdk/js/package.json, sdk/js/src/rpc/getSignedBatchVAA.ts, sdk/js/src/rpc/getSignedBatchVAAWithRetry.ts
This updates the SDK method to include `nonce` when calling the guardian's publicrpc endpoint to get a BatchVAA.
I also added `.npmrc`s to the js modules, to make npm save exact package versions (no `^`).
Part of https://github.com/wormhole-foundation/wormhole/issues/1893 & https://github.com/wormhole-foundation/wormhole/issues/1679
=> sdk/js - include nonce in GetSignedBatchVAA call

node/cmd/guardiand/node.go, node/pkg/watchers/evm/watcher.go
This PR changes the way the EVM watchers handle determining when a transaction can be published and when it should be declared abandoned.
The existing functionality uses a single minConfirmations parameter and multiplies it by four to get the max confirmations. This has broken down over time because the watchers for most EVM chains work off of finalized blocks, so there is no need to wait for additional blocks, but setting minConfirmations  to zero does not work to compute the maximum number of blocks to wait.
This PR changes the EVM watcher to take two parameters:
waitForConfirmations - bool indicating if we need to wait the number of additional confirmations specified by the consistency level. It will be set to false for chains that have true finality.
maxWaitConfirmations - this is …
=> Node: Rework min/max confs for EVM watchers

ethereum/contracts/bridge/BridgeImplementation.sol, ethereum/contracts/bridge/BridgeSetters.sol, ethereum/contracts/nft/NFTBridgeSetters.sol, scripts/contract-upgrade-governance.sh
This PR protects from a temporary DoS risk arising from the `initialize()` function only partially defining the `tokenContract` variable, combined with the fact that `initialize()` is public. This PR fixes the immediate issue, will follow up with a proposal to eliminate this class of bugs in due course.
The EVM upgrade test is expected to fail for this one, because it simulates an upgrade against ethereum, which in this case is expected to revert (since this upgrade targets arbitrum and optimism exclusively).
The token implementations in question are:
https://arbiscan.io/address/0x53b56de645b9de6e5a40ace047d1c74e8b42eccb
https://optimistic.etherscan.io/address/0xb91e3638f82a1facb28690b37e3aae45d2c33808
=> Protect token implementation for arbitrum&optimism

ethereum/contracts/Shutdown.sol, ethereum/contracts/bridge/BridgeShutdown.sol, ethereum/contracts/nft/NFTBridge.sol, ethereum/contracts/nft/NFTBridgeGetters.sol, ethereum/contracts/nft/NFTBridgeGovernance.sol, ethereum/contracts/nft/NFTBridgeImplementation.sol, ethereum/contracts/nft/NFTBridgeSetters.sol, ethereum/contracts/nft/NFTBridgeSetup.sol, ethereum/contracts/nft/NFTBridgeShutdown.sol, ethereum/scripts/deploy_core_bridge_shutdown.js, ethereum/scripts/deploy_nft_bridge_shutdown.js, ethereum/scripts/deploy_token_bridge_shutdown.js, ethereum/simulate_upgrade, ethereum/simulate_upgrades
These are stripped down versions of the original contracts that can be dropped in place via an upgrade to disable core functionality. Governance features are still enabled, which means it's possible to upgrade back to a working implementation.
Fixes #1937
=> ethereum: Implement shutdown for all 3 contracts (fixes #1937)

Dockerfile.node
race condition detector should not be enabled on a dev build because it can lead to ballooning memory consumption. We can think about adding it back in into a separate test build
=> node: remove race condition detector

sui/token_bridge/sources/bridge_state.move, sui/token_bridge/sources/dynamic_set.move
This PR introduces a new module, `dynamic_set`, which acts like the storage model of traditional move. That is, objects are identified by their type, and there's at most a single one of them. Implemented as dynamic object fields, so rather than belonging to an account, the elements belong to another object (the bridge state in this case). This module allows cleaning up the dummy fields, and overall a little more concise.
=> sui: simplify storage model

sui/token_bridge/sources/attest_token.move, sui/token_bridge/sources/bridge_state.move, sui/token_bridge/sources/wrapped.move
Introduce byte-addressing for CoinTypes on-chain. The byte addresses are taken from an increasing sequence of numbers starting from 0.
- `assign_coin_type_bytes_address`
- `get_coin_type_bytes_address`
Write tests for these as well.
=> sui: byte addressing for Sui CoinTypes

node/pkg/watchers/evm/connectors/common.go, node/pkg/watchers/evm/connectors/poller.go, node/pkg/watchers/evm/connectors/polygon.go, node/pkg/watchers/evm/watcher.go, sdk/vaa/structs.go
This adds the ability for the EVM watcher to listen for safe blocks in addition to finalized blocks. If a message has a consistency level of 201, it will wait for the safe block rather than the finalized one.
This feature is currently only enabled for Ethereum.
=> Node: Support for EVM watcher safe blocks

node/pkg/p2p/p2p.go
Enforce a minimum heartbeat message length such that signed observations, which have the format `signature(hash(hash(observation))` cannot be replayed as heartbeat messages, which have the format `signature(hash("heartbeat|..."))` in case where `hash(observation) = "heartbeat|...". 
I can't think of any concrete security risk with the current implementation, but it's better to tidy things up.
=> node: enforce minimum heartbeat message length

node/pkg/p2p/p2p.go
a possible solution to fixes https://github.com/wormhole-foundation/wormhole/issues/1991
=> node/p2p: enforce ObservationRequest signature payload >= 34 bytes

wormchain/Makefile
We needed to apply these changes to be able to generate the operator address with a Ledger.
If you want to make it optional, you might take inspiration from[ Osmosis’ makefile](https://github.com/osmosis-labs/osmosis/blob/9e178a631f91ffc91c51f3665ed915c9f15e1807/Makefile#L6).
=> Build wormchaind with Ledger support by default

node/cmd/guardiand/adminclient.go, node/cmd/guardiand/bech32.go, sdk/p2p_consts.go, wormchain/mainnet/genesis.json, wormchain/x/wormhole/client/cli/genesis.go, wormchain/x/wormhole/keeper/msg_server_register_account_as_guardian.go
This adds an admin commands to sign the wormchain validator address which guardians can use as part of becoming validators on wormchain.
```
guardiand admin sign-wormchain-address <wormhole...>
```
I've also updated the genesis to include all of the guardian public keys, which will allow other guardians to join without requiring any action from the first validator.
Please verify the guardian keys in the genesis are correct by running the following and comparing.
```
echo  0xD2CC37A4dc036a8D232b48f62cDD4731412f4890 `# 01node` | sed -e "s/^0x//" | xxd -r -p | base64 
echo  0x58CC3AE5C097b213cE3c81979e1B9f9570746AA5 `# jumpcrypto` | sed -e "s/^0x//" | xxd -r -p | base64 
echo  0x54Ce5B4D348fb74B958e8966e2ec3dBd4958a7cd `# chainlayer` | sed -e "s/^0x//" | xxd -r -p | base64 
echo …
```
=> admin command to sign wormchain validator address

sdk/vaa/structs.go
This PR establishes the precedent that `VAA.VerifySignatures` and `BatchVAA.VerifySignatures` should **only** be wrapper methods.
We should ensure that all logic is added in the main `VerifySignatures` method. This will help us guard against future confusion and cases where individual branches of logic may be accidentally added to one of the struct methods and not the main method.
=> sdk: enforce single canonical VerifySignatures method

sdk/js/src/token_bridge/__tests__/consts.ts, sdk/js/src/token_bridge/__tests__/terra-integration.ts, terra/devnet/config/config.toml, terra/tools/deploy.js
This PR patches the issues observed in #2064.
1. Updates the `timeout_broadcast_tx_commit` to `30s` (which matches the current LocalTerra config), resolving the timeout issue.
2. Forces the functions broadcasting transactions to wait for the next block.
3. Avoids using the test1 key in the Terra Classic tests to prevent a sequence mismatch on simulation within `getIsTransferCompletedTerra`.
=> terra/tools: restore broadcast waiting fix

cosmwasm/Makefile
We already run the unit tests as part of the rust-lint-and-tests CI job
so don't run them again before running the integration tests.
=> cosmwasm: Makefile: Separate unit and integration tests

sui/wormhole/sources/guardian_set_upgrade.move, sui/wormhole/sources/state.move
test that:
- old guardian set does not expire immediately after a guardian set upgrade
- but does so after 3 epochs have passed
In general, what should we set delta epochs to be? Right now it is set to 2 epochs. 
Note: the token bridge tests do not pass right now, because of the update to the CoinMetadata, which is fixed on a different branch
=> sui: wormhole test guardian set expiry

sdk/vaa/structs.go, sdk/vaa/structs_test.go
As part of the guardian changes for accounting, we need to start persisting common.MessagePublication objects in the badger db. It would be nice to be able to use JSON for that. To make that work, we need a custom unmarshal method for vaa.Address, since it has a custom marshal. (I don't want to change the existing marshal because that may cause unexpected breakage.)
Change-Id: I1beb99f82673d1fc3225a8c6628a0019648d7e01
=> sdk/go: Add unmarshal for vaa.Address

Dockerfile.node
Refs: #2073
Since the stuff under /bin might not have the right libraries to run, don't copy it. This is not a general purpose operating system image and is meant to be minimal.
=> docker: update node build to not copy executables

sdk/vaa/payloads.go, wormchain/x/wormhole/client/cli/genesis.go, wormchain/x/wormhole/keeper/msg_server_execute_governance_vaa.go, wormchain/x/wormhole/keeper/msg_server_execute_governance_vaa_test.go, wormchain/x/wormhole/keeper/msg_server_wasmd.go, wormchain/x/wormhole/keeper/msg_server_wasmd_test.go, wormchain/x/wormhole/types/tx.pb.go
https://github.com/wormhole-foundation/wormhole/pull/2057 added wormchain-specific governance messages to the sdk by hardcoding the "WasmdModule" string and uint8 action IDs. This PR cleans up the hardcoded values by using shared consts, following up on the discussion here - https://github.com/wormhole-foundation/wormhole/pull/2057#discussion_r1039804829.
Bringing the governance action consts into the sdk also allows us to eliminate other hardcoded values in the sdk serialization functions.
=> wormchain: move governance consts to sdk

aptos/deployer/Move.toml, aptos/token_bridge/Move.toml, aptos/wormhole/Move.toml
Instead of 'main', as it introduced breaking changes recently
=> aptos: build dependencies from 'mainnet' branch

.dockerignore
Running `make validators` in wormchain will fail if there already exists a `wormchain/build/config/gentx/` folder:
```
Error: failed to write signed gen tx: open build/config/gentx/gentx-<uuid>.json: file exists`
```
This change ensures that starting tilt with wormchain doesn't fail with this error by remove the `gentx/` from the wormchain directory that's copied over to the docker container.
=> tilt: remove wormchain gentx folder to make deployment robust

sdk/js/src/mock/tokenBridge.ts, testing/solana-test-validator/sdk-tests/2_token_bridge.ts
Fix the Javascript SDK's `MockTokenBridge`'s `serializeTransferOnly` method, which did not use the `withPayload` parameter to change the serialized payload ID. Without this fix, mock serialized token transfer messages will end up being deserialized as payload 1 transfers despite there being an additional payload associated with this transfer.
Workaround without this fix is to force the payload ID byte (at 51) of the resulting `Buffer` to `3` if you intend to use `publishTransferTokensWithPayload`.
1. Go to _testing/solana-test-validator_ and run `make test`.
2. Review change in _tokenBridge.ts_.
3. Review change in tests.
=> Fix MockTokenBridge

whitepapers/0008_batch_messaging.md
Added a paragraph explaining the constraint on number of messages in a batch, and why BatchVAAs won't be produced for non-compliant observations.
Also added links where bold text was referencing a section heading (I <3 markdown)
=> Batch messaging whitepaper - add max allowed messages info

clients/js/cmds/aptos.ts, sdk/js/src/utils/consts.ts
This PR increases the default airdrop amount of `worm aptos faucet`, since the deployer is currently running out of funds on branches that have added 1+ new chain registrations. Also a bit of cleanup RE: sdk consts.
Along with #2030, fixes #1990.
=> Increase Aptos faucet default airdrop amount

sdk/js/src/solana/tokenBridge/cpi.ts, sdk/js/src/solana/wormhole/accounts/claim.ts, sdk/js/src/solana/wormhole/coder/accounts.ts, sdk/js/src/solana/wormhole/coder/instruction.ts, testing/solana-test-validator/sdk-tests/2_token_bridge.ts
Minor fixes for Solana-related interactions using the Javascript SDK.
- generating CPI accounts for completing transfer (native and wrapped)
- serialization of account and instruction data 
1. Go to _testing/solana_test_validator_ and run `make test` to verify that the tests work.
2. Review code changes.
3. Review changes in the test.
=> sdk/js: solana cpi and serialization fixes

cosmwasm/contracts/wormchain-accounting/schema/wormchain-accounting.json, cosmwasm/contracts/wormchain-accounting/src/contract.rs, cosmwasm/contracts/wormchain-accounting/src/msg.rs, cosmwasm/packages/accounting/src/contract.rs
Add a query to validate transfers.  This can be useful for guardians to
sanity check a transfer before submitting a signed observation for it
Part of #1933.
=> cosmwasm: accounting: Add ValidateTransfer query

cosmwasm/Cargo.lock, cosmwasm/contracts/wormchain-accounting/Cargo.toml, cosmwasm/contracts/wormchain-accounting/schema/wormchain-accounting.json, cosmwasm/contracts/wormchain-accounting/src/contract.rs, cosmwasm/contracts/wormchain-accounting/src/msg.rs, cosmwasm/contracts/wormchain-accounting/src/state.rs, cosmwasm/contracts/wormchain-accounting/tests/helpers/mod.rs, cosmwasm/contracts/wormchain-accounting/tests/submit_observations.rs, cosmwasm/contracts/wormchain-accounting/tests/submit_vaas.rs, cosmwasm/packages/wormhole-bindings/Cargo.toml, cosmwasm/packages/wormhole-bindings/src/fake.rs, cosmwasm/packages/wormhole-bindings/src/query.rs, sdk/rust/Cargo.lock, sdk/rust/core/Cargo.toml, sdk/rust/core/src/vaa.rs
Add a mechanism to backfill missing transfer messages.  This will also
be used to initialize the on-chain state as there is too much data to
initialize the contract via the normal `instantiate` mechanism.
Fixes #1883, fixes #1884.
=> cosmwasm: Add backfill method for accounting

cosmwasm/contracts/wormchain-accounting/src/contract.rs, cosmwasm/contracts/wormchain-accounting/tests/helpers/fake_tokenbridge.rs
The tokenbridge chain registration query returns a
`ChainRegistrationResponse` struct and not a `Vec<u8>`.  Use the proper
return type when sending the query.
=> cosmwasm: accounting: Fix chain registration query return type

cosmwasm/contracts/wormhole/src/state.rs, terra/contracts/wormhole/src/state.rs
Remove unnecessary casting to `usize`. This fixes the clippy errors in ci.
=> cosmwasm: wormhole: remove unnecessary cast to usize

sui/Docker.md, sui/Dockerfile, sui/token_bridge/sources/bridge_state.move, sui/token_bridge/sources/newtypes/string32.move, sui/token_bridge/sources/register_chain.move, sui/token_bridge/sources/vaa.move, sui/wormhole/sources/external_address.move, sui/wormhole/sources/guardian_pubkey.move, sui/wormhole/sources/keccack256.move, sui/wormhole/sources/myu256.move, sui/wormhole/sources/myvaa.move
- re-build and push Docker image with updated Sui binaries to ghcr 
- update test annotations to use either `location` indicating place of failure or a `const u64` abort code
=> sui: update to 0.19.0, rebuild docker image, fix tests

.gitignore, Tiltfile, sui/NOTES.md, sui/scripts/funder.sh, sui/scripts/import_account_and_deploy.sh, sui/scripts/start_node.sh
Previously, deploying Sui contracts locally required following several steps in [sui/NOTES.md](https://github.com/wormhole-foundation/wormhole/blob/sui/integration/sui/NOTES.md). This PR automates that process via a simple bash script.
The default account is generated with the same seed as before, but now uses ed25519 instead of secp256k1 for the keygen scheme because Sui wallet, which is used for testing in the ui repo, derives imported accounts using ed25519.
=> sui: Import and fund default account

sdk/js/package-lock.json, sdk/js/package.json, sdk/js/src/solana/wormhole/coder/idl.ts, sdk/js/src/solana/wormhole/coder/instruction.ts, sdk/js/src/solana/wormhole/instructions/initialize.ts, sdk/js/src/solana/wormhole/instructions/postVaa.ts, sdk/js/src/solana/wormhole/instructions/verifySignature.ts
The current sdk/js for solana is a little bit lackluster :
- There is no encoder for PostMessage
- There is no intruction decoder
I need both things for cross-chain governance tools. I decided to copy what anchor does for encoding/decoding.
I updated WormholeInstructionCoder to parse the layouts of the instructions from wormhole.json (wormhole's IDL). I then use these layouts in WormholeInstructionCoder to encode/decode instructions. This means we no longer need to hand-serialize/deserialize instructions. To add a new instructions you just need to add it to wormhole.json.
=> sdk/js: Add instruction decoder to solana

.github/workflows/build.yml, solana/bridge/program/tests/common.rs, solana/bridge/program/tests/integration.rs
This removes the `common::sync` function which was not necessary and causing flakiness.
It also aggressively caches cargo dependencies and build artifacts. The binaries will still get rebuilt when there are changes.
=> ci: Fix flaky solana tests and improve CI time

sdk/js/CHANGELOG.md, sdk/js/package-lock.json, sdk/js/package.json, sdk/js/src/solana/nftBridge/accounts/wrapped.ts
Fixes this error when calling `deriveWrappedMintKey` in the browser:
TypeError: (intermediate value).toBuffer is not a function
=> sdk/js: Use BN.toArrayLike for compatibility with browserify and similar tools.

sdk/vaa/payloads_test.go, sdk/vaa/structs_test.go
Worked with @SEJeff on SDK VAA test coverage while learning golang.
* payloads.go 90.6% -> 💯 
* structs.go 51.4% -> 54.4%
For [vaa.UnmarshalBody](https://github.com/wormhole-foundation/wormhole/blob/98c843e85d19756b43df407e1fd85363d1a1b4c4/sdk/vaa/structs.go#L378), this error condition may not be reachable and therefore isn't covered.
https://github.com/wormhole-foundation/wormhole/blob/98c843e85d19756b43df407e1fd85363d1a1b4c4/sdk/vaa/structs.go#L411-L413
=> More sdk tests

cosmwasm/contracts/wormchain-accounting/schema/wormchain-accounting.json, cosmwasm/contracts/wormchain-accounting/src/contract.rs, cosmwasm/contracts/wormchain-accounting/src/msg.rs, cosmwasm/contracts/wormchain-accounting/src/state.rs, cosmwasm/contracts/wormchain-accounting/tests/helpers/mod.rs, cosmwasm/contracts/wormchain-accounting/tests/missing_observations.rs, cosmwasm/contracts/wormchain-accounting/tests/submit_observations.rs
Add a query so that guardians can directly check with the on-chain accounting state for transfers that are missing observations from that guardian.  This should make it easier for those guardians to do targeted re-observations.
Part of #2002.
=> cosmwasm: accounting: Add query for missing observations

cosmwasm/contracts/wormchain-accounting/src/contract.rs, cosmwasm/contracts/wormchain-accounting/tests/submit_vaas.rs
Change the error message when handling duplicate observations from
"message already processed" -> "transfer already committed".
=> cosmwasm: accounting: Change error message for duplicate observation

cosmwasm/contracts/wormchain-accounting/src/contract.rs
When we fail to handle an observation in a batch, include the transfer
key as part of the error context so that it's easier to figure out which
observation caused the error.
=> cosmwasm: accounting: Identify failed transfer in batch

sui/Docker.md, sui/Dockerfile, sui/wormhole/sources/external_address.move
- Build new `sui 0.20.0` docker image and push to ghcr: https://github.com/orgs/wormhole-foundation/packages/container/sui/61872809?tag=0.20.0
- fix serialize function in external_address.move affected by update
=> sui: update to devnet version 0.20.0, fix tests

sui/token_bridge/sources/attest_token.move, sui/token_bridge/sources/complete_transfer.move, sui/token_bridge/sources/testing/native_coin.move, sui/token_bridge/sources/testing/native_coin_v2.move, sui/token_bridge/sources/wrapped.move
- Finish `complete_transfer.move` using `coin_metadata`
-  Write `complete_transfer_native`, `complete_transfer_wrapped`, `submit_vaa_native`, `submit_vaa_wrapped`.
- Note: we distinguish between the native and wrapped cases because for native tokens, we have to pass in the `coin_metadata` explicitly. For the wrapped case, we instead look up the metadata from the `bridge_state`
- Implement normalization / denormalization properly by looking up decimals in `coin_metadata`
- `complete_transfer` tests are up-to-date with [Aptos counterparts](https://github.com/wormhole-foundation/wormhole/blob/main/aptos/token_bridge/sources/complete_transfer.move)
=> sui: finish complete transfer impl + tests, decimal denormalization

cosmwasm/Cargo.lock, cosmwasm/Cargo.toml, cosmwasm/packages/cw_transcode/Cargo.toml, cosmwasm/packages/cw_transcode/src/error.rs, cosmwasm/packages/cw_transcode/src/lib.rs, cosmwasm/packages/cw_transcode/src/ser.rs
The cw_transcode crate provides a way to transcode any arbitrary rust
struct into a `cosmwasm_std::Event` via that struct's `Serialize` impl,
ensuring that the event attribute values are encoded as proper json.
This will make it easier for client code to parse the event back into
structured data without having to write custom parsing code for each
individual event type.
=> cosmwasm: Add cw_transcode crate

cosmwasm/contracts/wormchain-accounting/schema/wormchain-accounting.json, cosmwasm/contracts/wormchain-accounting/src/contract.rs, cosmwasm/contracts/wormchain-accounting/src/msg.rs, cosmwasm/contracts/wormchain-accounting/tests/helpers/mod.rs, cosmwasm/contracts/wormchain-accounting/tests/query.rs
Rather than forcing clients to guess whether a transfer is pending or
committed use a single `TransferStatus` query that will return whether
the transfer is still pending or already committed.
This will make it easier for clients to keep the pending and committed
transfer state in sync to avoid unnecessary overhead.
Part of #2002
=> cosmwasm: accounting: Simplify transfer queries

cosmwasm/Cargo.lock, cosmwasm/contracts/wormchain-accounting/Cargo.toml, cosmwasm/contracts/wormchain-accounting/src/contract.rs, cosmwasm/contracts/wormchain-accounting/src/msg.rs, cosmwasm/contracts/wormchain-accounting/tests/modify_balance.rs, cosmwasm/contracts/wormchain-accounting/tests/submit_observations.rs, cosmwasm/contracts/wormchain-accounting/tests/submit_vaas.rs, cosmwasm/packages/accounting/Cargo.toml, cosmwasm/packages/accounting/src/contract.rs
Use cw_transcode to ensure that event attribute values are always
encoded as proper json, making it easier for clients to parse them back
into structured data.
This also lets us reuse the input messages for the events, reducing the
number of different structs that we need to track.
=> cosmwasm: accounting: Use cw_transcode for events

node/cmd/guardiand/admintemplate.go
The current guardian set index is 3, so the `guardiand` template command should generate prototxt files accordingly.
=> node: New default current guardian set index (3)

wormchain/mainnet/genesis.json
This is an export of the mainnet genesis with adjustments to validator `max_commission` and `max_change_commission` values to be 0.20 and 0.02 instead of 0.
There are no new account since they've been created since the last genesis reset, but some of the accounts have become validators.
=> wormchain: reset genesis to adjust 0 commission change values

cosmwasm/Cargo.lock, sdk/rust/Cargo.lock, sdk/rust/serde_wormhole/Cargo.toml, sdk/rust/serde_wormhole/src/de.rs, sdk/rust/serde_wormhole/src/lib.rs, sdk/rust/serde_wormhole/src/raw.rs, sdk/rust/serde_wormhole/src/ser.rs
Add a RawMessage type that can be used to defer parsing parts of a
payload, similar to the `json.RawMessage` from Go.  The implementation
is inspired by `serde_json::RawValue`, which does a similar thing.
When serializing, RawMessage will serialize to a base64-encoded string
if it detects that the data format is human readable (like JSON).
Otherwise it will simply forward the raw bytes to the serializer.
RawMessage has both borrowed and boxed versions.  The borrowed version
is the most efficient as it enables zero-copy handling of the input data
but also requires that the input data already contains raw bytes and is
not suitable when dealing with human-readable formats like JSON.
The boxed version is more flexible as it supports byte slices, base64-
encoded strings, and byte sequences but …
=> sdk/rust: Add serde_wormhole::RawMessage

cosmwasm/Cargo.lock, cosmwasm/contracts/wormchain-accounting/src/contract.rs, sdk/rust/Cargo.lock, sdk/rust/core/src/token.rs, sdk/rust/core/src/vaa.rs, sdk/rust/serde_wormhole/Cargo.toml, sdk/rust/serde_wormhole/src/de.rs, sdk/rust/serde_wormhole/src/lib.rs, sdk/rust/serde_wormhole/src/raw.rs, sdk/rust/serde_wormhole/src/ser.rs
The RawMessage type provides a more flexible way to handle trailing
payloads so replace all usage of the `*_with_payload` functions to use
`RawMessage` instead.
There should be no functional change.
=> sdk/rust: Remove `*_with_payload` methods

clients/js/evm.ts
Using `await` sequentially will force sequential blocking evaluation of code that could otherwise happily run concurrently. Instead of using `await`, this PR uses `Promise.all` to execute a bunch of independent computations in parallel.
Verified (by diffing) that the output matches the old version.
Before this PR, the following command
```
worm evm info -c ethereum -m NFTBridge -n mainnet
```
took around 10s to run on my machine. With this PR, it runs in ~1s.
=> worm: speed up `evm info` by improving concurrency

aptos/Dockerfile
=> aptos/cache_fix: remove the usage of the cache from the aptos test

cosmwasm/contracts/wormchain-accounting/src/contract.rs, cosmwasm/contracts/wormchain-accounting/src/msg.rs, cosmwasm/contracts/wormchain-accounting/tests/missing_observations.rs, cosmwasm/contracts/wormchain-accounting/tests/query.rs, cosmwasm/contracts/wormchain-accounting/tests/submit_vaas.rs, sdk/rust/core/src/token.rs, sdk/rust/core/src/vaa.rs
Add the payload as an explicit field to the `TransferWithPayload` enum
variant.  This is a generic parameter that defaults to `Box<RawMessage>`
for maximum flexibility (and to avoid leaking lifetimes higher up the
stack) but users are encouraged to replace this default type parameter
with an explicit `&RawMessage` in places where the serde_wormhole data
format is used.
The main benefit of this change is that the payload is now included as
part of the actual message and no longer requires callers to awkwardly
append it after serialization.  This is especially useful in human-
readable formats like JSON (see the `transfer_with_payload` test in
token.rs for an example of this simplification).
The main downside is that this now requires explicit type annotations
when using the non-payload3 …
=> sdk/rust: Properly support tokenbridge payload3 messages

node/hack/accountant/send_obs.go, node/pkg/accountant/accountant.go, node/pkg/accountant/accountant_test.go, node/pkg/accountant/metrics.go, node/pkg/accountant/submit_obs.go, node/pkg/accountant/submit_obs_test.go, node/pkg/accountant/watcher.go, node/pkg/accountant/watcher_test.go, node/pkg/wormconn/clientconn.go
This PR enhances the accountant module in the guardian to submit requests in batches.
It also supports the latest interface changes with the smart contract.
Fixes #2188
Change-Id: I3f950c73265f40b2542a9b1222b2df67cb1964b0
=> Node/Acct: batch requests

node/cmd/guardiand/adminserver.go, node/cmd/guardiand/node.go, node/pkg/governor/governor_monitoring.go, node/pkg/p2p/p2p.go, node/pkg/processor/broadcast.go, node/pkg/processor/cleanup.go, node/pkg/processor/processor.go, node/pkg/watchers/algorand/watcher.go, node/pkg/watchers/aptos/watcher.go, node/pkg/watchers/cosmwasm/watcher.go, node/pkg/watchers/evm/watcher.go, node/pkg/watchers/solana/client.go, node/pkg/watchers/wormchain/watcher.go, sdk/vaa/structs.go
there are no functional changes in this PR. 
I am adding read/write type constraints to the main channels defined in cmd/guardiand/node.go. This makes the code easier to audit.
=> node: add channel read/write type constraints

node/cmd/guardiand/adminclient.go
This allows copying and pasting transactions from montioring tools or an explorer to be reobserved.
Fixes #2273
=> node: strip leading 0x for send-observation-request

cosmwasm/Cargo.lock, cosmwasm/contracts/wormchain-accounting/schema/wormchain-accounting.json, cosmwasm/contracts/wormchain-accounting/src/contract.rs, cosmwasm/contracts/wormchain-accounting/src/msg.rs, cosmwasm/contracts/wormchain-accounting/src/state.rs, cosmwasm/contracts/wormchain-accounting/tests/missing_observations.rs, cosmwasm/contracts/wormchain-accounting/tests/submit_observations.rs, cosmwasm/contracts/wormchain-accounting/tests/submit_vaas.rs, cosmwasm/packages/accounting/Cargo.toml, cosmwasm/packages/accounting/src/state/addr.rs, cosmwasm/packages/wormhole-bindings/src/fake.rs
When submitting a batch of observations, we don't want an observation
for an already committed transfer to fail the entire batch.  This leads
to more complexity in the guardian and also delays all the legitimate
observations by at least one more block (~5 seconds).
Fix this by returning the transfer status of each observation as part
of the response data.  Observations for committed transfers will get
a `TransferStatus::Committed` response without failing the tx as long
as the digest of the observation matches the digest of the committed
transfer.  Digest mismatches are still an error and will fail the entire
batch.
Part of #2188
=> cosmwasm: accounting: Return transfer status for observations

wormchain/devnet/base/config/config.toml, wormchain/devnet/client/config/config.toml, wormchain/devnet/create-config.sh
this fixes the incessant `wormchain │ {"level":"error","module":"p2p","err":"EOF","peer":{"Logger":{},"Data":{}},"time":"2023-01-19T01:56:18Z","message":"Stopping peer for error"}` log in CI
=> wormchain - peer-exchange reactor off by default

wormchain/app/app.go
Fixes the following issue:
```
failed to execute message; message index: 0: x/wasmd not set: feature not supported
```
when trying to `msgStoreCode` when calling via the wormhole module.
=> wormchain: fix wormhole keeper wasmd field

cosmwasm/contracts/cw20-wrapped/src/contract.rs, cosmwasm/contracts/token-bridge/src/contract.rs, cosmwasm/contracts/token-bridge/src/token_address.rs, cosmwasm/contracts/wormhole/src/error.rs, sdk/rust/core/src/serde_array.rs, sdk/rust/serde_wormhole/src/lib.rs, terra/contracts/cw20-wrapped/src/contract.rs, terra/contracts/nft-bridge/src/contract.rs, terra/contracts/nft-bridge/src/state.rs, terra/contracts/nft-bridge/src/token_id.rs, terra/contracts/token-bridge/src/contract.rs, terra/contracts/wormhole/src/error.rs
Latest clippy triggers errors resemble:
```
error: variables can be used directly in the `format!` string
--> core/src/serde_array.rs:26:9
|
26 |         write!(formatter, "an array of length {}", N)
|         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
|
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#uninlined_format_args
```
This PR fixes these errors in _sdk/rust_, _cosmwasm_ and _terra_ directories.
1. Verify that Github CI works.
2. Review code change.
=> Fix Clippy Errors

Tiltfile, wormchain/ibc-relayer/chains/wormchain.json
Updates the devnet k8s service name of wormchain for IBC. `guardian-validator` is out of date. cc @nik-suri
=> wormchain ibc - update wormchain service name

solana/devnet_setup.sh
Fixes a flakiness in the solana deploy when starting multiple worm commands in parallel without a config present.
=> tilt: solana deploy fix

README.md
Replace link to docs with book.wormhole.com vs the deprecated docs site.
=> docs: remove README link to deprecated docs site

devnet/node.yaml, node/hack/accountant/send_obs.go
Updates some node config values for wormchain - service name and accountant contract address.
The contract address is what it will be when the contract-deploy PR stack lands. This change is not in the deploy PR stack because there are no dependencies between changes in the stack and this change.
=> node - wormchain config

wormchain/build/config/app.toml, wormchain/build/config/client.toml, wormchain/build/config/config.toml
Adds the cosmos default comments and options from cosmos `init` to `wormchain/build` config files.
It's helpful to have the comments describing what the files and options do. Also some config options were missing, so those got added back.
=> wormchain - config comments and defaults

node/pkg/common/scissors.go
This PR initializes the "run with scissors" metrics so that they will show up even if there have not been any errors.
Change-Id: I018a663aa5b9ea902f934ab71c23b1786c8aeeb0
=> Node: Initialize scissors metrics

node/cmd/guardiand/node.go, node/pkg/accountant/accountant.go, node/pkg/accountant/accountant_test.go, node/pkg/accountant/audit.go, node/pkg/accountant/metrics.go, node/pkg/accountant/query_test.go, node/pkg/accountant/submit_obs.go, node/pkg/accountant/submit_obs_test.go, node/pkg/accountant/watcher.go, node/pkg/accountant/watcher_test.go, node/pkg/processor/processor.go, node/pkg/wormconn/query.go
This PR implements the global account audit in the guardian. It verifies that the set of pending transfers the guardian knows about matches what the smart contract thinks. If mismatches are detected, it will either resubmit the observation to the contract or request a reobservation from the local watcher.
Additionally, this PR cleans up a couple of minor issues left over from the previous code review.
Fixes #2002 
Change-Id: I643ce699b5d5e21129d957dae8677e8f2fccdbfd
=> Node/Acct: audit stuck pending

node/pkg/accountant/audit.go, node/pkg/accountant/query_test.go
Fix for parsing the json returned for a pending transfer on the `batch_transfer_status` query. Was not able to test this until multiple guardian support was added.
=> Node/Acct: Pending status query fix

node/pkg/watchers/aptos/watcher.go, node/pkg/watchers/cosmwasm/watcher.go, node/pkg/watchers/evm/watcher.go, node/pkg/watchers/near/metrics.go, node/pkg/watchers/near/poll.go, node/pkg/watchers/solana/client.go, node/pkg/watchers/sui/watcher.go, node/pkg/watchers/wormchain/watcher.go
This change is the first in what will likely be a series of changes to log less debugging information by default. Useful non-debug data should be returned from the guardian at the info log level.
I looked through each guardian by searching for `logger\.Info` and updating where it made sense.
=> Slightly less verbose guardian logging at info level

node/pkg/watchers/evm/connectors/poller.go
Breaking up the pollBlocks function to handle individual timeouts. This fixes an issues seen in production with the Optimism watcher. Some nodes may not have been able to make all of the queries in a finalized block set within 15s.
=> node/pkg/watcher: add timeouts

sui/token_bridge/sources/bridge_state.move, sui/wormhole/sources/dynamic_set.move, sui/wormhole/sources/guardian_set_upgrade.move, sui/wormhole/sources/myvaa.move, sui/wormhole/sources/state.move, sui/wormhole/sources/wormhole.move
- Enforce _equality constraint_ for user-supplied fee coins. User now has to supply just the right amount of fee coins (formerly could supply more than necessary, core bridge would not give refund for surplus portion)
- Deposit fees into designated repository `FeeCustody` in the core bridge instead of deployer account `@wormhole`, because the deployer account should not have access to fees.
=> sui: wormhole message fee equality check, deposit into core bridge

scripts/contract-upgrade-governance.sh
Just a few tweaks to the script that generates contract upgrade governance to make it support pyth. I tried adding the custom RPC as part of the URL but could get it to work, so it is just a note for the user to set that by hand.
Change-Id: I9c40498ef9849979f89e8d48d60333932f8a696f
=> Deploy: Make contract upd script support pyth

node/pkg/governor/governor.go, node/pkg/processor/processor.go
This PR addresses a theoretical security issue in the governor where a message that should not be governed is somehow injected into the governor and then played out by the governor after the window expires.
Fixes #2335
=> Node/Gov: add is governed check

node/pkg/common/grpc.go
**Issue**: JSON-Web requests are being logged with `"peer.address": "@"` because they go through the `grpc-gateway`. 
**Solution**: Also log the `x-forwarded-for` header, which is set by `grpc-gateway`. This may also help in similar cases where Guardians are running reverse proxies and want to log IP addresses of the original caller. 
**Testing**: I tested this change locally by running `guardiand` outside of Tilt. If you run it inside of Tilt, the kube proxy will unfortunately hide the IP address of the caller.
=> node/grpc: add logging of x-forwarded-for to gRPC middleware

node/cmd/guardiand/adminserver.go
This PR simply adds the Optimism RPC to the dump_rpcs command.
In the future, we'll figure out a way to do this automatically.
=> node/cmd: add optimism

sui/token_bridge/sources/create_wrapped.move, sui/token_bridge/sources/objects/native_asset.move, sui/token_bridge/sources/objects/registered_tokens.move, sui/token_bridge/sources/objects/wrapped_asset.move, sui/token_bridge/sources/state.move
- Make `native_asset` and `wrapped_asset` non-objects by removing their `UID` field (a gas optimization)
- Write unit test for `token_bridge/objects/native_asset.move`
=> sui: test `native_asset`, demote `native_asset` and `wrapped_asset` to non-Sui objects

sui/token_bridge/sources/attest_token.move, sui/token_bridge/sources/complete_transfer.move, sui/token_bridge/sources/complete_transfer_with_payload.move, sui/token_bridge/sources/objects/native_asset.move, sui/token_bridge/sources/objects/registered_tokens.move, sui/token_bridge/sources/state.move, sui/token_bridge/sources/transfer_tokens.move
- It is unnecessary for the coin `custody` embedded in the `NativeAsset` object to have the `key` ability, because it never exists in the global object store and instead is stored within another object. Therefore it makes more sense for it to be a `sui::balance::Balance`, which only has a `store` ability, instead of a `sui::coin::Coin`, which has both `key` and `store` abilities.
```
struct NativeAsset<phantom C> has store {
custody: Balance<C>,
token_address: ExternalAddress,
decimals: u8
}
```
- Using `Balance` in `native_asset.move` also has the added benefit that creation of a new balance object does not require `ctx` as an input arg. This simplification propagates to several other areas of the codebase, including `attest_token` and `register_native_token`.
=> sui: use `Balance` instead of `Coin` for `NativeAsset.custody`

sui/token_bridge/sources/objects/wrapped_asset.move
Write a test for creation and destruction of `WrappedAssets`. Since the mint and burn functionalities are already tested in `registered_tokens.move`, we do not add test coverage for them here.
=> sui: test `wrapped_asset.move`

node/cmd/guardiand/node.go, node/pkg/watchers/evm/watcher.go
This PR supports Bedrock and pre-Bedrock Optimism nodes.  The presence of the CTC contract and RPC indicates it will run in pre-Bedrock mode.
This will stay a draft until the testnet guardian node is switched over to Bedrock.
=> node: Bedrock changes

sui/Docker.md, sui/Dockerfile
- previously deploy wormhole was giving the error `Local version of dependency 0000000000000000000000000000000000000002::ecvrf was not found.`
- this update attempts to fix it by updating the Sui Docker image in [ghcr](https://github.com/orgs/wormhole-foundation/packages/container/package/sui) to a newer `0.25.0` version
=> sui: update to more stable 0.25.0 version 

devnet/node.yaml, node/cmd/guardiand/adminserver.go, node/cmd/guardiand/node.go, node/cmd/guardiand/publicrpc.go, node/cmd/guardiand/publicweb.go, node/cmd/spy/spy.go, node/cmd/spy/spy_test.go, node/pkg/common/grpc.go, node/pkg/telemetry/telemetry.go
fixes #2370 
* `--publicRpcLogDetail [string]`
* `none` -- no logging of gRPC requests at all
* `minimal` -- only log gRPC methods
* `full` (default) -- additionally log user-agent and gRPC request payload
* `--logPublicRpcToTelemetry [bool]`
* `false` do not send publicrpc logs to Google Cloud Logging
* `true` (default) -- (current behavior)
=> node: add request logging with --publicRpcLogDetail and --logPublicRpcToTelemetry

node/pkg/watchers/evm/connectors/get_time_of_block.go, node/pkg/watchers/evm/watcher.go
The `ArbitrumConnector` in the EVM watcher is now also being used for Optimism Bedrock and Base, so this PR renames it to `ConnectorWithGetTimeOfBlock` since that is what it really provides.
=> Node: Rename Arbitrum connector

clients/js/networks.ts
Confirmed with the Acala team that the testnet endpoints have changed to these.
=> Client/js: Update karura/acala testnet endpoints

sui/token_bridge/sources/complete_transfer_with_payload.move, sui/token_bridge/sources/dynamic/registered_emitters.move
- add custom, more informative error types, so we don't throw uninformative standard library errors
- assert preconditions in `registered_emitter.move` `new`, `add`, `external_address` functions
- write tests exercising intended function behavior as well as individual assertions (negative test cases)
=> sui: test token bridge `dynamic/registered_emitters`

sui/token_bridge/sources/create_wrapped.move, sui/token_bridge/sources/testing/wrapped_coin_12_decimals.move, sui/wormhole/sources/myvaa.move
- add tests for update registered coin metadata, including negative test cases for each assertion
=> sui: test update registered coin metadata

node/cmd/guardiand/node.go, node/pkg/accountant/accountant.go
This PR fixes two issues identified in the roll out of log only mode.
1. A check was left in for `wormchainLCD`, even though it isn't used.
2. There can be a burst of resubmissions on startup, resulting in a channel overflow. So this increases the submission channel size to attempt to avoid that.
=> accountant fixes

node/pkg/watchers/aptos/watcher.go
The aptos reobservation code is always parsing the "transaction hash" (which is really the native event sequence number) as 0.
I used https://replit.com/languages/go to test
```go
package main
import "fmt"
import "encoding/binary"
import "encoding/hex"
func main() {
txHash, err := hex.DecodeString("00000000000000000000000000000000000000000000000000000000000026f1")
if err != nil {
fmt.Printf("ERROR")
return
}
wrongSeq := binary.BigEndian.Uint64(txHash)
fmt.Printf("WRONG: %d\n", wrongSeq)
nativeSeq := binary.BigEndian.Uint64(txHash[24:])
fmt.Printf("RIGHT: %d\n", nativeSeq)
}
```
result
```
WRONG: 0
RIGHT: 9969
```
=> node: fix aptos reobservation

sui/token_bridge/sources/objects/wrapped_asset.move, sui/token_bridge/sources/objects/wrapped_coin.move
- write test for `wrapped_coin.move` in which we create and destroy a wrapped coin
=> sui/token_bridge: test `wrapped_coin.move`

sui/token_bridge/sources/transfer_tokens.move
- examine transaction effects of `transfer_token` and assert that number of emitted user events is 1 (corresponding to publishing of Wormhole message for that transfer),
- delete some instances of `next_tx`
=> sui/token_bridge: check transfer tokens tx effects 

relayer/spy_relayer/README.md
Having two bootstrap nodes allows an outage of the certus one guardian to not cause too much hassle with existing spy instances or new guardians restarting.
Thanks @fchantada and the xLabs team for adding the dns and helping set this up.
=> relayer: update docs on running a spy

node/cmd/guardiand/node.go, node/pkg/telemetry/telemetry.go, node/pkg/telemetry/telemetry_test.go
1. Fix a nullpointer dereference bug caused by not cloning everything in `(enc *guardianTelemetryEncoder) Clone()`
2. Fix a bug that caused logs marked with `_privateLogEntry` to still be sent to telemetry because when a child logger is created (`logger.With(zap.Bool("_privateLogEntry", true))`) the extra fields will go into the encoder's buffer and will not be passed to `EncodeEntry(entry zapcore.Entry, fields []zapcore.Field)`. This bug had no production impact because the telemetry logger was broken (see (1))
3. make the telemetry module testable and add unit tests
=> node/telemetry: fix nullpointer, _privateLogEntry, tests

node/pkg/accountant/audit.go, node/pkg/accountant/data_for_test.go, node/pkg/accountant/query_test.go
When a guardian restarts, it may attempt to query for many pending transfers, which can cause the query to run out of gas and fail. This PR breaks those large queries up into a series of smaller ones. Based on testing by @evan-gray, we believe we could do up to 750 queries per batch. This change uses a more conservative value of 500 queries per batch.
Please do not be put off by the number of lines in this PR. The vast majority is populating data used for testing (as well as the actual tests).
=> Node/Acct: Handle large batch status queries

sui/token_bridge/Move.toml, sui/wormhole/Move.toml, sui/wormhole/sources/datatypes/guardian_pubkey.move, sui/wormhole/sources/myvaa.move
- Make contracts compatible with latest Sui version `0.27.1` by fixing imports
- Update core and token bridge Move.toml files to use new `0.27.1` rev: `157ac72030d014f17d76cefe81f3915b4afab2c9` 
- Fix `make-docker` tests
=> sui: update Move.toml rev to `0.27.1`

wormchain/Makefile
Guardians provided some feedback that the binary could get out of date and the makefile recipe sometimes wouldn't rebuild it.  This helps make it a little more foolproof.
=> wormchain: make recipe easier to use for making release build

wormchain/Makefile
More feedback: would be better to include the "v" in the tag name so the version matches the tag exactly.  Sorry would have been better to include with #2519.
=> wormchain: dont remove v in tag name for release

sui/token_bridge/sources/state.move, sui/token_bridge/sources/transfer_tokens.move, sui/token_bridge/sources/transfer_tokens_with_payload.move
- Add two tests `for transfer_tokens_with_payload` (one each for native and wrapped tokens). Previously there were no tests specific to this function.
- Inspect tx effects to make sure a single event was emitted corresponding to the publishing of a Wormhole message.
=> sui/token_bridge: test `transfer_tokens_with_payload` with check on tx_effects

node/cmd/guardiand/adminserver.go
Amount conversion overflow flag was incorrectly interpreted as "ok" flag.
=> node: fix deserialization issue for modify_message

sui/wormhole/sources/dummy/dummy_sui_package.move, sui/wormhole/sources/setup.move
Currently, because Mysten has not yet release the contract upgrade mechanism, this PR creates a dummy UpgradeCap in `init` so that we can keep the upgrade code paths introduced in #2494
=> sui: create mock upgrade cap in init

clients/js/cmds/sui.ts, clients/js/sui.ts, sui/scripts/deploy, sui/wormhole/sources/dummy/dummy_sui_package.move, sui/wormhole/sources/setup.move
The deploy script, which previously wrote output of sui CLI commands to files and manually parsed that output, now simply relies on worm CLI commands. This PR introduces a new script called deploy to match the functionality from Aptos; the older deploy.sh script may be deprecated and removed in a future PR.
Points of consideration:
The deploy script still necessarily relies on output of worm CLI commands. This can be avoided by creating a worm CLI command that deploys and initializes the core and token bridge in one command, but it's not immediately obvious to me that it's worth writing something like that.
This new deploy script no longer writes values such as WH package ID to an env file at the end. If this is truly necessary, I think it would be more elegant to find a way to query the …
=> sui: make deploy script use worm CLI

sui/Docker.md, sui/Dockerfile, sui/Dockerfile.base
This PR adds `worm` support to the Sui container so that we can deploy contracts to Tilt on startup (since this depends on `worm` CLI commands). Support is added to the base Docker image so as to not increase build times and a new release has been cut and published.
=> sui: worm support

spydk/js/src/__tests__/integration.ts
This doesn't fix everything that is wrong with the github tilt tests.  But it does appear to fix one thing.
=> spydk: debugging

clients/js/cmds/sui.ts, sui/scripts/deploy.sh
This PR allows for the publishing of messages through the `worm` CLI. The deploy script also now prints out the `publish-message` command with the args filled in from the rest of the script. This command can simply be copy and pasted into terminal to publish messages. The output of the publish command is also printed to the console.
=> clients/js: fix sui publish message

sui/scripts/node_builder.sh
Quick PR to bump rev to the one that corresponds to Sui 0.29.1 and is pinned in the `Move.toml` files in each of the contract directories.
=> sui: bump rev for node_builder.sh

sui/Dockerfile, sui/Makefile, sui/examples/core_messages/Makefile, sui/examples/core_messages/Move.devnet.toml, sui/examples/core_messages/Move.lock, sui/examples/core_messages/Move.toml, sui/examples/core_messages/sources/sender.move
=> sui: fix core_messages example contract

sui/token_bridge/sources/setup.move, sui/token_bridge/sources/state.move, sui/wormhole/sources/setup.move, sui/wormhole/sources/state.move
The existing `UpgradeCap` check would fail when we try to set up the contract after publishing. The reason is `0x0` is the published package address (which originates from _Move.toml_ when a contract is built prior to publishing).
Added a generic method to assert that an `UpgradeCap` belongs to `T` object's package.
=> sui: fix upgrade cap check

clients/js/cmds/Yargs.ts, clients/js/cmds/sui/deploy.ts, clients/js/cmds/sui/index.ts, clients/js/cmds/sui/init.ts, clients/js/cmds/sui/publish_message.ts, clients/js/cmds/sui/utils.ts, clients/js/main.ts
It's not possible to add more subcommands or options to the `sui` command in `worm` CLI because the `yargs` type becomes too large and Typescript throws this error: `Type instantiation is excessively deep and possibly infinite`. As a result, this PR splits the `sui` subcommands across several files and coalesces them in `cmds/sui/index.ts`. A `Yargs` class has been added to enable chaining of these refactored subcommands.
=> clients/js: refactor worm sui cli commands to prevent type becoming too large

Dockerfile.const, clients/js/cmds/generate.ts, clients/js/cmds/submit.ts, clients/js/cmds/sui/deploy.ts, clients/js/cmds/sui/init.ts, clients/js/consts.ts, clients/js/sui/consts.ts, clients/js/sui/utils.ts, devnet/sui-devnet.yaml, scripts/devnet-consts.json, scripts/guardian-set-init.sh, sui/Docker.md, sui/Dockerfile, sui/scripts/deploy.sh, sui/scripts/register_devnet.sh, sui/scripts/start_node.sh, sui/scripts/wait_for_devnet.sh
This PR updates the Sui deploy script to accept an optional `private-key` flag to allow for the use of a custom private key to sign transactions with. This is especially useful for contributors who are using a local Sui validator instead of Tilt, so that they can substitute the hardcoded active key from Tilt with their own.
Resolves #2595
=> sui: add custom key support to deploy script

clients/js/cmds/sui/init.ts, clients/js/cmds/sui/publish_message.ts, clients/js/sui/error.ts, clients/js/sui/utils.ts, sui/examples/core_messages/Move.lock, sui/scripts/deploy.sh, sui/token_bridge/Move.lock
The token bridge upgradeability refactor in #2516 caused some things to break in the `worm` CLI. This PR fixes a few changed func and struct names.
Additionally, although `getOwnedObjects` returns all objects of a given type owned by a given address, a user may own multiple structs with the same type, such as `0x2::package::UpgradeCap`. The `UpgradeCaps` specifically (and possible other such structs) have a couple of fields in the fetched data that we use to differentiate between them.
=> clients/js: reflect token-bridge-cleanup updates in worm CLI

.github/ISSUE_TEMPLATE/tracking_issue.md
redux of #2539 that was scrapped due to a rebase going awry
closes #2538
Updates the tracking issue template to use the new tasklist markdown that synergizes better with Projects
=> Update tracking issue markdown

clients/js/cmds/sui/init.ts, clients/js/cmds/sui/publish_message.ts, clients/js/sui/utils.ts
This PR normalizes Sui types and addresses in comparisons to guard against missing prefixes and leading 0s. It is the case that the Sui RPC returns some addresses with leading 0s and others without.
=> sui: normalize addresses and types in comparisons

aptos/coin/Move.toml, aptos/deployer/Move.toml, aptos/nft_bridge/Move.toml, aptos/token_bridge/Move.toml, aptos/wormhole/Move.toml
This ensures that the contracts build against the framework that are deployed on mainnet. We should still add a CI action that builds against `mainnet` to learn about breaking changes.
=> aptos: pin framework deps to `mainnet_20221115`

.github/workflows/build.yml, Tiltfile, clients/js/consts.ts, clients/js/sui/consts.ts, clients/js/sui/publish.ts, sui/Docker.md, sui/Dockerfile, sui/Dockerfile.base, sui/Makefile
This PR fixes an incorrect Sui version in a previously pushed image and builds `clients/js` in the main Dockerfile instead of the base image that it uses. This should significantly speed up local development but we will have to mindful to revert this change before we merge `sui/integration_v2` into `main`.
=> sui: fix tilt & build CLI in main sui Dockerfile

cosmwasm/Cargo.lock, cosmwasm/contracts/cw20-wrapped/Cargo.toml, cosmwasm/contracts/global-accountant/Cargo.toml, cosmwasm/contracts/mock-bridge-integration/Cargo.toml, cosmwasm/contracts/mock-bridge-integration/src/lib.rs, cosmwasm/contracts/token-bridge/Cargo.toml, cosmwasm/contracts/token-bridge/src/lib.rs, cosmwasm/contracts/wormhole/Cargo.toml
Seems like a lot of dependencies have been copy/pasted — would be good to stop this practice in the future so we avoid any unnecessary compatibility issues, which makes it harder for others to import these libs and build on top of wormhole.
=> cosmwasm: clean up unused dependencies

node/pkg/governor/governor.go, node/pkg/governor/governor_prices.go, node/pkg/governor/governor_test.go
As the number of tokens monitored by the governor increases (to something over 500), the CoinGecko query will eventually fail with a "rate limit exceeded" error. This PR breaks the queries up into chunks of 200 tokens, with a one second sleep between each query.
=> Node/Gov: Split up CoinGecko queries

cosmwasm/Cargo.lock, cosmwasm/contracts/global-accountant/tests/chain_registration.rs, cosmwasm/contracts/global-accountant/tests/submit_vaas.rs, cosmwasm/contracts/wormhole/Cargo.toml, cosmwasm/contracts/wormhole/src/contract.rs, cosmwasm/packages/wormhole-bindings/Cargo.toml, cosmwasm/packages/wormhole-bindings/src/fake.rs
See https://github.com/RustCrypto/elliptic-curves/blob/master/k256/CHANGELOG.md for changes to the `k256` library from `0.9.4` to `0.11`.
Most notable are:
1. The function renaming of `recover_verify_key_from_digest_bytes => recover_verifying_key_from_digest_bytes`
2. Using the `sec1` crate, which changes the `EncodedPoint` type. The `EncodedPoint` type no longer has a `decompress` method, so we use the affine point conversion: https://github.com/RustCrypto/elliptic-curves/pull/435/files
=> cosmwasm: bump k256 dependency to 0.11

sdk/js/CHANGELOG.md, sdk/js/package-lock.json, sdk/js/package.json, sdk/js/src/algorand/Algorand.ts, sdk/js/src/cosmwasm/query.testnet.test.ts, sdk/js/src/token_bridge/attest.testnet.test.ts, sdk/js/src/token_bridge/attest.ts, sdk/js/src/token_bridge/createWrapped.ts, sdk/js/src/token_bridge/getForeignAsset.ts, sdk/js/src/token_bridge/getIsTransferCompleted.ts, sdk/js/src/token_bridge/getIsWrappedAsset.ts, sdk/js/src/token_bridge/getOriginalAsset.ts, sdk/js/src/token_bridge/index.ts, sdk/js/src/token_bridge/injective.ts, sdk/js/src/token_bridge/redeem.ts, sdk/js/src/token_bridge/transfer.ts, sdk/js/src/token_bridge/updateWrapped.ts, sdk/js/src/utils/injective.ts
I encountered issues installing the sdk on a fresh Ubuntu image. This patch release of the injective sdk fixes a `postinstall` script issue.
https://github.com/InjectiveLabs/injective-ts/commit/adb7c764ad00a0cfa38223cecf9b221873cd31b8
Furthermore, in the interim versions, Injective now provides esm builds. This along with marking of `"sideEffects":false` should allow for drastically reduced builds for consumers of the Wormhole sdk. See [Webpack Tree Shaking](https://webpack.js.org/guides/tree-shaking/#mark-the-file-as-side-effect-free) for more details.
To increase tree shaking potential, moving the rest of the chain-specific functions to their own files (instead of grouping them by function) could be considered.
=> sdk/js: bump injective sdk

node/cmd/guardiand/node.go, node/pkg/watchers/sui/watcher.go
This pulls the SUI guardian watcher from the sui/integration_v2 branch up and only allows it to run in devnet and testnet.
=> node: add sui watcher for devnet and testnet only

node/pkg/common/scissors.go, node/pkg/common/scissors_test.go
The existing RunWithScissors will hang if it tries to write to the error channel if there is no listener. This PR changes that. It also adds tests and metrics to allow us to verify the behavior.
=> Node: RunWithScissors should not hang on error if no listener

node/pkg/db/governor.go, node/pkg/governor/devnet_config.go, node/pkg/governor/governor.go, node/pkg/governor/governor_db.go, node/pkg/governor/governor_monitoring.go, node/pkg/governor/governor_prices.go, node/pkg/governor/testnet_config.go, node/pkg/p2p/p2p.go, node/pkg/processor/processor.go
This PR changes the governor to use `logger.With("component", "cgov")` rather than having "cgov: " prepended to every log message.
This is similar to what was done for the global accountant with PR #2574.
=> Node/Gov: Use component logging

clients/js/consts.ts, clients/js/sui/consts.ts, sdk/js/src/utils/consts.ts, sui/token_bridge/sources/resources/token_registry.move
Add a convenient mapping in the `TokenRegistry` that maps chain ID and address to a specific coin type as string. This mapping is helpful for someone interacting with the contract via RPC where a coin type needs to be specified when interacting with the Token Bridge. It is especially helpful when completing a transfer, where the coin type is not encoded the token transfer VAA (only the canonical token info).
1. Make sure Move tests still run via `make test`.
2. Review the new member `coin_type` and how it is used when adding native and wrapped assets.
3. Review tests that validate `coin_type` entries.
=> sui: add coin type mapping using token info as key

.github/workflows/generic-relayer-docker.yml, relayer/generic_relayer/relayer-engine-v2/Dockerfile
Allow pushing the relayer engine docker image to ghcr so that relay providers can pull it automatically
=> Update docker push workflow

node/pkg/watchers/cosmwasm/watcher.go
The old block height query on Terra2 has stopped working.
See this doc for the API changes.
https://docs.terra.money/upgrade/
=> Node: Block height is always zero on Terra2

clients/js/consts.ts, clients/js/sui/consts.ts, sdk/js/src/utils/consts.ts, sui/token_bridge/sources/transfer_tokens.move, sui/token_bridge/sources/transfer_tokens_with_payload.move
The purpose of this PR is to replace the `ExternalAddress` type arguments with `vector<u8>` in both the `transfer_tokens` and `transfer_tokens_with_payload` functions.
=> sui: replace ExternalAddress with type vector

clients/js/consts.ts, clients/js/sui/consts.ts, sdk/js/src/token_bridge/__tests__/sui-integration.ts, sdk/js/src/utils/consts.ts, sui/Makefile, sui/examples/core_messages/sources/sender.move, sui/token_bridge/Makefile, sui/token_bridge/sources/attest_token.move, sui/token_bridge/sources/complete_transfer.move, sui/token_bridge/sources/complete_transfer_with_payload.move, sui/token_bridge/sources/governance/register_chain.move, sui/token_bridge/sources/messages/transfer_with_payload.move, sui/token_bridge/sources/migrate.move, sui/token_bridge/sources/state.move, sui/token_bridge/sources/test/token_bridge_scenario.move, sui/token_bridge/sources/transfer_tokens.move, sui/token_bridge/sources/transfer_tokens_with_payload.move, sui/token_bridge/sources/vaa.move, sui/wormhole/Makefile, sui/wormhole/sources/governance_message.move, sui/wormhole/sources/migrate.move, sui/wormhole/sources/publish_message.move, sui/wormhole/sources/resources/required_version.move, sui/wormhole/sources/test/wormhole_scenario.move, sui/wormhole/sources/vaa.move
- Add outbound types meant to be passed around to avoid breaking integrators when either Wormhole or Token Bridge are upgraded (e.g. `PreparedMessage` is now passed into `publish_message`, and `prepare_message` is a simpler method that does not require a reference to the Wormhole `State`).
- Split `complete_transfer` into two methods (in case a relayer were to manage its payouts via contract).
- Add `_from_tx` methods to execute these new two-step methods in one call, meant to be executed directly from a transaction.
- Add ability to disable (and re-enable) methods via `wormhole::required_version`.
- Fix comments
- Make sure Move tests run via `make test`
- Either review each commit sequentially or review the code diff
=> sui: add outbound types and other things

clients/js/sui/publish.ts, clients/js/sui/utils.ts
Resolves #2670 
This PR solves 504 errors (Gateway Time-out) while using `filter` params on API method `suix_getOwnedObjects`
A new method `findOwnedObjectByType` has  been added to directly download all `OwnedObjects` and navigate them until finding our target. 
This implementation uses `cursor` to search in every response page. You can check the API docs [here](https://docs.sui.io/sui-jsonrpc#suix_getOwnedObjects).
Further context is available [here]( https://github.com/wormhole-foundation/wormhole/issues/2670#issuecomment-1518415668) 👀
=> sui: lower rpc processing latency

clients/js/consts.ts, clients/js/sui/consts.ts, sdk/js/src/utils/consts.ts, sui/wormhole/Move.devnet.toml, sui/wormhole/Move.toml, sui/wormhole/sources/migrate.move, sui/wormhole/sources/state.move, sui/wormhole/sources/utils/package_utils.move, sui/wormhole/sources/version_control.move
Fixed `package_utils::init_package_info` where the pending package ID was inadvertently set to the zero address.
- Make sure Move tests run via `make test`
- Make sure all migrate methods in Wormhole make sense
=> sui/wormhole: fix `init_package_info`

sui/token_bridge/Move.lock, sui/token_bridge/sources/governance/upgrade_contract.move
- `&State` is a ref to token bridge state and not worm state
=> sui: fix typo in `authorize_governance`

node/pkg/accountant/accountant.go, node/pkg/governor/governor.go
Some of the guardians are noticing that after some length of time, their guardiand instance stops processing messages, which they report as the "RPCs stop working". Log analysis indicates that the issue is most likely that the main processor go routine is hanging up somewhere. Although we are not exactly sure what is happening, one possibility is that either the governor or the accountant is hanging while writing transfers to the database. Therefore, this PR adds logging around those writes. Since the governor and guardian only process token bridge messages, this should not cause an excessive amount of logging. Once this problem is resolved, the log messages will be removed.
=> Node: Add logging around DB writes

clients/js/README.md, clients/js/cmds/edit-vaa.ts, clients/js/cmds/verify-vaa.ts
This PR adds two new commands to the worm client:
- `worm edit-vaa` - Allows user to edit / create / sign a VAA.
- `worm verify-vaa` - Verifies a VAA by calling `parseAndVerifyVM` on the core contract on Ethereum.
=> Client/js: Add cmds to edit and verify VAAs

sdk/js/src/mock/governance.ts, sdk/js/src/mock/tokenBridge.ts
Fixed a couple of bugs in the mock subdirectory of the Javascript SDK.
1. `MockTokenBridge` was not properly serializing the symbol and name in the Wormhole message payload.
2. `GovernanceEmitter` was using the wrong chain ID.
- Make sure CI tests run
- Review trivial changes
=> sdk/js: fix `mock` bugs

cosmwasm/Cargo.lock, cosmwasm/contracts/token-bridge/Cargo.toml, cosmwasm/contracts/token-bridge/src/contract.rs, cosmwasm/contracts/token-bridge/src/msg.rs, cosmwasm/contracts/token-bridge/src/testing/tests.rs
I think it makes sense to remove the `terraswap` dependency from the `cw_token_bridge` for a couple reasons:
1. It’s an extra dependency that cosmwasm integrators need to pull in to build token bridge `ExecuteMsg` types.
2. The type is very simple and the dependency has functionality specific to `terra`, so it shouldn't be included in the general cosmwasm contract.
These `Asset` and `AssetInfo` types are generally quite useful in cosmwasm, and should ideally be pulled out of terraswap and committed upstream to one of the cosmwasm std libs. However, that is a longer process, so defining them in the token bridge is a good solution for the interim.
=> cosmwasm: remove terraswap dependency

node/cmd/guardiand/node.go, node/pkg/accountant/accountant.go, node/pkg/accountant/accountant_test.go, node/pkg/accountant/data_for_test.go, node/pkg/accountant/submit_obs.go
This PR addresses an issue being seen occasionally by the guardians, where guardiand stops processing messages. The logs indicate it is most likely an issue in the global accountant.
After studying the code, it looks like an issue where the accountant goes to publish a transfer back to the processor, but the processor happens to be in the accountant call to submit a new observation. Both cases requiring holding the same lock.
The channel used to publish transfers back to the processor did not have a capacity specified, so since the processor was busy in accountant (waiting on a lock), the write to the channel would block, causing a deadlock.
The solution is to specify a channel capacity and do a non-blocking write to the channel.
The bulk of the code in this PR is testing code to recreate …
=> Node/Gacct: Fix deadlock when publishing xfers

.github/CODEOWNERS
Update the code owners for /node/pkg/watcher to be common across all the watchers. Removed people who are no longer active on WH. Added other developers from the prodOps team.
=> Node: Update code owners for watchers

node/pkg/watchers/evm/connectors/common.go, node/pkg/watchers/evm/connectors/poller.go, node/pkg/watchers/evm/connectors/polygon.go, node/pkg/watchers/evm/watcher.go
=> node/watchers: address ToB findings

scripts/check-docker-pin.sh, scripts/check-npm-package-scopes.sh
This change reduces false negatives in the scope checking scripts by
* supporting spaces and other special characters in file paths
* using jq instead of a simple grep to parse the json
* being more restrictive in the regexes on what to allow to pass through
This addresses all review comments in the previously abandoned PR https://github.com/wormhole-foundation/wormhole/pull/1774
=> scripts/scope checkers: reduce false negatives

sdk/vaa/quorum.go, sdk/vaa/quorum_test.go
This is a belt and suspenders addition to the Guardians computation of quorum to ensure that negative numbers will panic rather than returning a viable quorum expectation.
=> sdk: assert no negative numGuardians in quorum calculation

sdk/rust/core/src/chain.rs
Chains `Btc`, `Base`, and `Sei` are currently missing from the rust sdk.
`Ropsten` was also removed in favor of `Sepolia` in the go sdk - this change does the same for the rust sdk.
=> sdk: rust: add Sei, Btc, and Base chains and change Ropsten to Sepolia

ethereum/contracts/interfaces/relayer/IWormholeReceiver.sol, ethereum/contracts/interfaces/relayer/IWormholeRelayer.sol, ethereum/contracts/relayer/coreRelayer/CoreRelayerBase.sol, ethereum/contracts/relayer/coreRelayer/CoreRelayerDelivery.sol, ethereum/contracts/relayer/coreRelayer/CoreRelayerGovernance.sol, ethereum/contracts/relayer/coreRelayer/CoreRelayerSend.sol, ethereum/contracts/relayer/coreRelayer/CoreRelayerSerde.sol, ethereum/forge-test/relayer/WormholeRelayerGovernance.t.sol
* rebased and further enhanced version of [PR2915](https://github.com/wormhole-foundation/wormhole/pull/2915) (which is now obsolete)
* refactor amount conversion code (source <-> target) to make it more uniform and legible
* improve contract upgrade mechanism in CoreRelayerGovernance
* check enum values before casting in CoreRelayerSerde to revert with intended error instead of panicking
* reorder checks in `payRefundToRefundAddress()` to check for `provider.isChainSupported()` first
* introduce and document distinction between versioning fields and payload ids
* remove TODOs and add documentation / make it more uniform
=> additional improvements / clean-up

ethereum/Makefile, ethereum/forge-test/Bridge.t.sol, ethereum/forge-test/Messages.t.sol, ethereum/forge-test/TokenImplementation.t.sol, ethereum/foundry, ethereum/foundry.toml
Newer versions of forge-std [like v1.0.0+](https://twitter.com/msolomon44/status/1587171153918840833?lang=en) include much improved fuzzing and invariant testing. To take advantage of that functionality, this PR upgrades both forge and forge-std.
To do that, it required changing the inheritance of the forge tests. I changed a bit of the logs in the test for truncateAddress with some help from @scnale since the previous version led to somewhat undefined behavior. I verified the changed tests run ✅ with the old and new version of forge-std.
It is highly recommended in your local checkout you run:
rm -rf ethereum/lib/forge-std
make forge_dependencies
=> Update forge-std to the latest

node/pkg/watchers/ibc/watcher.go
At some point, the format of the query used by the IBC watcher to get the chain / channel mapping changed from `"all_channel_chains"` to `{"all_channel_chains": {}}`. This is causing the watcher to fail. This PR fixes that.
=> Node: IBC Watcher channel query broken

ethereum/contracts/relayer/coreRelayer/CoreRelayer.sol, ethereum/forge-test/relayer/TestHelpers.sol, ethereum/ts-scripts/relayer/coreRelayer/deployCoreRelayer.ts, ethereum/ts-scripts/relayer/coreRelayer/upgradeCoreRelayerSelfSign.ts, ethereum/ts-scripts/relayer/helpers/deployments.ts
Originally, the defaultRelayProvider had to be baked into the bytecode via an immutable variable and then set in a parameter-less call to initialize() using said variable to aovid having a different deployment code (and hence a different deployment (=proxy) address) for the proxy.
Use of the create2 factory and its `Init` pattern (which always deploys the empty `Init` logic contract that is then immediately upgraded to the real logic contract) makes this kludge unnecessary and allows for a proper use of initialize()
(fixed version of [PR#2951](https://github.com/wormhole-foundation/wormhole/pull/2951))
=> add defaultRelayProvider as a parameter to initialize() and replace the current kludge

node/cmd/guardiand/node.go, node/cmd/guardiand/telemetry.go, node/pkg/telemetry/telemetry.go
The semantics of `--logPublicRpcToTelemetry` was inverted. 
The following options were added to `node`: 
* `--telemetryServiceAccountFile` lets one specify a Google Cloud credentials json to use instead of the encrypted default. This lets Guardian operators use their own Google Cloud logging project instead of the default one and also allows easier testing/debugging with a separate Google Cloud project. 
* `--telemetryProject` the name of the Google Cloud project where logs shall be sent to.
=> node/telemetry: Bugfix and additional debug options

Tiltfile, devnet/node.yaml, node/cmd/guardiand/node.go, node/cmd/guardiand/query.go, node/cmd/spy/spy.go, node/pkg/p2p/p2p.go, node/pkg/p2p/watermark_test.go
This PR adds a `--ccqEnabled` flag to `node.yaml` as well as a `--ccq` flag to tilt. It also adds a "ccq" feature flag to the heartbeat messages.
=> CCQ: Add enable flag and feature flag

cosmwasm/deployment/terra2/test/src/__tests__/bridge.ts, cosmwasm/deployment/terra2/test/src/helpers/client.ts
LocalTerra was updated to v2.4.0 and the LCD no longer returns HTTP errors on some transaction failures (not enough gas still returns an HTTP error). This caused some of the integration tests to break, because the typescript SDK would throw on those HTTP errors.
https://github.com/terra-money/LocalTerra/releases/tag/v2.4.0
=> terra2: Fix broken CI tests due to LocalTerra v2.4.0 update

.github/workflows/build.yml, node/pkg/watchers/near/metrics.go, node/pkg/watchers/near/nearapi/mock/mock_server.go, node/pkg/watchers/near/poll.go, node/pkg/watchers/near/tx_processing.go, node/pkg/watchers/near/watcher.go, node/pkg/watchers/near/watcher_test.go
The NEAR watcher unit tests have been intermittently failing, see e.g. 
https://github.com/wormhole-foundation/wormhole/actions/runs/4884237090/jobs/8716699257?pr=2850
https://github.com/wormhole-foundation/wormhole/actions/runs/4884164541/jobs/8716516861
https://github.com/wormhole-foundation/wormhole/actions/runs/4865612488/jobs/8676147944
https://github.com/wormhole-foundation/wormhole/actions/runs/4886760889/jobs/8722535032?pr=2858
https://github.com/wormhole-foundation/wormhole/actions/runs/5061553539/jobs/9085941996?pr=2968
The main issue seems to be in https://github.com/wormhole-foundation/wormhole/pull/2971/files#diff-541054d2cf5abedef3e9ef612b46f581e8d58ffab2479254b60986f57c7c12c2R57, where errors were previously not properly propagated. 
If the error is not properly propagated, …
=> node/near: Fix unit tests

Tiltfile, node/cmd/guardiand/node.go, node/cmd/guardiand/query.go
This PR adds the ccqAllowedRequestors parameter to the guardian config.
=> Node/CCQ: Add ccqAllowedRequesters

node/cmd/guardiand/node.go, node/cmd/guardiand/query.go, node/pkg/common/queryResponse.go, node/pkg/p2p/p2p.go, node/pkg/watchers/evm/watcher.go
This PR changes it so that query responses flow through the query handler, rather than directly from the watcher to p2p. This allows the handler to keep a cache of pending queries, and retry them. It retries a query every ten seconds for up to a minute, before giving up.
=> CCQ: Add request retries

.github/workflows/build.yml, sdk/vaa/quorum.go, sdk/vaa/quorum_test.go
This PR adds comments to better document CalculateQuorum and additionally adds some fuzz testing and a shortened run to the GitHub action flow to ensure it's always run briefly during each CI run.
=> sdk: add CalculateQuorum documentation and fuzz testing

node/cmd/guardiand/node.go, node/cmd/guardiand/query.go, node/pkg/common/queryRequest.go, node/pkg/common/queryResponse.go, node/pkg/watchers/evm/watcher.go
This PR eliminates the extra unmarshalling that was happening with query requests. It also factors out the request validation code so it can be more easily reused and tested.
=> CCQ: Validation and marshalling changes

clients/js/src/cmds/submit.ts
This PR extends the `worm submit` command to add the `--all-chains` option, which will submit the VAA to all chains defined on the network (mainnet/testnet), with the following exceptions:
- Only works for `RegisterChain` and `AttestMeta` VAAs.
- Skips the emitter / origin chain.
- The RPC must be defined in `network.ts`
- The target contract must be defined in `consts.ts`.
=> Client/js: Add submit for all chains

node/cmd/guardiand/admintemplate.go
This PR adds guardiand commands to generate prototxt for the Wormchain deploy commands:
```shell
$ build/bin/guardiand template wormchain-store-code --wasm-hash c9262d14fd2f5fe7ca2c272be609be2b25a22f10afe79b4726941da51eb27489
current_set_index:  3
messages:  {
sequence:  21314180802357929
nonce:  456824973
wormchain_store_code:  {
wasm_hash:  "c9262d14fd2f5fe7ca2c272be609be2b25a22f10afe79b4726941da51eb27489"
}
}
$ build/bin/guardiand template wormchain-instantiate-contract --code-id 5 --label ibcReceiver --instantiation-msg "{}"
current_set_index:  3
messages:  {
sequence:  13300675307875321402
nonce:  3949257006
wormchain_instantiate_contract:  {
code_id:  5
label:  "ibcReceiver"
instantiation_msg:  "{}"
}
}
$ build/bin/guardiand template wormchain-migrate-contract --code-id 5 …
```
=> Node: Add wormchain deploy admin commands

node/cmd/guardiand/adminverify.go, node/cmd/guardiand/node.go, node/pkg/adminrpc/adminserver.go, node/pkg/adminrpc/adminserver_test.go, node/pkg/node/adminServiceRunnable.go
No functional changes, only refactoring. 
This PR moves the adminserver into its own package. 
Context: this is part of cleaning up the guardiand package to make it more testable (more PRs coming). 
The adminserver could use some cleanup and refactoring as well, but this is out of scope of this PR.
=> node: move adminrpc from guardiand into own package

scripts/update-guardian-set.sh
This PR fixes a race condition in CI tests where the creation of the new-guardianset.prototxt led to Tilt reloading some resources, causing their state to be modified, which then could lead to failed CI tests
The problem is addressed by instead creating the file in /tmp/
=> scripts/update-guardian-set: move new-guardianset.prototxt to /tmp/

clients/js/package-lock.json, clients/js/package.json, clients/js/src/aptos.ts, clients/js/src/chains/sei/registrations.ts, clients/js/src/chains/sui/registrations.ts, clients/js/src/cmds/info/index.ts, clients/js/src/cmds/info/registrations.ts, clients/js/src/cmds/submit.ts, clients/js/src/emitter.ts, clients/js/src/evm.ts, clients/js/src/injective.ts, clients/js/src/solana.ts, clients/js/src/terra.ts
This PR adds a new worm cli command that can be used to dump the chain registrations for most of the chains:
`worm info registrations testnet aptos TokenBridge`
You can also use the `--verify` option to audit the returned registrations against the values in the `consts.ts` file.
This PR supersedes #3009 which is hopelessly out of date due to extensive refactoring in client/js.
=> Client/js: Add Info Registrations

node/go.mod, node/pkg/common/scissors_test.go, node/pkg/governor/governor_monitoring_test.go, node/pkg/p2p/watermark_test.go, node/pkg/watchers/near/nearapi/nearapi_test.go, node/pkg/watchers/near/watcher_test.go
Remove github.com/test-go/testify since there is github.com/stretchr/testify already.
=> node: rm dep github.com/test-go/testify

node/cmd/guardiand/node.go, node/pkg/p2p/p2p.go, node/pkg/watchers/ibc/watcher.go, node/pkg/watchers/ibc/watcher_test.go
This PR adds the wormchain version string to the IBC feature flag. The flag will look something like this:
`ibc:sei|v0.0.1` where `v0.0.1` is the wormchain version string from devnet.
=> Node: Make IBC watcher publish wormchain version

ethereum/forge-test/TokenImplementation.t.sol
In newer versions of forge, an assignment inside a view function generates an error, just tweaking this to it's one less thing to fix on our next forge update.
=> ethereum: fix view error with newer version of forge

ethereum/forge-test/TokenImplementation.t.sol
This reverts commit 05cec3d7293d056baffa6bde5ad84da893155fe3 (#3059)
The commit was erroneously included in anticipation of a forge version update, but it actually only generates an error with an outdated forge-stdlib version.
The old version's `vm.addr` function
(see
https://github.com/foundry-rs/forge-std/blob/ddb69063e4c9cc4aa863b224fc8a166be5d330ce/src/Vm.sol#L15) has no `pure` modifier, thus any function using it can not be `pure` (or `view`). The new version (see
https://github.com/foundry-rs/forge-std/blob/66bf4e2c92cf507531599845e8d5a08cc2e3b5bb/src/Vm.sol#L55) on the other hand does. In fact, with the new version, removing the modifier produces a warning.
=> Revert "ethereum: fix view error with newer version of forge"

ethereum/Makefile
This way, running `test-forge` is quicker. `make test` still runs all the tests.
=> ethereum/Makefile: split test-identifiers from test-forge target

Tiltfile, devnet/tests.yaml, node/cmd/guardiand/node.go, testing/Dockerfile.spydk.test, testing/sdk.sh, testing/spydk.sh, wormchain/contracts/tools/test_accountant.sh
This PR fixes a race condition in devnet where the p2p network may silently fail to start because at the time guardian-1 tries to connect to guardian-0 (bootstrat node) it may not be online yet. The race condition was more frequenly hit after a refactor, see https://github.com/wormhole-foundation/wormhole/pull/3024#issuecomment-1591803726
=> node: Wait for bootstrap guardian in devnet

aptos/scripts/README.md
Worm command is missing a couple params.
The current cURL results in a `resource_not_found` message. I think this is just because the wrong address is used so changed it to the core contract address.
=> Docs: fix Aptos worm send message command and URL to view events

node/cmd/guardiand/node.go, node/pkg/watchers/cosmwasm/watcher.go
On June 14, 2023, Terra Classic upgraded their cosmwasm version, which changed the format of message publications. They change from using `contract_address` to using `_contract_address` (like the other cosmwasm chains). This PR updates the watcher to reflect that.
=> Node/Watcher: Terra Classic fix

node/hack/release_verification/guardian_vaa_stats.go
This script can be used after a pre-release has been rolled out to a subset of mainnet guardians to verify that they are still participating in consensus as expected. E.g. as in the testing strategy for https://github.com/wormhole-foundation/wormhole/pull/3024
=> node/hack: add script for checking guardian participation in recent VAAs

node/pkg/accountant/accountant.go, node/pkg/governor/governor.go
These log messages were added to governor and accountant to help debug a deadlock in mainnet. That problem as been fixed, so these messages should be removed.
=> Node: Remove unnecessary debug logging

clients/js/README.md, clients/js/src/doc.ts, clients/js/src/main.ts
As reported in https://github.com/wormhole-foundation/wormhole/issues/3152 the `docs.ts` script meant to produce documentation for the CLI tool was producing incorrect subcommands. 
This was caused by re-using the `yargs` singleton that had state built up from other commands.
The fix here is to create a fresh copy for every invocation of `builder`
=> CLI: Fix bug in doc generator

node/pkg/processor/observation.go, node/pkg/processor/processor.go
When handling inbound signed VAAs with quorum, the processor looks to see if they are already in the database, and if so, it just returns without doing anything. It currently doesn't do that until after it verifies the signatures, which is wasted compute. This change moves the DB check ahead of that verification.
=> Node: Drop inbound signed vaas with quorum faster

sdk/js/src/utils/consts.ts
Typescript doesn't allow us to easily go from string literal types to array so lots of manual effort needs to happen in multiple places to do checks like isXXXChain. 
This modifies the chain name definitions to be arrays first and infer the string literal types from the arrays. 
1) should we export the XXXChainNames const?
2) should we add other chain types even for those that have only 1 instance? e.g. Algorand/Bitcoin
3) Left in a TODO for the terra chains since they're in both the CosmWasm and Terra definitions, do they need to be?
=> SDK: tweak typedefs to make doc generation easier

node/pkg/processor/cleanup.go, node/pkg/processor/observation.go
Looking at INFO logging for a random hour, for a random guardian (Staking Facilities), we saw about 3 million messages. Of those:
- `aggregation state for observation` occurred 1.3 million times.
- `quorum not met or already submitted, doing nothing` occurred 1.2 million times.
- `we have not yet seen this observation - temporarily storing signature` occurred 175K times.
None of these events are particularly noteworthy, so this PR changes them to debugs.
=> Node: Reduce info logging

ethereum/contracts/bridge/Bridge.sol, ethereum/contracts/bridge/interfaces/ITokenBridge.sol, ethereum/test/bridge.js
The purpose of this PR is to add the event `TransferRedeemed` to the token bridge. This will allow off-chain processes to track when a transfer has been redeemed.
=> evm: add TransferRedeemed event to Bridge.sol

node/pkg/processor/cleanup.go, node/pkg/processor/processor.go
The code in the processor cleanup routine was incorrectly retrying reobservations for **50 days** rather than five days. This PR changes it to retry for one day for observations we have seen and one hour for those we have not (which was previously 50 minutes, although the original comments said five minutes).
=> Node: Fix reobservation limits

node/pkg/p2p/p2p.go
The default buffer size for subscriptions is 32 messages.
This is apparently too small and causes issues with message delivery with log messages like:
```
INFO    pubsub  go-libp2p-pubsub@v0.9.3/pubsub.go:981   Can't deliver message to subscription for topic /wormhole/testnet/2/1/broadcast; subscriber too slow
```
which comes from
https://github.com/libp2p/go-libp2p-pubsub/blob/6d73cd4b56bf9d7fdd0c0caaed629a3d51027a75/pubsub.go#L981
The comment on the option provides a hint
https://github.com/libp2p/go-libp2p-pubsub/blob/master/pubsub.go#L1303-L1311
----
The choice of 1024 was somewhat arbitrary but "large enough"
It may be better to make this a package level const or add it to the arguments passed to `Run`, though that is already pretty thicc with arguments.
----
Are there any security …
=> Node: Increase subscription buffer size from 32 to 1024

node/pkg/watchers/sui/watcher.go, node/pkg/watchers/sui/watcher_test.go
Fixes: #2827
Previously, it prepended `ws://` to the address unlike any of the other websocket flags. This allows specifying it the same was as guardiand v2.16.0 or like the rest. In the future, we can remove the "legacy" way and make them all consistent.
=> node: fix url handling of the value to --suiWS

README.md
Book is no longer maintained.
This README could probably use a refresh with some more links/resources and a new image
=> docs: change link on README to point to docs site

node/pkg/watchers/sui/watcher.go
Some of the guardians are getting SUI errors:
```
jsonPayload: {
error: "json: cannot unmarshal string into Go struct field FieldsData.result.parsedJson.nonce of type uint64"
logger: "root.suiwatch"
message: "failed to unmarshal event message"
severity: "ERROR"
timestamp: "2023-07-12T17:14:17.588311789Z"
}
```
This PR adds a log message to try and determine what the bad message is.
=> watcher: add sui logging

node/cmd/guardiand/node.go, node/pkg/node/node_test.go, node/pkg/p2p/p2p.go
This change reduces the runtime of TestConsensus() in node_test.go from ~16s to ~3s and makes startup more reliable in devnet. 
Before this change, the heartbeat was sent immediately (after 1ns), but by then the network connections are not established yet and the heartbeat gets lost, so the tests needed to wait another 15s for the next heartbeat. 
After this change, we wait 2s to send out the first heartbeat, and by then the network is likely to be established. 
This change solves a problem during Guardian startup in devnet / Tilt: 
guardian-1 may start up before guardian-0 and therefore has no bootstrap node to connect to. 
guardian-1's messages then go into the void. 
This has been previously addressed in https://github.com/wormhole-foundation/wormhole/pull/3096 by essentially having …
=> node/p2p: improve startup

node/pkg/db/db.go, node/pkg/governor/governor.go, node/pkg/node/node_test.go, node/pkg/watchers/mock/watcher.go
This PR drastically decreases the log volume in the node_test.go.
=> node/node_test: improve logging

.gitignore, node/pkg/accountant/accountant_test.go, node/pkg/db/open.go, node/pkg/node/logcounter.go, node/pkg/node/node.go, node/pkg/node/node_test.go, node/pkg/node/options.go, node/pkg/p2p/p2p.go, node/pkg/watchers/near/nearapi/nearapi_test.go, node/pkg/watchers/near/watcher_test.go
* [increase inboundObservationBufferSize to 5000](https://github.com/wormhole-foundation/wormhole/pull/3135/commits/366c19740a42dff7f354b78905af55a537c37e98) because otherwise this channel too quickly reaches capacity. The 5000 is somewhat arbitrary and we can think more about the appropriate size, but for now it's large enough to run the benchmarks and not too large that it would take up too much memory or potentially add too much latency because processing 5000 observations should take ca. 1 second. 
* Implement BenchmarkConsensus in node_test.go to measure how long it takes to reach consensus on `n` messages with `m` guardian nodes. 
* Warn on certain channel overflows in p2p if in GoTest mode
* Count and report amount of logs generated per message during benchmarking
* Switch to …
=> node: Add benchmarks

node/cmd/spy/spy.go, node/pkg/common/msg_with_timestamp.go, node/pkg/node/node.go, node/pkg/p2p/p2p.go, node/pkg/p2p/watermark_test.go, node/pkg/processor/broadcast.go, node/pkg/processor/observation.go, node/pkg/processor/processor.go
This PR adds metrics to track delay on signed observations by adding two histograms.
One measures the delay from when P2P enqueues the observation on the channel until the processor reads it off the channel.
The second measures the total delay from when P2P enqueues the observation until the processor finishes processing it.
Here is sample output from multiple runs. The first three are using the standard single threaded processor. The second three are using `node_processor_multithreading`
`Standard processor:
PROCESSOR_METRICS       {"observationChannelDelay": "histogram:{sample_count:358602  sample_sum:1.020196794e+09  bucket:{cumulative_count:27698  upper_bound:10}  bucket:{cumulative_count:36184  upper_bound:20}  bucket:{cumulative_count:47105  upper_bound:50} …
=> Node: Processor delay metrics

sdk/js/package-lock.json, sdk/js/package.json, sdk/js/tsconfig.json
just bumped the version and added a field to `tsconfig.json`, `skipLibCheck` because `npm run build` complained:
```
node_modules/algosdk/dist/types/utils/utils.d.ts:41:6 - error TS1023: An index signature parameter type must be either 'string' or 'number'.
41     [x: symbol]: any;
~
```
=> SDK: bump algosdk version

sdk/js/src/relayer/relayer/helpers.ts
Running the `worm status ...` command causes an error message to be written to the console:
```
unknown modifier: ;
...
```
This seems to be caused by the fragment parser in the ethers library 
Tested with:
```ts
import { ethers } from "ethers";
(async function () {
const abi = [
"event LogMessagePublished(address indexed sender, uint64 sequence, uint32 nonce, bytes payload, uint8 consistencyLevel)",
];
const iface = new ethers.utils.Interface(abi);
console.log(iface.fragments[0].name);
const abix = [
"event LogMessagePublished(address indexed sender, uint64 sequence, uint32 nonce, bytes payload, uint8 consistencyLevel);",
];
const ifacex = new ethers.utils.Interface(abix);
console.log(ifacex.fragments[0].name);
})();
```
logging: 
```
LogMessagePublished
unknown modifier: ; …
```
=> SDK: remove semicolon in event definition

node/cmd/guardiand/node.go, node/cmd/spy/spy.go, node/pkg/gwrelayer/gwrelayer.go, node/pkg/gwrelayer/gwrelayer_test.go, node/pkg/node/node.go, node/pkg/node/node_test.go, node/pkg/node/options.go, node/pkg/p2p/p2p.go, node/pkg/p2p/watermark_test.go, node/pkg/processor/broadcast.go, node/pkg/processor/processor.go
The Gateway Relayer is a guardian module that looks for payload three transfers destined for the `ibc-translator` contract on Gateway/Wormchain and forwards those VAAs to that contract.
To enable the gateway relayer, specify the following guardian config parameters:
` --gatewayRelayerContract, --gatewayRelayerKeyPath, --gatewayRelayerKeyPassPhrase, --wormchainURL`
=> Node: Gateway Relayer

sdk/js/src/utils/consts.ts
Digging into an [issue ](https://github.com/wormhole-foundation/wormhole/actions/runs/5647923071/job/15299026706?pr=3206)while trying to upgrade the cli tool to the latest SDK I found that the `ChainProvider` was producing the incorrect type given a chain like `solana`
I traced this back to the `utils.ts` file and blame provided the jerk that committed [this change](https://github.com/wormhole-foundation/wormhole/commit/7de46f68b424723522e15d994c3851231748ba97)
Before:
After (+npm link the local version):
tbh I'm not crazy about this solution but it illustrates the issue. Happy to field other suggestions
=> SDK: fix chain id/name types

node/cmd/guardiand/node.go
skipPrivateLogs was erroneously hardcoded to `true` for Loki telemetry logging. This PR fixes that.
=> node: Fix skipPrivateLogs option in Loki telemetry

.github/CODEOWNERS
Proposing that we add @SEJeff to the governor CODEOWNER list.  This should add one person of redundancy when a code owner on governor is the proposer and cannot review their own code.
=> codeowners: add jeff to governor owners

node/pkg/processor/cleanup.go
retryLimitOurs defines how long this Guardian will keep an observation in the local state before discarding it.
Oservations from other Guardians can take up to 24h to arrive if they are held in their Governor. Therefore, this value should be greater than 24h.
=> node/proc: increase retryLimitOurs to 30h

node/pkg/db/db.go, node/pkg/processor/cleanup.go, node/pkg/processor/message.go, node/pkg/processor/observation.go, node/pkg/processor/processor.go
k.Timestamp is always equal to existing.Timestamp. Therefore `k.Timestamp.Sub(existing.Timestamp) > settlementTime` is always false. 
I am proposing to remove this dead code to avoid confusion. 
The intention of this code was to not make observations if there is a VAA already, but I think this is actually unwanted behavior because that would break re-observation requests and even if this was wanted, the check should've been done before accounting/governor and not after.
=> node/processor: Remove dead code

node/pkg/gwrelayer/gwrelayer.go
The gateway relayer is not detecting this error on a submit VAA:
"signature verification failed; please verify account number (35) and chain-id (wormchain-testnet-0): unauthorized"
=> Node/Gateway: Relayer not detecting error

node/cmd/guardiand/node.go, node/hack/accountant/send_obs.go, node/pkg/wormconn/clientconn.go, node/pkg/wormconn/send_tx.go
The ChainID parameter on wormchain transactions is hardcoded to be "wormchain". However, in testnet it should be "wormchain-testnet-0".
=> Node/Gateway: Wormconn chainID wrong for testnet

cosmwasm/contracts/global-accountant/tests/chain_registration.rs
Context: the CI rust toolchain uses the `stable` channel https://github.com/wormhole-foundation/wormhole/blob/753185e042132ad925257384a9ea714cdef6bff1/.github/workflows/build.yml#L348
https://github.com/rust-lang/rust/releases/tag/1.72.0 was released yesterday, which turns out includes a small change in the `rustfmt` formatting algorithm. I ran the new formatting tool
```shell
$ rustup default stable
$ rustup update
$ cargo fmt --all
```
=> cosmwasm: run cargo fmt using new stable 1.72.0

node/pkg/common/scissors.go, node/pkg/common/scissors_test.go
This PR adds a `StartRunnable` method to the `RunWithScissors` interface. This method allows you to control if panics should be caught or not, and is intended to eventually replace the `RunWithScissors` calls (which will be done with other PRs).
=> Node: Add StartRunnable to scissors

clients/js/src/cmds/aptos.ts
For some reason the bound variables in the lambda were underscored, unclear why. In turn, `yargs` referred to the package, resulting in runtime errors.
=> clients/js: fix aptos upgrade and migrate commands

sdk/js/CHANGELOG.md, sdk/js/package.json
`0.10.0` and `0.10.1` were published with a `test` tag.
=> sdk/js: version bump to resolve conflict

node/cmd/guardiand/node.go
The PythNet watcher now requires a websocket to function, this change makes it a required argument to guard against accidentally misconfigured guardians. We ran into this as the cause for missing signatures. As far as I can tell this is the only change needed, the Tiltfile is already configured with a websocket endpoint.
=> node/pkg/guardiand: require pythnetWS argument

node/pkg/node/node.go, node/pkg/node/node_test.go, node/pkg/node/options.go, node/pkg/processor/broadcast.go, node/pkg/processor/observation.go
Some performance improvements that don't change the protocol semantics. 
Benchmark on my machine (64 cores, 19 guardians, 1000 messages):
Before: 100 msg/s
After: 133 msg/s
=> node/processor: performance improvements

node/pkg/node/node_test.go
I was wondering if it was worthwhile to consider moving from ED25519 in the p2p network to RSA because RSA allows for faster signature verification, albeit larger signature size, and libp2p is verification-heavy. 
The benchmarks show that the libp2p RSA seems to be unoptimized and is actually slower than ED25519.
=> node/node_test: Add RSA to crypto benchmark

devnet/query-server.yaml, node/cmd/ccq/devnet.config.json, node/cmd/ccq/http.go, node/cmd/ccq/query_server.go, node/cmd/ccq/utils.go, sdk/js-query/src/query/ethCall.test.ts
This PR adds a configurable allow list to the `ccq_server` so that we can specify which users are allowed to make queries and which RPC calls they are allowed to make.
=> CCQ: Server allow list

SECURITY.md
- Halborn Wormchain and Accounting: These audits were based on an older version of Wormchain and Accounting that used modules instead of smart contracts. This older version never made it into production, hence I think the associated audit reports can be safely discarded.
- CertiK/Solitaire: This was consolidated together with CertiK/Solana into a single report. Therefore leaving the CertiK/Solana item but removing the CertiK/Solitaire item. 
- CertiK/Terra: Removing this item since this work was discontinued after Neodyme and Kudelski already audited the Terra contracts. 
- Hacken/NEAR: Removing this since the conversation with Hacken has stalled. Note that the Hacken audit of the Guardian part as well as the OtterSec audit of the NEAR smart contracts have both been published already.
=> SECURITY.md: Cleanup audit report list

ethereum/Makefile, ethereum/PROOFS.md, ethereum/forge-test/Getters.t.sol, ethereum/forge-test/Governance.t.sol, ethereum/forge-test/GovernanceStructs.t.sol, ethereum/forge-test/Implementation.t.sol, ethereum/forge-test/MessagesRV.t.sol, ethereum/forge-test/Setters.t.sol, ethereum/forge-test/Setup.t.sol, ethereum/forge-test/Shutdown.t.sol, ethereum/forge-test/TokenImplementation.t.sol, ethereum/forge-test/rv-helpers/IMyWormhole.sol, ethereum/forge-test/rv-helpers/KEVMCheats.sol, ethereum/forge-test/rv-helpers/MyImplementation.sol, ethereum/forge-test/rv-helpers/MySetters.sol, ethereum/forge-test/rv-helpers/TestUtils.sol, ethereum/run-kevm.sh, ethereum/wormhole-lemmas.k
* Add new Forge property tests for the Ethereum core messaging contracts in `forge-std`.
* Add wrappers for the `Getters`, `GovernanceStructs`, `Setters` and `Setup` tests to be executed symbolically by the [KEVM formal verification framework](https://github.com/runtimeverification/evm-semantics).
* Add `rv-helpers` folder with helper contracts for property tests.
* Add `run-kevm.sh` script for reproducing KEVM proofs.
* Add `PROOFS.md` with instructions for installing and running KEVM to reproduce the proofs.
* Add `wormhole-lemmas.k` file with helper lemmas used in the KEVM proofs.
* Edit `Makefile` to ignore the KEVM versions of the tests when running `forge test`.
=> ethereum: Add property tests and instructions for running them with KEVM

clients/js/README.md, clients/js/src/cmds/editVaa.ts
This PR changes the `worm edit-vaa` command so that you can tell it to look up the signatures on wormscan without specifying the complete URL.
Instead of doing:
`worm edit-vaa -n mainnet --vaa $VAA --wormscanurl https://api.wormscan.io/api/v1/observations/1/0000000000000000000000000000000000000000000000000000000000000004/651169458827220885`
you can just do:
`worm edit-vaa -n mainnet --vaa $VAA --wormscan`
and it will use the sequence number from the VAA bytes to generate the URL. The old command is still supported.
=> Client/js: Simplify edit-vaa command

solana/programs/core-bridge/src/error.rs, solana/programs/core-bridge/src/legacy/processor/verify_signatures.rs
all messages are checked to be the same, so we just store one of them
=> solana: make SigVerifyParameters canonical

solana/programs/core-bridge/src/error.rs, solana/programs/core-bridge/src/legacy/processor/verify_signatures.rs
This makes it easier to see which fields of a struct are used. Will follow up with the same refactoring in other places where appropriate
=> solana: pattern match instead of label

node/pkg/watchers/solana/client.go
The Solana rewrite going to testnet shows us that _at least_ 8 accounts will be usable.
=> Node/Watcher: Update solana min accounts check

sdk/js/src/cosmwasm/address.ts, sdk/js/src/utils/array.ts, sdk/js/src/utils/consts.ts
Use the new cosmos chain id range (`4000` onwards). Leave previous existing cosmos chains with their current id (e.g. `osmosis` with id `20`)
=> [sdk/js] Add cosmoshub and evmos chain ids

sdk/testnet_consts.go
This address is the encoded version of `wormhole1aaf9r6s7nxhysuegqrxv0wpm27ypyv4886medd3mrkrw6t4yfcnst3qpex`, which is defined in the testnet section of `sdk/js/src/utils/consts.ts`.
=> Node/SDK: Set testnet wormchain token bridge address

.github/workflows/build.yml, Dockerfile.proto, node/Dockerfile, scripts/Dockerfile.lint, scripts/dev-setup.sh
Please compile with golang >= 1.20.8.
=> upgrade to golang 1.20.8

algorand/runPythonUnitTests.sh
A recent change to the indexer branch name is breaking the Algorand build
Its accounted for here: https://github.com/algorand/sandbox/commit/783d25d37bb6b8e80df73fbad8c4ea5bd459caab#diff-596bbaeef3aec3ae956116372ea7d3862e78f4edb3c628d4c730f9d25507b815
but we've pinned sandbox repo to a much earlier version with a [TODO ](https://github.com/wormhole-foundation/wormhole/issues/3068) to improve
=> Algorand Tests: Specify Indexer branch

.github/DISCUSSION_TEMPLATE/gateway.yml
Not sure how to validate this yet
https://github.blog/2023-01-09-github-discussions-just-got-better-with-category-forms/
This should map 1:1 to categories, so also created a category `Gateway` here https://github.com/wormhole-foundation/wormhole/discussions/categories/gateway
We may want to rename to something more specific?
=> Discussion Template: Adding discussion template for Gateway/Cosmos onboarding

node/pkg/watchers/evm/watcher.go
Other cases set the variable to the scope outside the if/else cases so this _seems_ like a mistake.
Also moves a metric set call found during debug session
=> EVM Watcher: Fix shadowed variable in Optimism case

node/pkg/processor/observation.go
A recent change to `handleObservation` caused it to ignore additional signatures if the transaction is marked settled. However, the observation gets marked settled after only 30 seconds, and it sometimes (like in the case of consistency level 201, safe blocks) observations can take more than 30 seconds to arrive.
This PR changes it to ignore additional signatures once the transaction is marked submitted, meaning we have submitted / published the VAA.
=> Node: Observations are incorrectly ignored when marked settled

node/pkg/watchers/evm/watcher.go
Base safe support may not have been properly working due to not setting the `safeBlocksSupported` in the `Run` scope.
=> node/evm: fix Base safe block support

.github/workflows/build.yml
ubuntu-20.04 ships with GLIBC-2.31, but the latest foundry nightly (which these CI actions use) link against 2.33+ (perhaps foundry should statically link against something like musl...?)
So instead we run these two tests on ubuntu-latest
=> CI: run ethereum tests on ubuntu-latest

node/cmd/guardiand/adminclient.go, node/cmd/guardiand/keygen.go, node/cmd/guardiand/node.go, node/hack/accountant/send_obs.go, node/pkg/common/armoredKey.go, node/pkg/devnet/guardiankey.go
This PR restructures the code to generate, save and read guardian key files so that it can be shared with CCQ. Once this PR is merged, the code in the `ccq/integration` branch will be updated to use it, including changing the `ccq_server` to not use the guardian key label.
=> Node: Keygen changes

ethereum/README.md
This PR removes the batch VAA section from the ethereum README.md, since this feature is being deprecated.
Separately, we should start removing the associated contracts and the implementation from the node too.
=> ethereum: remove mention of batched vaas in README

aptos/scripts/deploy, aptos/scripts/named_addresses, aptos/scripts/upgrade, scripts/contract-upgrade-governance.sh, sdk/js/src/utils/consts.ts
This PR adds support for mainnet aptos upgrades in the aptos upgrade script and the governance proposal generator.
Also added the missing testnet NFT bridge address.
Changed the default behaviour of the governance proposal generator script to fail if the directory is dirty. This can be overridden with the `—force` flag.
=> aptos: tooling for mainnet upgrades

node/pkg/common/chainlock.go, node/pkg/db/accountant.go, node/pkg/db/accountant_test.go, node/pkg/db/governor.go, node/pkg/db/governor_test.go, node/pkg/governor/governor.go, node/pkg/processor/cleanup.go, node/pkg/processor/message.go, node/pkg/processor/processor.go, node/pkg/processor/vaa.go, node/pkg/watchers/algorand/watcher.go, node/pkg/watchers/aptos/watcher.go, node/pkg/watchers/cosmwasm/watcher.go, node/pkg/watchers/evm/watcher.go, node/pkg/watchers/ibc/watcher.go, node/pkg/watchers/mock/watcher.go, node/pkg/watchers/near/poll.go, node/pkg/watchers/near/tx_processing.go, node/pkg/watchers/near/watcher.go, node/pkg/watchers/near/watcher_test.go, node/pkg/watchers/solana/client.go, node/pkg/watchers/sui/watcher.go
This PR attempts to limit reobservation storms by not requesting reobservation on transactions that are the result of a reobservation request.
=> Node: Don't request reobservation on reobservations

clients/js/src/cmds/editVaa.ts, node/hack/release_verification/guardian_vaa_stats.go
Changed the files with hardcoded URLs found with: 
`grep -r 'wormscan' ./* --exclude-dir=node_modules --exclude-dir=build`
=> Replace wormscan with wormholescan in urls

devnet/query-server.yaml, node/cmd/ccq/http.go, node/cmd/ccq/query_server.go, node/cmd/ccq/utils.go, node/pkg/common/mode.go, node/pkg/common/mode_test.go
The `ccq_server` was recently updated to allow it to sign requests on behalf of API keys for which the feature is enabled. Unfortunately, that code hard coded the environment to devnet, so the requests are being signed using the wrong prefix for testnet. This PR fixes that. It also adds some more debug logging.
=> CCQ: Query server environment is hard coded to devnet

cosmwasm/contracts/global-accountant/src/contract.rs
The latest version of clippy warns about this. The change is semantics preserving.
=> cosmwasm/global-accountant: fix clippy warning

sdk/js/src/solana/utils/secp256k1.ts
In this case we've gotten away with it because the `messageDataLength` in the previous element is always 32 which is `0200` in LE that we overwrite the second byte with a `00` 
But might as well make it right
=> SDK: write to the correct index

node/pkg/p2p/cutover.go
This PR sets the time to cut over the gossip network on testnet from QUIC to QUIC-V1.
=> Node: Update QUIC cutover time for testnet

Makefile
This is required for building the guardiand binary.
To verify that it _doesn't_ build without this flag, run
```
CGO_ENABLED=0 make node
```
The above is needed in cases where `go env` is set up such that it supplies this flag by default, masking the issue.
=> Makefile: set CGO_ENABLED=1

ethereum/contracts/query/QueryResponse.sol, ethereum/forge-test/query/QueryResponse.t.sol
This PR adds support for `eth_call_by_timestamp` and `eth_call_with_finality` to the EVM parsing library.
=> CCQ/EVM: eth_call_by_timestamp and eth_call_with_finality support

ethereum/contracts/relayer/deliveryProvider/DeliveryProviderState.sol
This PR fixes an outdated storage slot comment.
=> ethereum/relayer: fix comment about storage slot derivation

node/cmd/guardiand/node.go, node/pkg/node/options.go, node/pkg/watchers/ibc/watcher.go, node/pkg/watchers/ibc/watcher_test.go
Currently the IBC watcher uses the `ibcWS` guardian config parameter to generate the URL used to read the block height and wormchain version. (This is necessary because the LCD may not be used to read `abci_info`.) This works in most cases (including for all mainnet guardians) but may not work in some situations in testnet.
This PR adds a new optional `ibcBlockHeightURL` config parameter. If it is not specified, the `ibcWS` is converted to be used for the http query (as it always has been). If `ibcBlockHeightURL` is specified, then it is used for the block height query.
Additionally, the existing conversion routine only handled URLs that start with "ws://", not "wss://". This PR fixes that.
=> NODE/IBC: Allow for a separate block height URL

node/pkg/watchers/evm/connectors/batch_poller.go, node/pkg/watchers/evm/connectors/common.go, node/pkg/watchers/evm/connectors/instant_finality.go, node/pkg/watchers/evm/connectors/poller.go, node/pkg/watchers/evm/connectors/polygon.go, node/pkg/watchers/evm/watcher.go
The CCQ timestamp to block number feature needs to have access to the timestamp of the latest blocks. This PR adds that for all the various block pollers.
=> Node/EVM: Add timestamp to block

node/pkg/watchers/evm/connectors/batch_poller.go, node/pkg/watchers/evm/connectors/batch_poller_test.go, node/pkg/watchers/evm/connectors/poller.go
The new batch poller is generating a lot of errors when running against certain public endpoints, due to load balancing. This PR suppresses those errors and makes the batch poller more robust.
=> Node/EVM: Suppress unnecessary polling errors

Tiltfile, devnet/query-server.yaml, node/cmd/ccq/http.go, node/cmd/ccq/metrics.go, node/cmd/ccq/p2p.go, node/cmd/ccq/query_server.go, node/cmd/ccq/status.go, node/cmd/ccq/utils.go, sdk/js-query/src/query/ethCall.test.ts, testing/querysdk.sh
This server adds Prometheus metrics to the CCQ query_server. It adds a new `statusAddr` config parameter which specifies the port on which the query_server should publish metrics and listen for health check requests. This defaults to `localhost:6068`.
In tilt, the following are useful endpoints:
- http://localhost:6068/metrics
- http://localhost:6068/health
=> CCQ: Query server metrics

node/pkg/watchers/solana/client.go
This PR adds a safety check to ensure that, on Solana, message publication account fields which were already zeroed out, are definitely zeroed out. This becomes important in the upcoming rewrite when the account can be written to across multiple instructions and one of these fields contains the `status`, which is set to zero when the account can no longer be written to.
=> node/watchers/solana: additional safety check

node/pkg/adminrpc/adminserver_test.go, node/pkg/query/query.go, node/pkg/query/request.go, node/pkg/watchers/evm/blocks_by_timestamp.go, node/pkg/watchers/evm/blocks_by_timestamp_test.go, node/pkg/watchers/evm/ccq.go, node/pkg/watchers/evm/connectors/batch_poller.go, node/pkg/watchers/evm/connectors/batch_poller_test.go, node/pkg/watchers/evm/connectors/celo.go, node/pkg/watchers/evm/connectors/common.go, node/pkg/watchers/evm/connectors/ethereum.go, node/pkg/watchers/evm/connectors/poller_test.go, node/pkg/watchers/evm/watcher.go, sdk/js-query/src/query/ethCall.test.ts
This PR is the first phase of caching the timestamp to block ID mapping in the EVM watcher for use by the CCQ `eth_call_by_timestamp` request.
This first phase only adds latest blocks to the cache, without any back filling of the cache. It also only supports three chains, Ethereum, Base and Optimism.
The next phase after this PR will add the ability to back fill the cache by doing batch queries to read old blocks.
Future phases will add support for more EVM chains, which should really only be a testing effort.
=> CCQ/Node/EVM: Cache timestamps

node/cmd/ccq/http.go, node/cmd/ccq/p2p.go
The query server currently does very little logging, except for at the debug level. Although this makes sense once it is heavily used in production, it is making it very hard to monitor it during deployment. This PR adds more info and error level logging for now. Later on, we may change some or all of these messages back to debug.
=> CCQ: Query server logging

node/pkg/watchers/solana/client.go
As of 2023-11-09, Pythnet has a bug which is not zeroing out these fields appropriately. This carve out should be removed after a fix is deployed.
This bug was identified as this security check was triggered in testnet.
=> node/watchers/solana: pythnet safety carve out

node/pkg/query/metrics.go, node/pkg/query/query.go, node/pkg/watchers/evm/ccq.go
This PR adds CCQ related metrics to the guardian.
=> CCQ/Node: Metrics

node/cmd/ccq/query_server.go, node/hack/query/send_req.go, node/hack/query/test/query_test.go, node/pkg/p2p/ccq_p2p.go
This PR appends "/ccq" to the end of the P2P network ID used for CCQ to separate it out from the main gossip network.
=> CCQ: Change network ID

ethereum/contracts/query/QueryDemo.sol, ethereum/contracts/query/QueryResponse.sol, ethereum/forge-test/query/QueryResponse.t.sol
Redoing this PR with my new permissions. Reverting back to public visibility as any state changes are prevented by the view anyway. I was being overly cautious. Provided the integrator is in control of the "wormhole" address input (like in the demo contract) to those parsing functions so that an invalid CCQ isn't incorrectly accepted then we're good. This needs to be well documented so that integrators can't get rekt (happy to write if someone lets me know where).
Added fuzz tests to parseAndVerifyQueryResponse and verifyQueryResponseSignatures as I think these are the most important entrypoints. This required a small refactor to split the hex string into its constituent parts so we can construct the payloads on the fly.
Assuming you could get the guardians to sign the CCQ, there was a …
=> CCQ: QueryResponse fuzzing + extra safety checks

node/cmd/ccq/query_server.go
The last PR changed the network ID for CCQ to add "/ccq" on the end. This is working, but as a side affect, the query server is now using that as the network name in Loki logging, which is confusing. This PR reverts that so the logging will be done using the base network ID.
=> CCQ: Server should use base networkID  for logging

node/pkg/p2p/ccq_p2p.go, node/pkg/p2p/p2p.go
I'm not sure if it matters (local testing didn't seem impacted) if we listen to requests from other guardians. Seems rude to let them retry subscriptions for... seemingly forever every second.
=> node/ccq: allow guardian peers

node/pkg/adminrpc/adminserver.go, node/pkg/watchers/cosmwasm/watcher.go
This PR adds Terra2 to the list of cosmwasm chains that no longer base64 encode message attributes.
Also, sneaks in some text changes.
=> node/pkg/watchers: cw decoding more robust

clients/js/src/evm.ts
Previously this function would not actually catch an exception and cause the program to crash. This commit fixes that.
=> clients/js: Fix `maybeUnsupported` function

node/pkg/watchers/evm/ccq.go, node/pkg/watchers/evm/watcher.go
This looks like a fairly big PR, but it is really quite simple. A previous PR added a separate `ccqLogger` to the watcher object to avoid having to constantly add the "ccqevm" component. This PR just changes the code to use that every where, rather passing the logger into all the CCQ functions.
=> CCQ/Node/EVM: Logger cleanup

ethereum/forge-test/Governance.t.sol
Turns out that the recipient address for the failure cases was the same as the WH proxy, so I've added that as another address to avoid
=> ethereum: Fix flaky tests

node/pkg/governor/governor_prices.go
Probably overkill but my thinking was that since price queries are every 15 minutes, someone could predict the cache key if just the Unix timestamp was used; hence concatenating the unix timestamp and a random number.
Tested cache hits/misses with Postman
=> node: Add cache buster for CoinGecko price queries

ethereum/forge-test/Governance.t.sol
After being baffled by the fact that all the storage slot addresses were being calculated correctly, it turns out that the issue with this test was that not enough slots were being discarded.
The test has been updated to align with other similar tests like `testSubmitContractUpgrade`: https://github.com/wormhole-foundation/wormhole/blob/1152b5bd6449f38e0c96d13345caf51726ba4df9/ethereum/forge-test/Governance.t.sol#L67-L80.
=> ethereum: Fix flaky governance replay attack test

node/pkg/p2p/cutover.go
This PR schedules the cut over from QUIC to QUIC-v1 for January 16th, 2024 at 9am CST.
Before that time:
- This PR must be deployed in a release.
- All guardians must upgrade to a release that includes it.
- All spies, flies, CCQ proxies and any other applications that listen to gossip must also upgrade.
- All applications that listen to gossip must be configured to automatically restart on a panic.
Note that applications *should not* modify their bootstrap parameters. The cut over feature takes care of translating the old parameters to the new format at the appropriate time.
This cut over took place smoothly in testnet on November 7th, 2023.
=> QUIC/Node: Set mainnet cut over time

node/pkg/p2p/ccq_p2p.go, node/pkg/query/query.go, node/pkg/query/request.go, node/pkg/query/response.go, node/pkg/watchers/evm/ccq.go
This code reduces the amount of code that is duplicated between the `eth_call`, `eth_call_by_timestamp` and `eth_call_with_finality`.
This PR also fixes #3539.
=> CCQ/Node/EVM: Refactor

docs/operations.md
Staking Fund recently became a bootstrap node for CCQ. This PR adds them to the documentation.
=> Node/Doc: Add Staking Fund to CCQ bootstrap

ethereum/ts-scripts/relayer/shell/deployInContainer.sh
The latest version of `tsx` throws a nasty error with the version of node used in the eth tests container.
=> tilt: eth relayer pin tsx

sdk/js/CHANGELOG.md, sdk/js/src/solana/tokenBridge/accounts/wrapped.ts
The `last_updated_sequence` variable was added to the new `WrappedAsset` struct which is currently deployed in devnet. When I created a new wrapped token or updated an existing one the data length of the wrapped asset changed from 35 to 43 bytes. This PR supports deserializing both the legacy (35 bytes) and new (43 bytes) wrapped asset data. https://github.com/wormhole-foundation/wormhole/blob/cf74cd22ba74f019861066e734ecb058d8d3fdfe/solana/programs/token-bridge/src/legacy/state/wrapped_asset.rs#L48
=> sdk/js: Refactor WrappedMeta class constructor to include lastUpdatedSequence

node/pkg/accountant/accountant.go
A change was made a while ago to drop these bad pending transfers on start up, which fixed a reobservation storm. However, the transfers were left in the DB, so we get an error saying they were dropped on every restart. This PR removes them from the DB so that we can be done with them for good.
=> Node/GACCT: Drop bogus pending transfers from db

node/pkg/watchers/evm/watcher.go
This PR addresses issue #2905, where reading the block time on a new EVM transaction can fail, possibly due to a load balancer issue. This failure kills the watcher, which has always been a problem, but will be worse now that the watcher is maintaining the timestamp to block number cache used for CCQ, so that history will be lost on a restart.
This PR adds a limited retry (every five seconds for up to three retries) before giving up on the transaction.
=> Node/EVM: Retry block time read

node/pkg/governor/mainnet_chains.go
Governance discussion here: https://github.com/wormhole-foundation/wormhole/discussions/3580
This PR lowers the Aptos governor limit from $5M to $1M.
=> governor: lower aptos governor limit to 1M

cosmwasm/deployment/terra2/Makefile, cosmwasm/deployment/terra2/devnet/docker-compose.yml
The terra-2 test started failing, likely because it was pulling the latest LocalTerra and something changed. This now uses a defined `docker-compose.yaml` and pinned version. Ideally this could share an image with tilt, but that didn't work immediately with the current devnet config.
=> ci: fix terra2 test

node/cmd/ccq/http.go, node/cmd/ccq/metrics.go, node/cmd/ccq/permissions.go, node/cmd/ccq/query_server.go, node/cmd/ccq/utils.go, node/go.mod, node/go.sum
This PR adds a file watcher to the CCQ server to automatically pick up updates to the permissions file.
Note that all of the code removed from `utils.go` was moved unchanged to `permissions.go`.
=> Node/CCQ/Server: Add permissions file watcher

devnet/query-server.yaml, node/cmd/ccq/p2p.go, node/cmd/ccq/pending_request.go, node/cmd/ccq/query_server.go, node/cmd/ccq/status.go
This PR changes the proxy server to handle restarts more cleanly, hopefully without dropping query requests.
It adds two new config parameters (with what should be reasonable default values): `shutdownDelay1` and `shutdownDelay2`. When a sigterm is received, it will do the following:
- Set a flag to stop responding to health checks
- Sleep for `shutdownDelay1` seconds to allow the load balancer to detect that the server is down and stop routing requests to it.
- Sleep for up to `shutdownDelay2` seconds, but checking every second to see if there are no more pending requests.
- When there are no more pending requests (or after `shutdownDelay2` seconds), the server exits.
The default values for the two config parameters are based on the default health check parameter values. We may want to …
=> Node/CCQ/Server: Clean restart

ethereum/contracts/query/QueryDemo.sol, ethereum/contracts/query/QueryResponse.sol, ethereum/forge-test/query/QueryResponse.t.sol
As discussed I've added some high level helpers that should hopefully make validating a parsed response easier for integrators rather than having to write validation logic from scratch every time.
I've also slightly refactored the passing of the wormhole address to avoid the potential for an integrator accidentally allowing the caller to specify this value.
=> CCQ: High level validation helpers + slight refactor

Dockerfile.cli, Dockerfile.const, Dockerfile.proto, Tiltfile, algorand/Dockerfile, algorand/sandbox-algorand/images/algod/Dockerfile, algorand/sandbox-algorand/images/indexer/Dockerfile, aptos/Dockerfile, cosmwasm/Dockerfile, cosmwasm/Dockerfile.deploy, ethereum/Dockerfile, node/Dockerfile, relayer/generic_relayer/relayer-engine-v2/Dockerfile, solana/Dockerfile, solana/Dockerfile.wasm, sui/Dockerfile, terra/Dockerfile, wormchain/Dockerfile.deploy
I had previously added this code to support contributors behind corporate firewalls which required custom root certificate authorities. I don't think this is needed anymore and is simply spamming logs.
=> tilt: remove additional root CA support

node/pkg/watchers/evm/config.go, node/pkg/watchers/evm/watcher.go
This PR removes some dead code from the EVM watcher in an attempt to make the code more readable.
Since the watcher has been upgraded to use `finalized` for all chains, the `waitForConfirmations` config parameter was always false, so I've removed it. This meant that the `expectedConfirmations` variable was always zero, so I also removed that.
Additionally, the `maxWaitConfirmations` config parameter is always 60, so I made it a constant.
=> Node/EVM: Minor code cleanup

node/hack/governor/.gitignore, node/hack/governor/src/index.ts, node/pkg/governor/mainnet_tokens_test.go
This PR is part 1 of improving the governor token list update process to increase automation and visibility.
Specifically, this PR concerns the changes to the existing update script that find any new token additions or token removals, and any significant decreases in token price. The generated tokens list that is generated by this script is unchanged. However the script now also outputs a `changes.txt` file with a summary. This is the file that is used in the GitHub PR body.
See https://github.com/wormhole-foundation/wormhole/pull/3587 for an example of what the PR body will look like. If there's anything about the body you'd like to change then please suggest on this PR.
This PR is accompanied by part 2 (https://github.com/djb15/wormhole/pull/4) which runs the automation. This is …
=> node: Updated governor token list update script

node/pkg/watchers/evm/connectors/celo.go
When the `Time` attributed was added to the `NewBlock` struct for the timestamp cache feature, Celo was missed. This PR updates the Celo block poller to populate the timestamp.
=> Node/EVM: Celo not setting timestamp in blocks

docs/operations.md
=> docs: remove certus one references from operations

clients/js/README.md, clients/js/package-lock.json, clients/js/package.json, clients/js/src/chains/generic/getOriginalAsset.ts, clients/js/src/chains/generic/getWrappedAssetAddress.ts, clients/js/src/chains/generic/provider.ts, clients/js/src/cmds/submit.ts, clients/js/src/cmds/transfer.ts, clients/js/src/consts/networks.ts
This PR adds testnet support to the `worm` client for the following chains:
1. Scroll
2. Mantle
3. Arbitrum Sepolia
4. Base Sepolia
5. Optimism Sepolia
=> Client/JS: Add new chains

node/cmd/ccq/metrics.go, node/cmd/ccq/p2p.go, node/cmd/ccq/query_server.go, node/pkg/query/query.go, node/pkg/watchers/evm/ccq.go
In testnet, the CCQ proxy server is not detecting when a guardian restarts. As a work around, this PR adds the ability for the server to attempt to automatically reconnect when it detects that a bootstrap peer has gone away.
This feature is only intended to be used in testnet, and is controlled by a config parameter, `monitorPeers`.
This PR also changes some CCQ log messages from error to debug so that routine conditions (like block not available yet) don't flood the logs.
=> Node/CCQ: Server auto reconnect

node/hack/governor/src/index.ts
This fixes the script if there is a new token on a chain that doesn't already have at least 1 token on the list
=> node: Fix governor token list script for new chains

clients/js/README.md, clients/js/package-lock.json, clients/js/package.json, clients/js/src/chains/generic/getOriginalAsset.ts, clients/js/src/chains/generic/getWrappedAssetAddress.ts, clients/js/src/chains/generic/provider.ts, clients/js/src/consts/networks.ts
This PR updates the `worm` command to support the Holesky testnet.
=> Client/JS: Add Holesky support

node/pkg/query/request.go, node/pkg/query/request_test.go, node/pkg/query/response.go, node/pkg/query/response_test.go
The CCQ `Unmarshal` methods should fail if someone slips extra bytes at the end of the message. Not sure if this is really an exploitable issue, but it seems like a reasonable safety.
=> Node/CCQ: Unmarshal should check for extra bytes

node/pkg/p2p/cutover.go, node/pkg/p2p/cutover_test.go, node/pkg/p2p/p2p.go, node/pkg/p2p/watermark_test.go
Now that mainnet has officially cut over to quic-v1, we no longer need to check the cutover time on startup. Instead we will just always convert the bootstrap peers and listen addresses to use `/quic-v1/`.
We want to keep doing that so that the guardians and other users don't have to change their configs.
Question: Should I update `operations.md` to reference `/quic-v1`, or leave it as is?
=> Node: Always cut over to quic-v1

node/cmd/ccq/utils.go, node/pkg/query/request.go, node/pkg/query/response.go, sdk/js-query/src/mock/index.ts, sdk/js-query/src/mock/mock.test.ts, whitepapers/0013_ccq.md
The Mock for the Solana `sol_account` query does not support the `min_context_slot` parameter. This PR adds that support.
Additionally, this PR includes a few small tweaks that came out of PR #3637.
=> CCQ: Solana mock should support min_context_slot

sdk/js/src/relayer/consts.ts, sdk/js/src/relayer/relayer/helpers.ts
Adds *sepolia chains to SDK and update the chain name mapping
https://developers.circle.com/stablecoins/docs/migrate-from-goerli-to-sepolia-testnet
=> prepare for sepolia chains for cctp

sdk/rust/Cargo.toml, sdk/rust/core/Cargo.toml
This solves https://github.com/wormhole-foundation/wormhole/issues/2972
Currently any rust project that depends on wormhole-sdk needs to copy into their `Cargo.toml`: 
```
[patch.crates-io]
serde_wormhole = { path = "serde_wormhole" }
```
which is really annoying for everyone using it.
Specifying `serde_wormhole = { path = "../serde_wormhole", version = "0.1.0" }` is great because: 
- when using `wormhole-sdk` locally `serde_wormhole` will get resolved properly with the `path = "../serde_wormhole"`
- if `wormhole-sdk` gets published and `serde_wormhole` gets published as well, `serde_wormhole` will get resolved properly with the `version = "0.1.0"`
=> [rust-sdk] Fix wormhole_serde patch

node/pkg/query/query.go, node/pkg/query/query_test.go, node/pkg/watchers/solana/ccq.go, node/pkg/watchers/solana/ccq_test.go, sdk/js-query/src/query/solana.test.ts
This PR adds a fast retry mechanism to the Solana query handler when the RPC call fails due to the `MinContextSlot` not being met. In that case, we retry every 200 milliseconds, attempting to hit the desired slot.
This PR also changes the query audit interval to once per second from every ten seconds so that we will be more likely to retry a query every ten seconds.
=> Node/CCQ: Solana min context slot support

node/pkg/query/query.go, node/pkg/query/request.go, node/pkg/watchers/solana/ccq.go, node/pkg/watchers/solana/ccq_test.go
Some Solana nodes do not return the current slot in the min context slot error. This PR changes the code to use the latest slot seen by the watcher in that case.
=> Node/CCQ: Solana min context slot fix

ethereum/contracts/bridge/BridgeImplementation.sol
the canonical WETH on optimism:
https://help.optimism.io/hc/en-us/articles/4417948883611-What-is-ETH-WETH-How-do-they-interact
https://optimistic.etherscan.io/address/0x4200000000000000000000000000000000000006#code
https://github.com/ethereum-optimism/optimism/blob/d48b45954c381f75a13e61312da68d84e9b41418/op-bindings/predeploys/addresses.go#L11
=> evm: sets optimism WETH in token bridge initializer

node/cmd/ccq/http.go, node/cmd/ccq/p2p.go
The existing CCQ server response logging was not working for unsigned requests. This PR fixes that. Additionally, it logs the request along with the response.
=> Node/CCQServer: Enhance response logging

.github/workflows/build.yml, ethereum/Makefile
Checks that we don't inadvertently build contracts with compiler versions that support PUSH0 opcodes whilst support is spotty.
It's brittle but it works whilst this is a transient state of play.
=> ethereum: PUSH0 test

terra/verify
This allows running the `verify` script on e.g. some mac installations that come bundled with bash v3.
=> terra: uses `tr` instead of bash 4 feature in `verify` script

clients/js/src/chains/sei/submit.ts, clients/js/src/cmds/submit.ts, clients/js/src/consts/networks.ts
This adds the following for VAA submit on Sei:
- Gas estimation.
- Process/accept `rpc` option.
- Defines `SEI_KEY` as the environment variable for mainnet Sei keys.
=> Client/js: adds key and rpc support for submit VAA on Sei mainnet.

node/cmd/ccq/http.go, node/cmd/ccq/metrics.go, node/cmd/ccq/p2p.go, node/cmd/ccq/pending_request.go
This PR changes the CCQ proxy server so that it will give up on a query when the number of matching responses plus the potential number of outstanding responses would not reach quorum. When that happens, it returns a "quorum not met" error to the client.
=> Node/CCQServer: Quorum not met

.github/workflows/build.yml
If a forge project has already been built it skips compilation, even if you specify extra flags. So the extra opcode output we needed wasn't being generated and the test would always pass. This reorders the tests to make sure we get the opcodes in our build output.
=> ci: Fix ordering of forge builds

sdk/js/src/token_bridge/injective.ts
The injective SDK does not base64 encode Uint8Arrays, passing a payload here will result in a transaction with nonsensical data in the transaction.
Any other places we have Uint8Array as input are treated with `fromUint8Array` or `Buffer.from().toString('base64')`
ex
https://github.com/wormhole-foundation/wormhole/blob/5288d51e152c7a82978ae9cdcfde740c904da5b9/sdk/js/src/token_bridge/injective.ts#L82
------
This code is going on [1.5 years old ](https://github.com/wormhole-foundation/wormhole/pull/1396) but somehow was never run or reported to us
I could not find any existing tests that exercise the payload argument but willing to add if this is a scary change
=> SDK: base64 encode payload being sent to injective token bridge

node/pkg/db/governor.go, node/pkg/db/governor_test.go, node/pkg/governor/governor.go, node/pkg/governor/governor_test.go
This PR adds the target chain and address to the governor transfers stored in the DB. It also handles reloading transfers that do not have those fields and migrating them to the new format.
=> Node/Gov: Add target to db

node/pkg/accountant/ntt_config.go
This PR sets the NTT emitters for testnet as follows:
```
1: 7e6436b671cce379a1fa9833783e28b36d39a00e2cdc6bfeab5d2d836eb61c7f
10002: 0000000000000000000000001fdc902e30b188fd2ba976b421cb179943f57896
10003: 0000000000000000000000000e24d17d7467467b39bf64a9dff88776bd6c74d7
10004: 0000000000000000000000001e072169541f1171e427aa44b5fd8924bee71b0e
10005: 00000000000000000000000041265eb2863bf0238081f6aeefef73549c82c3dd
```
=> Node/NTT/Acct: Set testnet emitters

node/cmd/ccq/http.go, node/cmd/ccq/metrics.go, node/cmd/ccq/pending_request.go, node/cmd/ccq/query_server.go, node/cmd/ccq/utils.go
This PR adds a metric to the proxy server to track the maximum number of concurrent requests by chain. This will be useful for scaling the amount of parallelism in the guardian watchers.
=> Node/CCQ: Track concurrent queries

sdk/js/src/solana/sendAndConfirmPostVaa.ts
This pull request addresses the deprecation of the `sendAndConfirmTransactionsWithRetry` function in the `postVaaWithRetry` method. This function was replaced with the new `signSendAndConfirmTransaction` function as per the recent updates in the library. The retries are done with the `ConfirmOption` and handled internally in the Solana library.
The main changes involve replacing the deprecated `sendAndConfirmTransactionsWithRetry` function with the `signSendAndConfirmTransaction` function in the `postVaaWithRetry` method. The `signSendAndConfirmTransaction` function handles each transaction individually, so the code has been adjusted to process each transaction in a loop.
This change was required because `sendAndConfirmTransactionsWithRetry` was marked as deprecated in the library, and …
=> sdk/js: Replace deprecated function with signSendAndConfirmTransaction

clients/js/Makefile, clients/js/jest.config.json, clients/js/package-lock.json, clients/js/package.json, clients/js/src/consts/networks.ts, clients/js/src/near.test.ts, clients/js/src/near.ts
The submit VAA logic for Near in `worm` assumes that the deployer account id is a specific one. This makes it difficult to switch to another key when submitting VAAs to Near.
This adds an environment variable to set the implicit account id to register with the private key but I'm not sure if this is the way we want to go. There might be better alternatives; I haven't looked at the Near SDK that much.
=> clients/js: fixes hardcoded Near deployer implicit account id.

devnet/query-server.yaml, devnet/spy.yaml, docs/operations.md, node/cmd/ccq/query_server.go, node/cmd/guardiand/node.go, node/cmd/spy/spy.go, node/hack/query/ccqlistener/ccqlistener.go, node/pkg/p2p/network_consts.go, node/pkg/p2p/network_consts_test.go
This PR hard codes the bootstrap peers and network ID for the guardian, spy and query proxy server, based on the environment (mainnet or testnet). It allows them to be overridden using the existing parameters, but that should be discouraged.
For devnet / tilt, the existing parameters should still be used because the bootstrap peer may not be deterministic.
The following config parameters should be removed for guardiand and the query proxy server:
- --network
- --bootstrap
- --ccqP2pBootstrap
The following config changes should be made for the spy:
- Add --env with a value of `mainnet` or `testnet`.
- Remove --network
- Remove --bootstrap
=> Node/P2P: Add default bootstrap peers

node/cmd/ccq/pending_request.go, node/pkg/node/node.go, node/pkg/node/options.go, node/pkg/query/query.go, node/pkg/watchers/evm/ccq_backfill.go, node/pkg/watchers/solana/ccq.go
This PR addresses a few small issues seen during query load testing:
- Internal message queues were filling up, causing unnecessary retries.
- The proxy metric to track current level of concurrent queries was not properly updating when a query completed.
- A few watcher logging improvements.
=> Node/CCQ: Load testing tweaks

node/cmd/guardiand/node.go, node/pkg/node/node_test.go, node/pkg/node/options.go, node/pkg/p2p/ccq_p2p.go, node/pkg/p2p/p2p.go
When behind a private network such as in the case of a guardian running in Kubernetes, or behind a NAT, the default p2p setup doesn't work. It looks at all addresses that it is listening on and advertises them on p2p as the addresses for contacting the guardian. This patch is the first step towards allowing specifying a custom ip address to be advertised on the gossip p2p network.
For example, a guardian running inside kubernetes can post a reserved ip address of the incoming ingress/load balancer that sends the traffic in to their guardian.
To use this feature, just add `--gossipAdvertiseAddress $externally_reachable_ip_address` to the guardiand flags.
=> node: support overriding the p2p advertised ip

node/pkg/governor/governor_prices.go
We're consistently hitting the CoinGecko API rate limit now on the free plan which means we're not always updating prices and the query check fails when trying to update the governor token list. Rather than paying for the premium API plans we could instead just throttle our requests, since these price updates are not time critical.
Someone better then me at Go can tell me if this is rubbish!
=> node: Throttle CoinGecko queries

node/pkg/p2p/p2p.go, node/pkg/processor/cleanup.go, node/pkg/processor/message.go, node/pkg/processor/observation.go, node/pkg/processor/processor.go, node/pkg/processor/vaa.go
This PR does two things.
First, it adds the standard VAA / Message ID (emitterChain/emitterAddress/seqNo) to messages in the processor to make it easier to follow a message from end-to-end in the logs.
Second, it adds a log level check around a lot of the debug messages so that we don't waste time formatting complex log messages that get dropped anyway.
=> Node: Logging cleanup

node/cmd/guardiand/node.go, node/pkg/watchers/evm/config.go, node/pkg/watchers/evm/connectors/linea_poller.go, node/pkg/watchers/evm/connectors/lineaabi/LineaRollup.go, node/pkg/watchers/evm/watcher.go
This PR modifies the watcher for Linea to track the publication of finalized blocks from the roll up contract on Ethereum.
There are still questions about whether or not this implementation is adequate, but it is at least a step in the right direction.
This PR also updates the `getFinality` function in the watcher to make the finality assumptions of every EVM chain explicit.
Note to @panoel : Don't be frightened by the size of this PR. Most of it is in the generated ABI file.
=> Node/EVM: Linea poller

node/go.mod, node/go.sum, wormchain/go.mod, wormchain/go.sum
Newer versions of Ledger (or firmware?) requires more recent dependencies of the following:
```
github.com/cosmos/ledger-cosmos-go
github.com/zondax/ledger-go
github.com/zondax/hid
```
If they are not updated the results are failed transactions:
```
wormchaind tx bank send account1 account2 1utest --from account1
Default sign-mode 'direct' not supported by Ledger, using sign-mode 'amino-json'.
{"body":{"messages":[{"@type":"/cosmos.bank.v1beta1.MsgSend","from_address":"account1","to_address":"account2","amount":[{"denom":"utest","amount":"1"}]}],"memo":"","timeout_height":"0","extension_options":[],"non_critical_extension_options":[]},"auth_info":{"signer_infos":[],"fee":{"amount":[],"gas_limit":"200000","payer":"","granter":""}},"signatures":[]}
confirm transaction before signing and …
```
=> Fixes transactions when using a Ledger

node/cmd/guardiand/admintemplate.go, node/pkg/adminrpc/adminserver.go, node/pkg/adminrpc/adminserver_test.go, node/pkg/adminrpc/prototext_test.go, sdk/vaa/payloads.go, sdk/vaa/payloads_test.go, sdk/vaa/types_test.go, wormchain/x/wormhole/keeper/msg_server_wasmd_test.go
This PR fixes https://github.com/wormhole-foundation/wormhole/issues/3897. It removes the `panic` calls from the code that handles injected governance commands.
This PR also adds a bunch of tests for the governance commands.
Created issue https://github.com/wormhole-foundation/wormhole/issues/3902 to address adding a missing admin template command.
=> Node: Adminserver commands should not panic

aptos/Docker.md, aptos/Dockerfile, aptos/Dockerfile.base, aptos/coin/Move.toml, aptos/deployer/Move.toml, aptos/nft_bridge/Move.toml, aptos/start_node.sh, aptos/token_bridge/Move.toml, aptos/wormhole/Move.toml
This bumps the toolchain and libs for the aptos contracts to 3.1.0 after it was raised that Pyth was behind the current aptos deployment, which will allow us to update our wormhole dependent contracts as well. This PR is modeled on [the last change that previously bumped to 2.0.3](https://github.com/wormhole-foundation/wormhole/commit/4a4873c9a3a1110dfb13a44dec51445dfd5be86d), the latest CLI rev can be found [here](https://github.com/aptos-labs/aptos-core/commit/6f83bc6d02207298b2dee91133d75538789bf582).
The PR is in draft state because `aptos/Dockerfile` requires a docker hash that I am unable to push myself so assuming this PR looks OK, and someone with permission can do that push, I can fix the PR as well and mark ready.
=> aptos: upgrade to 3.1.0 (toolchain and stdlib)

cspell-custom-words.txt, docs/operations.md
This is a set of changes I've been working on as I saw RockawayX folks ask questions when they were working on setting up a new guardian node.
=> Update operations docs

cosmwasm/contracts/ibc-translator/src/reply.rs, cosmwasm/contracts/ibc-translator/tests/test_setup/mod.rs, cosmwasm/packages/cw_transcode/src/ser.rs, sdk/rust/serde_wormhole/src/ser.rs
The 1.78 version of the rust toolchain has been released on the stable channel: https://github.com/rust-lang/rust-clippy/blob/master/CHANGELOG.md#rust-178
It introduces a number of new clippy lints. The relevant ones:
- https://rust-lang.github.io/rust-clippy/master/index.html#/assigning_clones
- https://rust-lang.github.io/rust-clippy/master/index.html#/multiple_bound_locations
- https://rust-lang.github.io/rust-clippy/master/index.html#/new_without_default
This commit fixes these lints.
=> sdk,cosmwasm: fix new clippy 1.78.0 lints

docs/query_proxy.md, node/cmd/ccq/p2p.go, node/cmd/ccq/query_server.go
This PR adds support for the `--gossipAdvertiseAddress` option to the CCQ proxy server, like already exists for the guardian.
=> Node/CCQ: Add gossipAdvertiseAddress option to proxy server

node/cmd/guardiand/node.go, node/pkg/devnet/hostname.go, node/pkg/devnet/hostname_test.go
The guardian in Tilt currently expects the first guardian name as listed in the bootstrap peers to be "guardian-0.guardian" so for the other guardians, waits until this host is visible before finishing initialization. In load testing, we have to use a different format host name. This PR extracts the host name from the first entry in the bootstrap peers. 
Note that PR only effects devnet, not testnet or mainnet.
=> Node/Devnet: Extract first guardian name from bootstrap peers

.github/workflows/build.yml
Solana binary releases are pulled from their github regularly, which breaks any process that needs to download a specific binary (e.g. CI). Instead of relying on github caching, we use the prebuilt docker image that's also used in tilt, which has the appropriate solana version built in.
=> CI: run solana action in prebuilt docker image

node/pkg/governor/manual_tokens.go
* Add Mantle to the `mainnet_chains.go` file using the default, minimum limits
* Add manual tokens. Data sourced from: https://www.coingecko.com/en/categories/mantle-ecosystem. I wasn't able to find other token information from e.g. https://explorer.mantle.xyz/ but if anyone knows of another reputable data source that shows other tokens we should add, let me know.
Previous related PRs:
* https://github.com/wormhole-foundation/wormhole/pull/3908
* https://github.com/wormhole-foundation/wormhole/pull/3926
Opening in draft until I can run `check_query.go`. Currently I'm rate-limited
=> node: add governor support for Mantle

wormchain/syncing.md
=> Update sync instructions for `v2.18.1.1` and `v2.24.2-wormchaind` upgrades.

node/hack/query/utils/fetchCurrentGuardianSet.go, node/pkg/node/node_test.go, node/pkg/p2p/p2p_test.go, node/pkg/watchers/evm/ccq_backfill.go, node/pkg/watchers/evm/connectors/batch_poller_test.go, node/pkg/watchers/evm/connectors/celo.go, node/pkg/watchers/evm/connectors/ethereum.go, node/pkg/watchers/evm/connectors/finalizer_poller_test.go
Some Go packages are imported more than once. Clean up a bit.
=> node: clean up duplicate imports

scripts/register-chain-governance.sh
This fixes the governance message document template when using multi mode.
When generating more than one governance message you could observe this being generated as the shell command to generate the prototxt:
```
cat << EOF > governance-206690B
259B804.prototxt
current_set_index:  4
[...]
```
Which breaks the format of the governance message.
=> script: uses only first digest as identifier for governance prototxt

node/pkg/watchers/cosmwasm/watcher.go
As of Terra Classic v3.0.1, attributes are not longer base64 encoded.
=> watcher: terra stopped b64 encoding

node/pkg/common/guardianset.go, node/pkg/common/guardianset_test.go, node/pkg/node/node_test.go, node/pkg/p2p/p2p.go, node/pkg/processor/broadcast.go, node/pkg/processor/cleanup.go, node/pkg/processor/observation.go, node/pkg/processor/processor.go, node/pkg/watchers/evm/watcher.go
This PR does a few things to help with guardian performance.
First, it adds some metrics to the processor to better track the flow of observations.
Secondly, it enhances the `common.GuardianSet` object to cache the quorum value once so that we do not have to repeatedly calculate quorum while processing observations. It also adds a map of guardian address to guardian index to speed up the look up of guardian index.
Finally, it modifies `handleObservation` to bail out early when we have already submitted the VAA.
=> Node metric and performance tweaks

node/hack/governor/src/index.ts
When trying to update the governor token list, the script was failing on this check:
```
// Sanity check to make sure the script is doing what we think it is
if (existingTokenKeys.length + addedTokens.length - removedTokens.length != newTokensCount) {
console.error(`Num existing tokens (${existingTokenKeys.length}) + Added tokens (${addedTokens.length}) - Removed tokens (${removedTokens.length}) != Num new tokens (${newTokensCount})`);
process.exit(1);
}
```
It turned out that a token was being classified as "removed" because its symbol had changed. We should allow tokens to change their symbol (like we do on the new token side) so this PR updates the script to only use the chain + address key for removed token lookups; that's a unique identifier after all.
Even if the token symbol …
=> node: Allow tokens to change their symbol in generator script

node/pkg/p2p/network_consts.go
node: update xlabs testnet guardian endpoints
update xlabs testnet guardian endpoints due to a migration.
The old domain names (stable.io) will be still up till P2P updates their testnet guardian to use this new update.
Tested TestnetBootstrapPeers endpoints using Wormhole Spy service.
=> node: update xlabs testnet guardian endpoints

node/cmd/spy/spy.go, node/pkg/accountant/submit_obs.go, node/pkg/common/channel_utils.go, node/pkg/common/channel_utils_test.go, node/pkg/common/guardianset.go, node/pkg/common/guardianset_test.go, node/pkg/p2p/p2p.go, node/pkg/processor/broadcast.go, node/pkg/processor/cleanup.go, node/pkg/processor/observation.go, node/pkg/processor/processor.go
This PR adds several minor tweaks that I came across while investigating the batching of observations:
- Make it so the spy does not have to subscribe for observations, just to drop them.
- Don't format the guardian address each time we publish an observation.
- Move a template function from the accountant package to common so it can be shared.
- Make the `Quorum` in the `GuardianSet` private and add a getter (as suggested by @SEJeff on #3967).
=> Node: Minor tweaks and spy improvement

node/hack/governor/src/index.ts
At @SEJeff 's request, the script now flags tokens that have changed their symbols since the last time the script was run. We can easily check for any funny business in these rare cases.
=> node: Token generator script flags tokens with changed symbols

ethereum/env/.env.gnosis.testnet, sdk/js/src/utils/consts.ts
Re-doing read-only deploy to Gnosis Chiado testnet since Sokol is deprecated.
```
-- Wormhole Core Addresses --------------------------------------------------
| Setup address                | 0x3245D2bC406af46B56c2a2328F7734E7D4C0231e |
| Implementation address       | 0x06Bc50Cf4768929465E07199567B36Da6C74808c |
| Wormhole address             | 0xBB73cB66C26740F31d1FabDC6b7A46a038A300dd |
-----------------------------------------------------------------------------
```
Core:
https://gnosis-chiado.blockscout.com/address/0xBB73cB66C26740F31d1FabDC6b7A46a038A300dd?tab=txs
Implementation:
https://gnosis-chiado.blockscout.com/address/0x06Bc50Cf4768929465E07199567B36Da6C74808c
=> Deploy Gnosis Chiado Testnet

node/pkg/governor/flow_cancel_tokens.go, node/pkg/governor/governor_test.go
- Add canonical Solana and Ethereum stablecoins
- Remove Aave USDC
The original flow cancel PR had a token list that wasn't representative of the actual tokens that we want to flow cancel #3798. This PR modifies that list.
The updated token list now consists of:
- USDC originating on Ethereum and Solana
- USDT originating on Ethereum and Solana
- DAI originating on Ethereum
=> node: Update flow cancel tokens

node/pkg/governor/governor.go, node/pkg/governor/governor_test.go
There was an issue in the flow cancel mechanism. Tokens were not being indexed correctly (using token Origin and token address) so the logic for cancelling transactions was never triggered.
This got through due to a gap in unit test coverage in #3798. The issue is in the function `ProcessMsgForTime` and while the small component functions were tested, this function was not.
This PR makes the following changes:
- Indexes the tokenEntry for flow cancel tokens properly (using the
token's origin chain and origin address)
- Adds many more tests and assertions to check flow cancel logic in more detail and at
the resolution of the ProcessMsgForTime method.
Big thanks to @mdulin2 for helping to debug the issue and the unit tests.
=> node: Fix bug in flow cancel mechanism where the wrong values were being used for tokenEntry

docs/governor.md
The original PR to add a "number of days" argument did not update the documentation to reflect the change. This PR changes that.
=> docs: update governor docs to reflect reset-release-timer change

node/pkg/governor/governor_db.go, node/pkg/governor/governor_test.go
Flow-canceling is done in the `ProcessMsgForTime` loop when a new message occurs. However, this was not done when a node restarted and reloaded transfers from the past 24 hours. As a result it was possible for the node to calculate a result that showed that the outgoing transfers for an emitter chain exceeded the daily limit. In effect this is true but only with the condition that there was incoming flow to allow this to happen. This appeared to violate an invariant and so the node did not start properly.
=> node: Fix issue where transfers that were loaded from the DB did not add a flow-cancel transfer on the TargetChain

node/pkg/watchers/evm/watcher.go, node/pkg/watchers/evm/watcher_test.go
Noticed a few additional error returns in the log that we could retry on.
=> Node/EVM: Add more cases to canRetryGetBlockTime

node/hack/governor/src/index.ts
The endpoint address for Sui appears to have been changed: https://www.allthatnode.com/sui.dsrv
Previous URL was failing with:
```
FetchError: request to https://sui-mainnet-rpc.allthatnode.com/ failed, reason: getaddrinfo ENOTFOUND sui-mainnet-rpc.allthatnode.com
at ClientRequest.<anonymous> (/Users/dirk/code/wormhole/node/hack/governor/node_modules/node-fetch/lib/index.js:1491:11)
at ClientRequest.emit (node:events:517:28)
at TLSSocket.socketErrorListener (node:_http_client:501:9)
at TLSSocket.emit (node:events:517:28)
at emitErrorNT (node:internal/streams/destroy:151:8)
at emitErrorCloseNT (node:internal/streams/destroy:116:3)
at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
type: 'system',
errno: 'ENOTFOUND',
code: 'ENOTFOUND'
}
```
when trying to run …
=> node/hack: Update Sui RPC endpoint

clients/js/src/consts/networks.ts, ethereum/env/.env.berachain.testnet
We originally deployed to Berachain testnet in April 2024.
Recently Berachain deprecated V1 (Artio) in favor of V2 (bArtio).
Although we deployed the contracts and updated the SDK, it was never actually enabled in testnet, so no integrators ever used it. For that reason, we are able to use the same chain ID as before.
Additionally, when the contracts were deployed to the new network, the addresses were the same, so the SDK does not need to be updated.
This PR makes the couple of minor changes needed to reflect the new deployment.
The core is deployed [here](https://bartio.beratrail.io/address/0xBB73cB66C26740F31d1FabDC6b7A46a038A300dd/contract/80084/code), the token bridge is deployed [here](https://bartio.beratrail.io/address/0xa10f2eF61dE1f19f586ab8B6F2EbA89bACE63F7a/contract/80084/code) …
=> Deploy Berachain V2 testnet

clients/eth/main.go, node/cmd/ccq/p2p.go, node/cmd/ccq/utils.go, node/cmd/guardiand/adminclient.go, node/cmd/guardiand/admintemplate.go
This PR replaces `fmt.Errorf` without parameters with `errors.New`
=> chore(node/cmd): replace `fmt.Errorf` without parameters with `errors.New`

.devcontainer/devcontainer.json, node/Dockerfile, scripts/check-docker-pin.sh
This PR adds a [devcontainer.json](https://code.visualstudio.com/docs/devcontainers/containers) to aid in the development of node / guardian code. While development is currently possible in Linux (including WSL on Windows), providing this container adds an option for non-WSL Windows and ARM (M-series) Mac users which only requires Docker and VS Code. It also shares the same dockerfile used in CI for added assurance of compatibility. Relevant to #4031. Please note, this dockerfile _explicitly_ specifies amd64, which means it will run via qemu or rosetta (depending on your Docker settings) - as far as I understand, the cosmwasm dependency (and possibly others) requires this and there will be a slight performance hit, but it is useable.
=> node: devcontainer support

cosmwasm/contracts/ibc-translator/Cargo.toml, cosmwasm/contracts/wormchain-ibc-receiver/Cargo.toml, cosmwasm/contracts/wormchain-ibc-receiver/src/ibc.rs, cosmwasm/contracts/wormhole-ibc/Cargo.toml, cosmwasm/contracts/wormhole-ibc/src/ibc.rs
These flags were previously not declared, which is now reported by clippy.
Also fixed the docstring indentation, which clippy also complains about now.
=> cosmwasm: add missing feature flags in Cargo.toml files

node/hack/governor/src/index.ts
There's a script that adds a list of tokens into a file called `generated_mainnet_tokens.go` once every two weeks. This adds some input validation on the CoinGecko data before being inserted into the Go code. 
This is meant to be a temporary fix while a more robust mechanism, such as a JSON config file or the usage of a real Go code generation library, is completed. 
I ran this on the production endpoint and this did not violate any tokens in the current list either.
=> Input Validation on Generated Token List

node/hack/repair_eth/repair_eth.go
Fix error flagged by `errcheck` via `golangci-lint`
=> node: Fix lint violation in hack/repair_eth/repair_eth.go

near/test/watcher.go, wormchain/testutil/keeper/wormhole.go, wormchain/x/wormhole/client/cli/genesis.go, wormchain/x/wormhole/client/cli/tx_wasmd.go
According to https://pkg.go.dev/io/ioutil.
> Deprecated: As of Go 1.16, the same functionality is now provided by package [io](https://pkg.go.dev/io) or package [os](https://pkg.go.dev/os), and those implementations should be preferred in new code. See the specific function documentation for details.
This PR changes those deprecated packages to the new one.
=> change ioutil to io and os

node/pkg/governor/devnet_config.go, node/pkg/governor/testnet_config.go
The previous entries had incorrect CoinGecko symbol information. This commit updates the values in these config files to use the same data as their counterparts in the generated token list for mainnet.
=> node: Update token entries for devnet and testnet configs

node/pkg/node/node_test.go
There is a race condition in the node tests where the logger can get destroyed before the supervisor finishes logging on exit. This PR makes the tests in question wait for the supervisor to exit before cleaning up the logger.
Also, the tests in question were doing several defers that were not getting executed as expected because they were in a for loop, not a function. This PR changes the code so that the defers get executed between each test.
=> ci: fix node tests fail intermittently

node/pkg/gwrelayer/gwrelayer.go, node/pkg/gwrelayer/gwrelayer_test.go
We are occasionally seeing the gateway relayer logging an error when the contract returns "this asset has already been attested". This should not be logged as an error.
=> Node: Gateway relayer can ignore already attested return

node/hack/governor/package-lock.json, node/hack/governor/src/index.ts
- The script used to generate the updated token list was using an outdated version of the TS SDK. This caused newer chains to return a result of 'undefined' when they were converted to the custom ChainId type as they were not encluded in the enum of valid chain IDs
- Update the local SDK version used by the script via `npm update @certusone/wormhole-sdk`
- Adds additional logging to the script to help troubleshoot similar errors in the future
To test:
- Before this commit: run `node/hack/governor/src/index.ts`, observe error output relating to Scroll. Note that Scroll has no governed tokens in the generated tokens list
- On this commit: do the same. No error and Scroll will be updated to be in the generated token list.
=> node: Fix missing support for chains in generated token list due to outdated SDK

cosmwasm/deployment/terra2/Makefile
Recently Terra2 started failing in CI saying "docker-compose: not found". The `docker-compose` command has been replaced by `docker compose`. Although I'm not sure why things suddenly stopped working (Did the docker version in CI get updated?), it works after changing it. 🤷
=> Terra2: Use "docker compose", not "docker-compose"

ethereum/Dockerfile
We have seen [some instances](https://github.com/wormholelabs-xyz/wormhole/actions/runs/10162658975/job/28103791466#step:6:9835) in CI where anvil returns a block number which doesn't match the one queried. Perhaps this issue has been fixed since the [nightly currently being used (2024-05-26)](https://github.com/foundry-rs/foundry/commit/ea2eff95b5c17edd3ffbdfc6daab5ce5cc80afc0). Confirmed that the forge output is still the same by exec-ing into the container and running the following before and after the change then diffing the result.
```bash
cd ~/app/ethereum/build-forge
find . -type f -exec sha256sum {} \;
cd ~/app/relayer/ethereum/build-forge
find . -type f -exec sha256sum {} \;
```
=> ci: bump foundry to 2024-08-04 nightly

node/pkg/db/db.go, node/pkg/db/db_test.go, node/pkg/processor/broadcast.go, node/pkg/processor/cleanup.go, node/pkg/processor/message.go, node/pkg/processor/observation.go, node/pkg/processor/observation_test.go, node/pkg/processor/processor.go, node/pkg/processor/vaa.go
This PR contains a number of small performance improvements to the processor.
- Writes to the badger DB on a separate go routine. 
- Adds the ability to write multiple VAAs using the BadgerDB batch API.
- Speeds up processing of local observations.
- Adds some measurements to monitor the time to handle observations and quorum.
- Removes some unnecessary map look ups.
- Removes unnecessary debugging code.
=> Node: Processor performance improvements

node/cmd/guardiand/node.go, node/pkg/node/node_test.go, node/pkg/node/options.go
This PR allows the guardians to not subscribe to inbound VAAs via the `subscribeToVAAs` config parameter.
This parameter defaults to false, since the only reason a guardian may want to subscribe is if they are acting as a public RPC. If they do not subscribe, they will only be able to report status on VAAs they have actually published.
=> Node/P2P: Allow disabling subscribing to VAAs

docs/query_proxy.md, node/cmd/ccq/devnet.permissions.json, node/cmd/ccq/parse_config_test.go, node/cmd/ccq/permissions.go, node/cmd/ccq/utils.go, node/pkg/watchers/evm/blocks_by_timestamp.go, node/pkg/watchers/evm/ccq.go
This PR allows the permissions in the queries proxy server to use a wildcard in the contract address field.
It also makes some logging changes in the guardian CCQ code to help debug problems.
To specify a wildcard on an eth call type, the `contractAddress` should be set to `"*"` rather than a specific address.
=> Node/CCQ: Allow address wildcard

node/pkg/watchers/solana/ccq.go, node/pkg/watchers/solana/ccq_test.go
We are seeing quite a few cases where the Solana watcher is able to read the desired slot, but then fails to look up the block associated with that slot (to get the block time). This is most likely due to load balancing. This PR adds a retry mechanism for that case.
=> Node/CCQ: Solana should retry block read

node/pkg/governor/manual_tokens.go
Evan made a nice suggestion for how to check which token transfers are ungoverned. With a BQ query and a Python script to parse the results I've made a few small changes to the manual token list.
- Add PayPal USD
- Update NEAR price
- Add Aptos USDT
- Fix SEI token address
Note that the SEI token address had a small typo (leading `00` has been updated to `01`).
=> node: Update governor manual tokens list

node/pkg/p2p/p2p.go, node/pkg/processor/observation.go
This PR makes a couple of changes to minimize the impact of gossip traffic received from a guardian that is not in the guardian set.
=> Node: Unknown guardian tweaks

node/pkg/governor/mainnet_tokens_test.go
The control flow for this function should be `continue` rather than `return`, otherwise the entire test will exit early when evaluating an ignored chain rather than skip the current iteration as intended.
In practice, this test just so happened to work OK because:
- the only ignored chain is Wormchain with ID 3104
- 3104 is the last entry in the slice
- iteration over slices is deterministic 
And so the test always returned early when hitting Wormchain, but Wormchain is the last item in the list.
=> node/test: fix incorrect control flow in governed assets test

ethereum/README.md, ethereum/sh/registerAllChainsOnTokenBridge.sh
This script is used to register all existing chains on a new chain. It currently requires that the new chain be supported by the `worm` cli, which can make it difficult to use for newly added chains. This PR removes the dependency on the `worm` cli in favor of reading parameters from the command line and then `.env` file.
=> Eth: Make registerAllChainsOnTokenBridge not require worm support

devnet/query-server.yaml, docs/query_proxy.md, node/cmd/ccq/devnet.permissions.json, node/cmd/ccq/http.go, node/cmd/ccq/metrics.go, node/cmd/ccq/parse_config_test.go, node/cmd/ccq/permissions.go, node/cmd/ccq/query_server.go, sdk/js-query/src/query/ethCall.test.ts
This PR adds support for rate limiting. Please see the query server operations guide for details.
Note that this PR also removes the  `--allowAnything`  command line argument used in testnet and replaces it with the `allowAnythingSupported` attribute in the permissions file.
This change simplifies the command for verifying updates to the json file to be:
```
$ guardiand query-server --env mainnet --verifyPermissions --permFile new.permissions.file.json
```
=> Node/CCQ: Add rate limiting to proxy

docs/operations.md
This PR adds instructions for deploying a wormchain validator.
The goal of these changes is to make the onboarding of the new guardians easier.
=> docs: instructions for deploying a wormchain validator.

node/pkg/governor/manual_tokens.go
- Remove BOTX token (not significant - 4 lifetime transfers)
- Update Near token decimals: https://etherscan.io/address/0x85f17cf997934a597031b2e18a9ab6ebd4b9f6a4#readContract
- Aurora has been deprecated so remove relevant tokens (chain id: 9)
- Update Polkadot on Acala token decimals: https://acala.subscan.io/custom_token?unique_id=asset_registry%2Fb025a485e041bae59c2453dc19ed03c465809955
- Update KLEVA on Klatyn token decimals: https://klaytnscope.com/token/0x5fff3a6c16c2208103f318f4713d4d90601a7313?tabId=tokenTransfer
- Update WEMIX on Klatyn token decimals: https://klaytnscope.com/token/0x5096db80b21ef45230c9e423c373f1fc9c0198dd?tabId=tokenTransfer
- Add Acala (ACA) token
The decimals changes aren't critical as they get [normalised down to …
=> node: Fix + update governor manual tokens list

node/pkg/p2p/gossip_cutover.go, node/pkg/processor/cutover.go
This PR enables observation batching and the split of gossip traffic into the new topics in devnet / tilt. It does that by setting the cutover dates for devnet to a time in the past.
=> Node: Enable batching and gossip split in tilt

node/pkg/processor/message.go
The recent refactoring of the processor included a change to not do all of the `handleObservation` processing on our own observations. This avoids unnecessary work, but the change also caused us to stop pegging `wormhole_observations_signed_by_guardian_total`, which at least one guardian does not like. This PR make it peg that metric for our own observations.
=> Node/Processor: Peg observation metric for us

node/pkg/p2p/gossip_cutover.go, node/pkg/processor/cutover.go
This PR sets the date to cutover to the new gossip topics and observation batching on testnet. This PR will have no effect until the cutover date (September 24th, 2024, 9am Central Daylight Time).
=> Node: Set cutover date for testnet

node/pkg/watchers/evm/connectors/batch_poller.go, node/pkg/watchers/evm/connectors/batch_poller_test.go
This PR changes the EVM batch poller so that it publishes the current finalized and safe blocks on startup. This is helpful for chains with longer finality times because reobservation requests are not allowed until we have received the first finalized / safe block.
=> Node/EVM: Batch poller publish initial blocks

clients/js/src/consts/networks.ts
The ankr RPC was frequently 429'ing the CI tests.
=> clients/js: switch eth rpc

SECURITY.md
The max reward on immunefi is $5M as shown in the screenshot here 
Also is there a hard upper limit at $5M? or are critical issues paid using the W token and then $5M is just an estimate of how much 20M W tokens would convert to, at the current price of W?
=> Update bug bounty reward limit in SECURITY.md

sdk/mainnet_consts.go
[Here's](https://guardian.mainnet.xlabs.xyz/v1/governor/enqueued_vaas) proof that the endpoint works.
=> go-sdk: Add xLabs public RPC

node/pkg/p2p/gossip_cutover.go, node/pkg/processor/cutover.go
This PR sets the time for the gossip network in mainnet to be cutover to using the split topics and observation batching.
A release containing this PR must be deployed to all guardian nodes before that time (9:00 CDT, October 29th, 2024).
=> Node: Set mainnet gossip cutover time

ethereum/anvil_fork, ethereum/sh/upgrade.sh, ethereum/sh/upgrade_all_testnet.sh
The `set -u` options in these scripts caused them to fail with 'unbound variable' errors when CLI args or env variables were unset. This commit fixes the validation so that the scripts output usage info or helpful errors instead of exiting with unbound variable errors that the user must read the source to diagnose.
for the script `ethereum/sh/upgrade_all_testnet.sh`, the commit updates a variable name that appears incorrect.
=> eth: fix unbound variable errors in shell utilities

node/hack/governor/src/index.ts
This addition to the governor token generation script searches for and prints and tokens that look like USD stablecoins and have deviated from the expected $1 price by more than a certain percentage (defaults to 10%). It discards any false positive matches that are specified in an array.
To start with I've only considered USD stablecoins.
Output for the current token list looks something like:
```
Potentially depegged USD stablecoins (>10%) = 5:
<WH_chain_id>-<WH_token_addr>-<token_symbol> = <token_price>
[
"2-000000000000000000000000df574c24545e5ffecb9a659c229253d4111d87e1-HUSD = 0.02706502",
"13-0000000000000000000000005c74070fdea071359b86082bd9f9b3deaafbe32b-KDAI = 0.20189",
"13-000000000000000000000000754288077d0ff82af7a5317c7cb8c444d421d103-oUSDC = 0.247451", …
```
=> node/hack: Print potential USD stablecoins that appear depegged

sdk/README.md, sdk/js/README.md
It is in fact no longer a pre-alpha release in active development
=> Add deprecation warning to the top of SDK readme

node/cmd/spy/spy.go
`guardiand spy --port` wouldn't be respected and the default port was always used.
=> spy: respect --port if set

node/pkg/common/guardianset.go, node/pkg/common/guardianset_test.go, node/pkg/p2p/p2p.go
The `p2p.Run` method is not subscribing to the channel topic if a client (such as the historical uptime monitor) subscribes to heartbeats via the guardian set state but not any other of the other events that use the control topic. This results in never seeing heartbeats.
I tested this by hacking the spy to subscribe to heartbeats using the guardian set state.
=> Node: p2p.Run not always subscribing to heartbeat channel when it should

Tiltfile, wormchain/Dockerfile.deploy, wormchain/Makefile, wormchain/ts-sdk/package.json
Ignite, which is used to generate go and TS code for wormchain / Cosmos, now fails due to a deprecated protobuf dependency. As far as I understand, these files are already committed, but the step was left as the ignite build is non-deterministic, so it was not possible to add enforcement in CI that the committed code matches what would be generate (as with the other pre-compiled sources, such as the node protobuf files).
As soon as the version of Ignite is upgraded, the generation should be moved to a CI check like the others to ensure it matches what is committed.
=> wormchain: disable ignite

node/pkg/governor/mainnet_chains.go
There is a discussion #4163 recommending that the daily limit for Solana and Ethereum be increased.
=> Temporarily increasing governor limits for a few chains

node/pkg/watchers/evm/ccq.go, node/pkg/watchers/solana/ccq.go
Seeing CCQ errors in the log that are not really errors, just the users making bad requests. This PR changes those to infos. Also, for Solana, it adds another case were we will retry to read the block info before failing.
=> Node/CCQ: Logging changes in watchers

clients/js/src/consts/networks.ts, ethereum/Dockerfile, relayer/ethereum/ts-scripts/relayer/config/kubernetes/chains.json, testing/Dockerfile.sdk.test
This PR mitigates a bug where `localhost` was not resolving in node.js for Kubernetes (v1.29.2) in Docker Desktop 4.29.0 and later. It also fixes an issue when pulling the amd64 foundry image with sha on aarch64 Macs.
=> tilt: support latest docker desktop

cosmwasm/packages/accountant/src/state/account.rs, cosmwasm/packages/accountant/src/state/addr.rs, cosmwasm/packages/accountant/src/state/transfer.rs, cosmwasm/packages/cw_transcode/src/ser.rs, sdk/rust/serde_wormhole/src/de.rs, sdk/rust/serde_wormhole/src/ser.rs
by removing the binders for inferrable lifetimes
=> fix clippy::needless-lifetimes warnings

Tiltfile, devnet/solana-devnet.yaml, solana/Dockerfile.test-validator, wormchain/.dockerignore, wormchain/Dockerfile.deploy
This PR adds support for `solana-test-validator` within Docker / Tilt for M-series Macs. This is useful for downstream projects such as NTT which rely on a subset of the tilt setup for e2e testing. It may also benefit contributors who wish to run a minimal tilt setup on their Macs.
The key hold up was Rosetta 2 lacking AVX instruction support, which `solana-test-validator` relies upon. Everything would compile as `amd64` but would not run. Further complicating efforts, there is not a pre-built binary for linux/aarch64. Unlike prior attempts to build the entire solana dependency under `aarch64`, this simply swaps out the binary used.
This same shortcoming may also prevent some other chains from running, such as Near. Further work could be done to provide `aarch64` alternative dockerfiles …
=> tilt: m1 flag

Tiltfile, testing/sdk.sh
The following gets all containers running and relevant tests passing with the exception of
- Near
- Aptos
- Sui
That is because those images require instructions sets that are not supported by Rosetta2 (likely AVX). As far as I can tell, pre-built binaries or images do not exist for linux/arm64, but they could potentially be built, akin to what I did for `solana-test-validator`.
This was tested with 8 CPU / 24 GB memory under Docker resources with the command `tilt up -- --ci --num=2 --m1 --near=false --aptos=false --sui=false`. Fair warning it took nearly 2 hours, but that was with rebuilding nearly all of the images.
Everything should succeed except 
`sdk-ci-tests`
```
FAIL src/token_bridge/__tests__/sui-integration.ts
FAIL src/nft_bridge/__tests__/aptos-integration.ts (10.318 s)
FAIL …
```
=> tilt: mac improvements

Tiltfile, aptos/Docker.md, aptos/Dockerfile, aptos/Dockerfile.base, node/Dockerfile, sdk/js-query/src/query/solana.test.ts, solana/Dockerfile.test-validator, sui/Docker.md, sui/Dockerfile, sui/Dockerfile.base
This PR removes the m1 flag in favor of the multi-platform `solana-test-validator` image [[src](https://github.com/wormholelabs-xyz/solana-test-validator), [image](https://github.com/orgs/wormholelabs-xyz/packages/container/package/solana-test-validator)]. It also uses the newly rebuilt multi-image aptos and sui images and makes the guardian image compatible with an arm64 or amd64 build.
With this PR, Near should now be the only container and test that fails on M-series Macs, which I tested via `tilt up -- --ci --num=2 --near=false`.
It is important to note that, when available, images should pin the *index* digest, which identifies the registry entry, not the manifext digest, which identifies a single platform image. See https://docs.docker.com/build/building/multi-platform/.
Reviewers: …
=> tilt: more multi-platform support

node/cmd/guardiand/node.go, node/pkg/adminrpc/adminserver_test.go, node/pkg/governor/governor.go, node/pkg/governor/governor_monitoring_test.go, node/pkg/governor/governor_prices.go, node/pkg/governor/governor_test.go, node/pkg/node/adminServiceRunnable.go, node/pkg/node/node_test.go, node/pkg/node/options.go, node/pkg/publicrpc/publicrpcserver_test.go
In case the Guardians want to use API keys for Coin Gecko, support for the API keys has been added. This changes code in the Guardian and adds a command line flag.
Testing this is difficult because we don't want to include a key in here. Prior to this, I don't think we had tests for the query success from CoinGecko anyway. So, I added tests that make requests to coin gecko using the standard and pro APIs. If the API key isn't specified in the test file, the test is just skipped. If there's a better way to do this or relying on external APIs for builds to succeed is bad practice, then please say something and I'm happy to make changes accordingly.
=> Add coin gecko pro API usage for the governor

whitepapers/0004_message_publishing.md
Adds a note to the whitepaper in reference to issue #4211.
=> docs: add TransferFees conformance note

node/pkg/governor/mainnet_chains.go, node/pkg/governor/mainnet_chains_test.go
Any objections to doubling the limits on Ethereum and Solana due to the recent high volumes on these 2 chains?
=> Double the limits on Ethereum and Solana

node/cmd/guardiand/node.go
Starting and stopping a temporary guardian in testnet causes false alarms in monitoring. This is because monitoring looks for heartbeats from all guardians for which it has seen heartbeats.
This PR allows the running of temporary guardians without heartbeating by omitting the `--nodeName` parameter *in testnet only*. This should prevent these false alarms.
=> Node: Allow no heartbeating in testnet

node/pkg/governor/mainnet_chains.go, node/pkg/governor/mainnet_chains_test.go
Reverts https://github.com/wormhole-foundation/wormhole/pull/4225 as the traffic surge turned out to be very short lived, the higher limit is not needed at this time.
=> Node: Revert #4225 (Double the limits on Ethereum and Solana)

cspell-custom-words.txt, node/cmd/txverifier/README.md, node/pkg/txverifier/evm.go, node/pkg/txverifier/evm_test.go, node/pkg/txverifier/evmtypes.go, node/pkg/txverifier/evmtypes_test.go
- Sometimes From _can_ be set to the zero address when a token is minted. This restriction has been removed
- Made error handling around irrelevant receipts less noisy. Now there will not be any WARN logs when a receipt contains a LogMessagePublished event that was sent by someone other than the token bridge.
- Changed functions that process receipts to always return nil rather than the empty struct
- Added more unit tests to ensure that functions don't panic in nil input
- Added Validation function for TransferReceipts
- Add README for running the Transfer Verifier CLI tool
- Fix typo in variable name
=> txverifier: fix bugs and improve error handling

node/pkg/watchers/evm/chain_config.go, node/pkg/watchers/evm/chain_config_test.go, node/pkg/watchers/evm/verify_chain_config/verify.go
The old code that determined the finality values for creating the appropriate poller reported that instant finality chains did not support finalized or safe. This was okay because the finalized / safe flags were not used for instant finality chains. However, now that we have this chain config, which can also be used as a way to document chain behavior, it would be useful to have the correct finalized / safe values for instant finality chains, just for documentation purposes. 
This PR adds an `InstantFinality` flag to the chain config tables and also sets the correct values for `Finalized` and `Safe` for instant finality chains. Additionally, this PR enhances the `verify_chain_config` tool to validate the values for `Finalized` and `Safe` against the public RPC endpoints.
Here is the …
=> Node/EVM: Add instant finality to chain config

node/pkg/watchers/evm/chain_config.go, node/pkg/watchers/evm/chain_config_test.go
We noticed recently that Berachain reports different block numbers for latest and finalized / safe. This PR updates it to use the batch poller rather than the instant finality poller.
=> Node/EVM: Berachain not instant finality

.github/workflows/build.yml
Ubuntu 20.04 actions runner is now deprecated. https://github.com/actions/runner-images/issues/11101
=> ci: bump ubuntu-20.04 to ubuntu-24.04

clients/js/src/cmds/generate.ts
This PR adds support for generating chain registrations for chains that have not yet been added to the SDK by explicitly specifying their chain ID and platform. This is often an issue when deploying / testing new chains locally or in testnet before they are officially supported in the SDK.
=> cli: arbitrary chain registration

node/cmd/ccq/p2p.go, node/cmd/ccq/query_server.go, node/cmd/guardiand/node.go, node/cmd/spy/spy.go, node/pkg/node/node_test.go, node/pkg/node/options.go, node/pkg/p2p/ccq_p2p.go, node/pkg/p2p/p2p.go, node/pkg/p2p/run_params.go, node/pkg/p2p/run_params_test.go, node/pkg/p2p/watermark_test.go
This PR adds the ability to specify a set of P2P peer IDs that should be added to the protected list.
**Guardian**
This is done for the guardian with something like this:
```
--protectedPeers 12D3KooWE4dmZwxhfjCKHLUqSaww96Cf7kmq1ZuKmzPz3MrJgZxp,12D3KooWMkxuNh1abxCRjsfNZ9D2C8ZgcsQ4xxbXBuuqdxVRbasu \
--protectedPeers 12D3KooWCW3LGUtkCVkHZmVSZHzL3C4WRKWfqAiJPz1NR7dT9Bxh,12D3KooWJXA6goBCiWM8ucjzc4jVUBSqL9Rri6UpjHbkMPErz5zK \
--ccqProtectedPeers 12D3KooWE4dmZwxhfjCKHLUqSaww96Cf7kmq1ZuKmzPz3MrJgZxp,12D3KooWMkxuNh1abxCRjsfNZ9D2C8ZgcsQ4xxbXBuuqdxVRbasu \
--ccqProtectedPeers  12D3KooWCW3LGUtkCVkHZmVSZHzL3C4WRKWfqAiJPz1NR7dT9Bxh,12D3KooWJXA6goBCiWM8ucjzc4jVUBSqL9Rri6UpjHbkMPErz5zK \
```
Note that there can be multiple instances of the same parameter, and each instance may contain either a single …
=> Node/P2P: Add protected peers list

node/hack/repair_eth/repair_eth.go, node/pkg/governor/mainnet_chains.go, node/pkg/governor/mainnet_tokens_test.go, node/pkg/watchers/evm/chain_config.go, sdk/mainnet_consts.go
This PR enabled Ink in mainnet.
- The core is available [here](https://explorer.inkonchain.com/address/0xCa1D5a146B03f6303baF59e5AD5615ae0b9d146D).
- The token bridge is available [here](https://explorer.inkonchain.com/address/0x3Ff72741fd67D6AD0668d93B41a09248F4700560).
Due to a bug in the explorer, both are labeled as `TokenBridge`. See the "Read/Write Proxy" tab to confirm each is the correct contract.
Here is the output from the command to confirm that the EVM chain ID and Finalized / Safe flags are correct.
```
verify_chain_config (main *)$ go run verify.go --env mainnet
<snip>
EVM chain ID match for prod ink: value: 57073
verify_chain_config (main *)$
```
=> Deploy Ink mainnet

node/pkg/watchers/solana/client.go
The log messages showing the result of a solana reobservation request (both success and failure) are logging the identifier as a hex string when it is really a base58 encoded string. This means that the result message does not have the same identifier as the request. This PR makes them consistent.
Also changed `txID` to a more generic `identifier` since it can be either an account ID or a transaction signature.
=> Node / Solana: Fix reobservation ID in log msg

devnet/node.yaml, node/cmd/guardiand/node.go, node/cmd/txverifier/evm.go, node/go.mod, node/hack/parse_eth_tx/parse_eth_tx.go, node/pkg/common/chainlock.go, node/pkg/common/chainlock_test.go, node/pkg/node/node.go, node/pkg/node/node_test.go, node/pkg/node/options.go, node/pkg/txverifier/evm.go, node/pkg/txverifier/evmtypes.go, node/pkg/txverifier/evmtypes_test.go, node/pkg/txverifier/utils.go, node/pkg/txverifier/utils_test.go, node/pkg/watchers/evm/by_transaction.go, node/pkg/watchers/evm/config.go, node/pkg/watchers/evm/msg_verifier.go, node/pkg/watchers/evm/reobserve.go, node/pkg/watchers/evm/watcher.go, node/pkg/watchers/evm/watcher_test.go, sdk/devnet_consts.go, sdk/mainnet_consts.go, sdk/testnet_consts.go
* Create a TxVerifier instance in the Run function of the EVM watcher
* Wrap all instances where a message would be published to the broadcasting msg channel with a new function,  `verifyAndPublish`
* Messages are published with a new status: `VerificationState`. 
* Modified the Transfer Verifier pkg API so that we can call the method with either an existing Receipt or a txHash.
* Added unit test in the watcher for new functionality
- Messages that are token transfers will undergo Transfer Verification
- Message will be published with a status of Valid or Rejected depending on the result
- The calling code can then decide what to do based on this status
- Existing behaviour will be preserved, but messages will be published with a status of NotVerified. No further actions are taken when a …
=> node: Integrate Transfer Verifier into the Ethereum watcher

sdk/vaa/structs.go, sdk/vaa/structs_test.go
In many places in the Guardian, the following is done:
```go
// equivalent to `cid := uint16(x)`
cid := vaa.ChainID(x)
```
As `ChainID()` is just a custom type around `uint16`, this is equivalent to doing an unchecked type-conversion to uint16, which could result in edge-case truncation/overflow/sign-change issues.
The motivation for this change is to provide a clear way to go from any integer type to a ChainID in a type-safe way. With this PR, someone could instead write the following:
```go
// just type-safe
cid, err := vaa.ChainIDFromNumber(x)
// type-safe + corresponds to a real chain
cid, err := vaa.KnownChainIDFromNumber(x)
```
If the general idea seems good, I will merge this work with #4239 in the future so that the function introduced in that PR will use `KnownChainIDFromNumber` …
=> sdk: Add functions for type-safe conversions from integers to ChainID

node/hack/repair_eth/repair_eth.go, node/pkg/watchers/evm/chain_config.go, node/pkg/watchers/evm/chain_config_test.go, node/pkg/watchers/evm/verify_chain_config/verify.go
This PR enhances the EVM chain config to include the core contract address. This provides easy access to the contract addresses and also allows the `verify_chain_config` to confirm that the contract exists at the expected location. This PR also enhances the tool to make it easier to see what it is doing.
Note that, although it would be possible to use these contract addresses as defaults for the guardian, we are not doing that at this time since it could make it easier for an attacker to compromise the watchers.
Note, while working on this PR, I realized that Linea was currently allowed in mainnet when it should not be, so I fixed that.
Note to reviewers: If you trust the verify tool, you don't need to worry about validating the contract addresses. . .
=> Node/EVM: Add contract address to chain config

node/cmd/root.go, node/go.mod
This dependency is deprecated and seems easy to replace via a call to the standard library.
Background: https://github.com/mitchellh/go-homedir/issues/34
Note that this is still an indirect dependency for us:
```sh
$ go mod why github.com/mitchellh/go-homedir
github.com/certusone/wormhole/node/pkg/telemetry
github.com/grafana/loki/clients/pkg/promtail/client
github.com/grafana/loki/pkg/util
github.com/grafana/dskit/kv
github.com/grafana/dskit/kv/consul
github.com/hashicorp/consul/api
github.com/hashicorp/go-rootcerts
github.com/mitchellh/go-homedir
```
There is an open PR to remove this dependency in `github.com/hashicorp/go-rootcerts` as well, at which point it shouldn't be a dependency for us. https://github.com/hashicorp/go-rootcerts/pull/28
=> node: Remove go-homedir dependency

sdk/vaa/structs.go, sdk/vaa/structs_test.go
Adds a function to the SDK's vaa structs that parses known ChainIDs from string representations of ints or chain names.
I've found myself wishing that this function exists in the context of working with ChainIDs. It's nice to have this parsing and validation provided by the SDK.
=> sdk: add StringToKnownChainID function for VAAs

node/cmd/guardiand/node.go, node/pkg/node/node_test.go, node/pkg/node/options.go, node/pkg/p2p/p2p.go, node/pkg/p2p/run_params.go, node/pkg/p2p/run_params_test.go, node/pkg/p2p/watermark_test.go
This PR adds a the Solana shim to the feature flags published in heartbeat messages (as "solshim") so that we can see in the dashboard if a guardian has it enabled. This feature can be used for other features, such as the Fogo shim.
=> Node: Add Solana shim feature flag

devnet/tx-verifier/Dockerfile.cast, devnet/tx-verifier/Dockerfile.tx-verifier-evm, ethereum/Dockerfile, ethereum/foundry, testing/Dockerfile.sdk.test
It looks like some of the nightly releases of foundry are disappearing. This PR pins foundry to a specific official release.
=> Tilt/CI: Pin foundry release

Makefile, node/Makefile
Adds convenience `make lint` commands for the root directory and `node/`.
=> node: add targets for linting to Makefiles

node/cmd/guardiand/adminclient.go, node/cmd/guardiand/node.go, node/pkg/altpub/README.md, node/pkg/altpub/alternate_pub.go, node/pkg/altpub/alternate_pub_test.go, node/pkg/altpub/end2end_test.go, node/pkg/common/url_verification.go, node/pkg/common/url_verification_test.go, node/pkg/node/node.go, node/pkg/node/node_test.go, node/pkg/node/options.go, node/pkg/node/url_verification.go, node/pkg/p2p/p2p.go, node/pkg/p2p/run_params.go, node/pkg/processor/broadcast.go, node/pkg/processor/message.go, node/pkg/processor/processor.go
Please see the file README.md for an overview of this feature.
Note that this PR includes moving `url_verification.go` from `node/pkg/node` to `node/pkg/common` and updating all references to it. This was necessary so the `altpub` package could use `ValidateURL` without causing a circular reference.
=> Node: Alternate publishers

.golangci.yml
Rework of #4307 after the major version upgrade for golangci-lint.
The rules have also been sorted alphabetically.
=> ci: add golangci-lint linters with no violations

sdk/vaa/structs.go, sdk/vaa/structs_test.go
- Updates SDK function and unit tests to return false for the empty case. This is to prevent the function returning true trivially for empty arguments. Either true or false may be 'correct', but returning false is less likely to lead to failing open if empty arguments are passed by mistake.
- Adds a comment warning that VerifySignatures is the wrong function to use when actually validating a VAA. (This is a bug that has occurred before but was caught in internal review.)
=> sdk: Return false for empty arguments to VerifySignatures

node/go.mod, node/pkg/node/options.go, node/pkg/node/reobserve.go, node/pkg/node/reobserve_test.go
- Replaces the [archived dependency](https://github.com/benbjohnson/clock)'s mock clock capabilities with an interface defined in the files that use it. The implementation is similar to how the library does it.
- Update go.mod via `go mod tidy`
- Minor refactoring of reobserve.go to change in-line durations to named constants.
=> deps: Remove benbjohnson/clock as a direct dependency

node/pkg/watchers/solana/client.go, node/pkg/watchers/solana/client_test.go, node/pkg/watchers/solana/config.go
This PR does some minor clean up of the Solana watcher. Notably:
- Optimizes the check to see if a transaction might include a wormhole `PostMessage`
- Can't save the `ctx` across a restart since it may have previously been canceled
- Removes logging of the commitment level since it is in the logger name
- Cleans up various other log messages
- A few other minor things
- Don't count the wrong commitment level as an observation
=> Node/Solana: Minor watcher cleanup

.golangci.yml, node/cmd/txverifier/evm.go, node/cmd/txverifier/sui.go, node/hack/release_verification/guardian_vaa_stats.go, node/pkg/adminrpc/adminserver.go, node/pkg/adminrpc/prototext_test.go, node/pkg/common/armoredKey.go, node/pkg/common/chainlock_test.go, node/pkg/governor/governor.go, node/pkg/governor/governor_prices.go, node/pkg/governor/governor_test.go, node/pkg/guardiansigner/filesigner.go, node/pkg/guardiansigner/guardiansigner.go, node/pkg/node/node_test.go, node/pkg/processor/backoff.go, node/pkg/processor/cleanup.go, node/pkg/processor/observation.go, node/pkg/query/request.go, node/pkg/txverifier/sui.go, node/pkg/watchers/aptos/watcher.go, node/pkg/watchers/evm/ccq.go, node/pkg/watchers/ibc/watcher.go, node/pkg/watchers/near/finalizer.go, node/pkg/watchers/near/nearapi/nearapi.go
https://golangci-lint.run/usage/linters/#nolintlint
Configuration:
* All `nolint` directives need a reason
* The tool will flag nolints that aren't actually triggered (i.e. it'll flag outdated directives that don't apply anymore). (When a nolint is removed here, this is why.)
* Ensures correct formatting
This PR was created by adding the linter and then running `golangci-lint run --fix`. Then I went in and added manual comments where necessary. 
In a few cases I added TODO comments where the lint seemed correct. The idea is to limit the scope of this PR is to add the new linter, not to refactor existing code.
=> ci: Add nolintlint to golangci-lint

DEVELOP.md, cspell-custom-words.txt
- Add golangci-lint as a developer requirement and note the version (see #4322)
- Update the documentation for getting a minimal Tilt instance running. The existing documentation is incorrect.
=> docs: Fix Tilt minimal run command; add linter requirement

node/cmd/guardiand/node.go, node/pkg/altpub/alternate_pub.go, node/pkg/node/node_test.go, node/pkg/node/options.go, node/pkg/p2p/p2p.go, node/pkg/p2p/run_params.go, node/pkg/p2p/run_params_test.go, node/pkg/p2p/watermark_test.go, node/pkg/processor/processor.go, node/pkg/watchers/ibc/watcher.go
This feature cleans up the guardian feature flags published in heartbeat messages and displayed in the dashboard.
It does the following:
- Removes the individual chains from the IBC flag (since they are hard coded for a release). It keeps the wormchain version. Listing all the chains was taking up too much space in the dashboard.
- Adds a feature flag for the TX Verifier feature.
- Introduces the concept of static and dynamic feature flags. The static ones are built once on initialization and passed into `p2p.go` via the `featureFlags` parameter. Dynamic feature flags are generated each heartbeat interval and are passed into `p2p.go` via the `featureFlagFuncs` parameter. These functions are evaluated each interval and the results added to the features list.
- Sorts the feature flags so …
=> Node: Clean up feature flags

node/go.mod, node/pkg/adminrpc/adminserver.go
- The adminserver.go file was using an experimental version of the slices package. This isn't necessary as the functions it uses are all available in the stable package.
=> deps: Use stable slices package instead of experimental release

node/cmd/guardiand/adminclient.go, node/cmd/guardiand/adminverify.go, node/go.mod
- This dependency was being used only to print hex-encoded bytes, but this can be done by passing `%x` to `fmt.Printf()`
`go mod tidy` has removed this as a direct dependency.
=> deps: Remove status-im/keycard-go

ethereum/Makefile, relayer/ethereum/Makefile
The `--no-commit` flag has been removed: https://github.com/foundry-rs/foundry/pull/9884
CI is now failing as a result when pulling the `stable` foundry release via https://github.com/foundry-rs/foundry-toolchain/releases/tag/v1
https://github.com/wormhole-foundation/wormhole/actions/runs/14776517039/job/41485875483?pr=4357
```sh
Run cd ethereum && make test-push0 && make test
touch -m node_modules
npm ci
npm WARN reify Removing non-directory /home/runner/work/wormhole/wormhole/ethereum/node_modules
added 117 packages, and audited 118 packages in 2s
39 packages are looking for funding
run `npm fund` for details
5 vulnerabilities ([4](https://github.com/wormhole-foundation/wormhole/actions/runs/14776517039/job/41485875483?pr=4357#step:5:5) high, 1 critical)
To address all issues, run:
npm …
```
=> ethereum: remove deleted "--no-commit" flag from forge commands

.github/workflows/build.yml
CI is having transient failures around golangci-lint. Trying to bump the version to see if this makes the lints more stable.
Example: https://github.com/wormhole-foundation/wormhole/actions/runs/14778216211/job/41491112350?pr=4363
(I'm unable to reproduce this locally on `main`)
=> ci: update golangci-lint to 2.1.5

algorand/runPythonUnitTests.sh
This fixes errors related to 'docker compose' not being installed. This should unblock CI.
The version of the sandbox we use has a bug with its `docker compose`
check. This commit includes a workaround to get CI to work.
I tried upgrading to the latest `sandbox` version but it caused other errors. Rather than attempt a full upgrade, this commit does a cheeky rewrite of the upstream `sandbox` script to fix how it detects docker.
Compare with:
https://github.com/algorand/sandbox/blob/59803a56a2d254bc49df36e964dc4e4f94435446/sandbox#L45-L55
Upstream bug fix PR:
https://github.com/algorand/sandbox/pull/206
=> ci: Fix docker-related errors in Algorand job

docs/governor.md
Adds instructions for enabling flow cancel. Note that there is no plan to enable this yet. The earliest time we would enable this is after Transfer Verifier is complete.
=> docs: Add instructions for enabling flow cancel in the Governor

node/cmd/ccq/permissions.go, node/cmd/ccq/query_server.go, node/go.mod, node/go.sum
- The fswatch repository seems to be abandoned, whereas fsnotify is actively supported and appears to be popular.
https://github.com/go-godo/godo/tree/v2.0.9/watcher/fswatch (last released 10 years ago)
https://github.com/fsnotify/fsnotify
I had a hard time getting the Query Server to work, both inside of Tilt and when directly running `guardiand`. 
I encountered blocking failures for the p2p section of `query_server.go` that I couldn't resolve, so I moved the permissions block above the p2p block.
After this was done, I tested by running a combination of:
* `touch node/cmd/ccq/devnet.permissions.json`
* `nano node/cmd/ccq/devnet.permissions.json`
* `nvim node/cmd/ccq/devnet.permissions.json`
I confirmed that making modifications via nano and neovim trigged the file reload. As noted in …
=> deps: Replace godo/fswatch with fsnotify/fsnotify

node/cmd/debug/vaa.go, node/cmd/guardiand/adminclient.go, node/cmd/guardiand/adminverify.go, node/go.mod, sdk/vaa/structs.go
Remove unmaintained dependency. It was only being used to print a dump of VAAs, so this PR adds a function specifically for debugging VAA info and removes the dependency.
- Removes go-spew (https://github.com/davecgh/go-spew) as it has not been updated in 7 years.
- Replaces the Go Spew functionality with a JSON-encoded string. The new function DebugString() can be used to get a spew-like output.
While the new format isn't the same, it does capture most of the existing functionality.
<details>
The command to run is the following:
```sh
./build/bin/guardiand debug decode-vaa 01000000040d034b96c773dce897724ed8ed4851cfa4f5077c35b7aa397251a3941fc587328a872ce9eac4228c692b2ce2ec9c4a958658fb7e290fdc98eaee1c9c2785c489c2ca010412878b0893d2b98c06490662174c22214417a299ddf6dbd11240fb5781891ff217d023c07 …
```
=> deps: Remove Go-Spew and add new debugging function for VAAs

node/cmd/guardiand/adminverify.go, sdk/vaa/payloads.go, sdk/vaa/payloads_test.go
* Fixed a bug that made chain id to appear twice in the `CoreBridgeSetMessageFee` payload.
* Fixed a format issue that was printing VAA digests as binary instead of as hex
=> guardiand: fix set message fee serialization

cspell-custom-words.txt, whitepapers/0007_governor.md
A documentation PR that adds information on Flow Cancel Tokens added in https://github.com/wormhole-foundation/wormhole/pull/3798.
Please let me know if the level of detail is sufficient or if it would be better to move the text to another section.
=> docs: Modify Governor whitepaper to include information about Flow Cancelling

devnet/node.yaml, docs/operations.md, node/cmd/guardiand/node.go, node/cmd/root.go, node/pkg/node/config_file_reader.go, node/pkg/node/config_file_reader_test.go
This PR allows a guardian operator to load config parameters from an arbitrary config file when running `guardiand node` by specifying the `--config <fname>` command line argument. This file may be in any of the formats supported by [Viper](https://pkg.go.dev/github.com/spf13/viper#section-readme), including .yaml and .json.
Parameters from this file are loaded first, then overridden by environment variables starting with `GUARDIAND`, and finally command line arguments.
**NOTE**: This PR changes existing behavior. Previously, if the file `node/config/guardiand.yaml` existed, it was loaded. However, this did not support specifying an arbitrary file location.
If you were previously using `node/config/guardiand.yaml` for your configuration, please add `--config node/config/guardiand.yaml` to …
=> Node: Specify config file

cosmwasm/contracts/shutdown-wormhole/src/testing/integration.rs
Rust 1.88 upgraded a new lint to a warning, causing our CI to fail https://github.com/rust-lang/rust-clippy/blob/master/CHANGELOG.md#moves-and-deprecations
This commit fixes the lint violation
=> ci: fix clippy lint violation

node/cmd/guardiand/node.go, node/pkg/watchers/solana/client.go, node/pkg/watchers/solana/config.go, node/pkg/watchers/solana/reobserve.go, node/pkg/watchers/solana/tx_for_addr.go
This PR updates the Solana watcher so that it can use the `getSignaturesForAddress` RPC call to poll for Wormhole observations, and enables the feature for Fogo. (This is the technique used in the dashboard monitor.)
Note that this PR does not affect the behavior for either Solana or Pyth.
The hope is that this technique will work better than the current technique of polling for every block, given Fogo's short block time.
Each interval (one second), it calls `getSignaturesForAddress` to read all transactions involving the Core contract since the last detected transaction. If it finds any transactions, it uses the standard transaction processing code to observe any messages.
This PR also adds the transaction signature to the "message observed" log message, to help with debugging and …
=> Node/Solana: TX for account

node/pkg/common/chain_id_test.go, node/pkg/common/nodekey_test.go
This PR adds a test to verify that the chain IDs defined in the protobuf match the ones defined in the go SDK.
Special thanks to @johnsaigle as this PR borrows code from his PR #4402.
This PR also disables some logging in the node key tests since it's just noise.
=> Node: Audit protobuf chain IDs

.github/workflows/build.yml, scripts/lint.sh
Runs `cspell` (if installed) as part of local linting. This allows developers to spellcheck locally and catch errors, which helps avoid doing an entire CI run that fails just because of a typo.
=> ci: add cspell to lint script

node/pkg/governor/mainnet_chains.go, node/pkg/governor/mainnet_chains_test.go
Updates mainnet configuration for the Governor:
```
Ethereum
$5M => $20M
Arbitrum
$500K => $2M
Base
$500K => $2M
Sui
$500K => $2M
Solana
$2.5M => $10M
```
=> governor: update big transaction limits

.golangci.yml
https://github.com/charithe/durationcheck
> A Go linter to detect cases where two time.Duration values are being multiplied in possibly erroneous ways.
> Consider the following (highly contrived) code:
```go
func waitForSeconds(someDuration time.Duration) {
timeToWait := someDuration * time.Second
fmt.Printf("Waiting for %s\n", timeToWait)
}
func main() {
waitForSeconds(5) // waits for 5 seconds
waitForSeconds(5 * time.Second) // waits for 1388888h 53m 20s
}
```
=> ci: Add durationcheck linter

node/pkg/accountant/ntt_config.go, node/pkg/accountant/ntt_test.go
Mezo Transceiver: https://explorer.mezo.org/address/0x56E27f1A8425515FFD4BD76A254Ac1a5c0B66D71
Ethereum Transceiver: https://etherscan.io/address/0x76ddb3f1dde02391ef0a28664499b74c29d18d3e
=> node: Add emitters for mUSD deployment to NTT Accountant

sui/testing/scripts/upgrade-token-bridge.ts, sui/testing/scripts/upgrade-wormhole.ts, sui/token_bridge/Move.testnet.toml, sui/wormhole/Move.testnet.toml
This PR updates updates the sui testnet upgrade scripts for both the wormhole and token_bridge contracts to perform the upgrade and migration against the actual deployments.
Also, update the `published-at` addresses of these contracts to the most recently deployed versions.
=> sui: testnet updates

node/cmd/txverifier/evm.go, node/pkg/txverifier/evm.go, node/pkg/txverifier/evm_test.go, node/pkg/txverifier/evmtypes.go, node/pkg/txverifier/evmtypes_test.go, node/pkg/txverifier/utils.go, node/pkg/watchers/evm/msg_verifier.go, node/pkg/watchers/evm/watcher_test.go
- Update TransferIsValid method to support per-message validation
- Add `msgID` parameter (equivalent to VAA ID) to `TransferIsValid` method
signature to enable validation of specific messages within transaction
receipts. Update caching mechanism to store per-message validation
results instead of per-transaction results. Modify receipt processing
to track message-specific evaluations and validate transfer amounts on
a per-message basis.
Key changes:
- Add msgID parameter to TransferIsValid method for targeted message validation
- Replace single Result field in evaluation struct with Results map keyed by message ID
- Update receipt summary to track transfers per message ID rather than aggregated amounts
- Modify invariant checking to validate each message's transfers individually
- Add …
=> node(transfer verifier): Update TransferIsValid method to return results per Message rather than per Receipt

node/pkg/txverifier/evmtypes.go
We identified an issue with the EVM transfer verifier in testnet, where it was reading the EVM chain id from the connector and attempting to parse it into a `uint64`, with 16-bit resolution. This failed for Sepolia, which has the EVM chain id 11155111. 
This change replaces the conversion with the `big.Int` `Uint64()` method, instead.
=> fix(transfer verifier): Use Uint64() instead of parseUint for EVM chain ID conversion

.github/CODEOWNERS
Allows the security team to review dependencies for major components before being upgraded. This was discussed in the security meeting this week.
Review the added `go.mod` files to ensure these are the correct ones to add. I intentionally left out Wormchain's `go.mod` , but I would consider adding it and others if others were passionate about it.
=> Add CODEOWNERS for Guardian Dependency Upgrades

near/Makefile
- Removed the Make target for package-lock.json. There's already a lock file in-place that should be used in most cases. Otherwise, developers should be thoughtfully upgrading packages slowly when the needed arises. Exposing a make target for `npm install` is suboptimal and encourages a workflow that goes against the contributor guidelines.
=> node(near): Replace `npm install` with `npm ci`

node/pkg/watchers/algorand/watcher.go, node/pkg/watchers/aptos/watcher.go, node/pkg/watchers/cosmwasm/watcher.go, node/pkg/watchers/evm/watcher.go, node/pkg/watchers/near/nearapi/mock/mock_server.go, node/pkg/watchers/near/nearapi/nearapi.go, node/pkg/watchers/near/nearapi/types.go, node/pkg/watchers/near/watcher.go, node/pkg/watchers/solana/client.go, node/pkg/watchers/sui/watcher.go
Thanks to @SEJeff for https://github.com/wormhole-foundation/wormhole/pull/2520 from which this is based.
This has been tested manually for every watcher in Tilt devnet to confirm we get the expected output.
I have also deliberately induced a panic in a `logVersion` method and confirmed that CI fails. For watchers without tests, the watcher will boot loop in Tilt and eventually timeout. The new changes are designed in such a way that if the version can't be fetched successfully an error is logged and the watcher continues as normal.
=> node: Log version on watcher start

CONTRIBUTING.md, cspell-custom-words.txt, whitepapers/0014_transfer_verifier.md
Adds a whitepaper for the Transfer Verifier.
Future work: the Sui details should be added to the whitepaper once #4324 is stable and merged.
=> node: Add Transfer Verifier whitepaper

node/pkg/governor/governor.go, node/pkg/governor/governor_db.go, node/pkg/governor/governor_prices.go, node/pkg/governor/governor_test.go
- Change the function visibility for Governor methods that are currently only used internally by the package. This helps to minimize the API for the Governor package.
Fixes #2846. It's possible that not all of the public methods/constants have high-quality docstrings but this is something we should address generally with a linter if we care about it.
=> node(governor): make internal-only methods private
