wormhole-foundation/wormhole

- bridge/pkg/terra/watcher.go
- terra/contracts/wormhole/src/contract.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/94)
> Non-deterministic VAAs formed by Terra watcher fixed

- bridge/cmd/guardiand/bridge.go
- bridge/pkg/devnet/constants.go
- bridge/pkg/processor/observation.go
- bridge/pkg/terra/sender.go
- devnet/bridge.yaml
Resolves #96 , #95
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/129)
> Terra key moved out from env variable, VAA submission on Terra made async

- proto/agent/v1/service.proto
- solana/agent/src/main.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/141)
> Watch slots for Solana liveness monitoring

- ethereum/contracts/WrappedAsset.sol
Closes #81
This only affects readonly methods.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/152)
> Add more metadata to erc20 token name

- ethereum/contracts/Wormhole.sol
This allows external contracts to verify VAAs using a public method and is required for #147.
No logic has been touched and the public function is using the `view` modifier which makes it read-only.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/153)
> Refactor VAA parsing into public view method

- bridge/cmd/guardiand/adminclient.go
- bridge/cmd/guardiand/adminserver.go
- bridge/cmd/guardiand/admintemplate.go
- bridge/cmd/guardiand/adminverify.go
- bridge/cmd/root.go
- bridge/pkg/processor/observation.go
- bridge/pkg/vaa/structs.go
- bridge/pkg/vaa/types_test.go
- docs/protocol.md
- docs/solana_program.md
- proto/node/v1/node.proto
- scripts/test-injection.sh
- solana/Cargo.lock
- solana/agent/Cargo.toml
- solana/bridge/Cargo.toml
- solana/bridge/src/error.rs
- solana/bridge/src/error_program.rs
- solana/bridge/src/instruction.rs
- solana/bridge/src/processor.rs
- solana/bridge/src/vaa.rs
- solana/cli/Cargo.toml
- third_party/solana/Dockerfile
Closes #78
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/151)
> Implement upgradeability

- solana/bridge/src/processor.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/163)
> Fix rent calculation and hardening

- terra/contracts/wormhole/src/contract.rs
- terra/contracts/wormhole/src/error.rs
- Magic numbers replaced by constants
- Outdated TODOs removed
- Added boundary checks when accessing byte data from VAAs
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/167)
> Fixed remaining Terra contract issues from the code review report

- DEVELOP.md
- bridge/cmd/vaa-test-terra/main.go
- bridge/cmd/vaa-test/main.go
- bridge/e2e/e2e_test.go
- bridge/e2e/eth.go
- bridge/e2e/solana.go
- bridge/e2e/terra.go
- bridge/pkg/devnet/constants.go
- bridge/pkg/ethereum/utils.go
- bridge/pkg/ethereum/watcher.go
- terra/contracts/wormhole/src/contract.rs
Fixes #164 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/168)
> Added missing e2e tests between Terra and Ethereum/Solana

- bridge/cmd/guardiand/bridge.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/173)
> Terra support enabled in production mode

- bridge/pkg/terra/watcher.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/176)
> Added Terra node height monitoring

- bridge/pkg/solana/client.go
- bridge/pkg/terra/watcher.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/177)
> Asynchronously fetch Terra block height

- bridge/pkg/processor/observation.go
Fixes #184
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/191)
> Fix guardian set initialization race condition

- bridge/e2e/terra.go
- terra/contracts/wormhole/Cargo.toml
- terra/contracts/wormhole/src/contract.rs
- terra/contracts/wormhole/src/error.rs
- terra/contracts/wormhole/src/msg.rs
- terra/contracts/wormhole/src/state.rs
- terra/contracts/wormhole/tests/integration.rs
- terra/tools/lock-token.ts
- terra/tools/utils.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/182)
> Added VAA verification query to the Terra smart contract, lock fees, refactoring

- solana/bpf-sdk-install.sh
- solana/do.sh
This fixes master, helps us use the current method for installing the toolchain and makes it easier to work with multiple Solana programs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/193)
> Updates for newest beta bpf-sdk, small do.sh refactor

- bridge_ui/src/hooks/useTVL.ts
Change-Id: Ic9a59dd847b87c6354b2615d8ea657652c1e2813
> bridge_ui: remove incorrect prices from tvl

- Tiltfile
- devnet/bigtable.yaml
- event_database/cloud_functions/Dockerfile
- event_database/cloud_functions/Dockerfile.run
- event_database/cloud_functions/cmd/main.go
**Stack**:
- #614
- #613
- #606
- #605
- #604
- #603
- #602
- #601
- #600
- #599
- #598
- #597
- #596
- #595
- #594
- #593
- #592
- #591
- #590
- #589
- #588
- #587
- #586
- #585
- #584
Change-Id: I931501aa5162569785cb078a546dc44a3741de08
> devnet: simplify cloud function setup

- bridge_ui/src/utils/consts.ts
Change-Id: I4471446113ba516e08cd68275d7a8f0d65e88103
> bridge_ui: add avax to coming soon list

- devnet/node.yaml
- node/cmd/guardiand/adminnodes.go
- node/cmd/guardiand/node.go
- node/pkg/common/readiness.go
- node/pkg/vaa/structs.go
- proto/publicrpc/v1/publicrpc.proto
<pre>
commit-id:31eeeb35
</pre>
> node: add oasis support

- bridge_ui/src/components/Recovery.tsx
- bridge_ui/src/components/Transfer/Redeem.tsx
- bridge_ui/src/hooks/useFetchTargetAsset.ts
- bridge_ui/src/hooks/useGetIsTransferCompleted.ts
- bridge_ui/src/hooks/useMetadata.ts
- bridge_ui/src/store/transferSlice.ts
- bridge_ui/src/utils/consts.ts
Notify the user when they're trying to redeem a transfer that has
already been redeemed.
Added useGetIsTransferCompleted hook
> bridge_ui: Transfer already redeemed feature

- node/cmd/guardiand/adminnodes.go
- node/cmd/guardiand/node.go
- node/pkg/solana/client.go
- node/pkg/solana/recovery.go
**Stack**:
- #655 ⮜
- #649
- #648
<pre>
We're not ready to release this yet.
commit-id:c2d6531f
</pre>
> node: move oasis to testnet mode

- node/cmd/guardiand/adminnodes.go
- node/cmd/guardiand/node.go
<pre>
This reverts commit 9ad792c6eec97a05c5f801b41d28541e58237038.
commit-id:896988bd
</pre>
> Revert "node: move oasis to testnet mode"

- bridge_ui/src/components/Transfer/Redeem.tsx
> bridge_ui: Don't display amount on Redeem step

- node/pkg/reporter/bigtablewriter.go
So it can be used elsewhere, in cloud functions.
> export MakeRowKey in bigtablewriter.go

- bridge_ui/src/components/Transfer/FeaturedMarkets.tsx
- bridge_ui/src/components/Transfer/RedeemPreview.tsx
- bridge_ui/src/utils/consts.ts
> bridge_ui: Show featured markets when redeemed tokens, link to Jupiter swap

- terra/Cargo.lock
- terra/Cargo.toml
- terra/contracts/cw721-wrapped/.cargo/config
- terra/contracts/cw721-wrapped/Cargo.toml
- terra/contracts/cw721-wrapped/examples/schema.rs
- terra/contracts/cw721-wrapped/schema/all_nft_info_response.json
- terra/contracts/cw721-wrapped/schema/approval_response.json
- terra/contracts/cw721-wrapped/schema/approvals_response.json
- terra/contracts/cw721-wrapped/schema/contract_info_response.json
- terra/contracts/cw721-wrapped/schema/execute_msg.json
- terra/contracts/cw721-wrapped/schema/instantiate_msg.json
- terra/contracts/cw721-wrapped/schema/minter_response.json
- terra/contracts/cw721-wrapped/schema/nft_info_response.json
- terra/contracts/cw721-wrapped/schema/num_tokens_response.json
- terra/contracts/cw721-wrapped/schema/operators_response.json
- terra/contracts/cw721-wrapped/schema/owner_of_response.json
- terra/contracts/cw721-wrapped/schema/query_msg.json
- terra/contracts/cw721-wrapped/schema/tokens_response.json
- terra/contracts/cw721-wrapped/src/lib.rs
- terra/contracts/cw721-wrapped/src/msg.rs
- terra/contracts/cw721-wrapped/src/state.rs
**Stack**:
- #700
- #699
- #698
- #697 ⮜
<pre>
Wrapped NFT contract
</pre>
> terra/nft_bridge: Implement cw721-wrapped

- sdk/js/CHANGELOG.md
- sdk/js/package-lock.json
- sdk/js/package.json
- sdk/js/src/index.ts
- sdk/js/src/nft_bridge/__tests__/consts.ts
- sdk/js/src/nft_bridge/__tests__/integration.ts
- sdk/js/src/nft_bridge/getForeignAsset.ts
- sdk/js/src/nft_bridge/getIsTransferCompleted.ts
- sdk/js/src/nft_bridge/getOriginalAsset.ts
- sdk/js/src/nft_bridge/index.ts
- sdk/js/src/nft_bridge/redeem.ts
- sdk/js/src/nft_bridge/transfer.ts
> sdk/js: Terra NFT bridge support

- sdk/js/CHANGELOG.md
- sdk/js/src/nft_bridge/getIsTransferCompleted.ts
- sdk/js/src/nft_bridge/getIsWrappedAsset.ts
- sdk/js/src/nft_bridge/getOriginalAsset.ts
- sdk/js/src/rpc/getSignedVAAWithRetry.ts
- sdk/js/src/rpc/index.ts
- sdk/js/src/solana/index.ts
- sdk/js/src/token_bridge/getForeignAsset.ts
- sdk/js/src/token_bridge/getIsTransferCompleted.ts
- sdk/js/src/token_bridge/getIsWrappedAsset.ts
- sdk/js/src/token_bridge/getOriginalAsset.ts
> sdk/js: v0.1.6

- node/pkg/solana/client.go
<pre>
commit-id:69632fa8
</pre>
> node/pkg/solana: fix context memory leak

- ethereum/contracts/bridge/Bridge.sol
- terra/contracts/token-bridge/src/contract.rs
Safeguard against malicious tokens with reentrancy protection. These contracts are already deployed on all evm chains and terra on mainnet.
> Reentrancy protection

- node/cmd/guardiand/adminserver.go
- node/cmd/guardiand/adminverify.go
And add some extra debug logging for governance-vaa-verify.
> cmd/guardiand: fix governance VAA serialization

- node/pkg/db/db.go
- node/pkg/vaa/structs.go
commit-id:1fb9f998
---
**Stack**:
- #821
- #798
- #797
- #796 ⮜
> node/pkg/db: add db.VaaIDFromString and vaa.StringToAddress helpers

- docs/operations.md
> Fix a typo in operations.md

- sdk/js/CHANGELOG.md
- sdk/js/package-lock.json
- sdk/js/package.json
- sdk/js/src/nft_bridge/__tests__/integration.ts
- sdk/js/src/nft_bridge/getIsTransferCompleted.ts
- sdk/js/src/token_bridge/__tests__/integration.ts
- sdk/js/src/token_bridge/getIsTransferCompleted.ts
- sdk/js/src/token_bridge/getIsWrappedAsset.ts
- sdk/js/src/utils/consts.ts
- terra/devnet/config/genesis.json
Changed devnet terra tax rate to zero to reflect mainnet and testnet
> sdk/js: Updated terra dependencies

- bridge_ui/package-lock.json
- bridge_ui/package.json
- bridge_ui/src/components/TerraWalletKey.tsx
- bridge_ui/src/contexts/TerraWalletContext.tsx
- bridge_ui/src/hooks/useGetIsTransferCompleted.ts
- bridge_ui/src/hooks/useTerraNativeBalances.ts
- bridge_ui/src/hooks/useTransactionFees.tsx
- bridge_ui/src/utils/terra.ts
Updated @terra-money/wallet-provider to 3.8.0
> bridge_ui: Updated terra dependencies

- devnet/node.yaml
- node/cmd/guardiand/adminnodes.go
- node/cmd/guardiand/node.go
- node/pkg/common/readiness.go
- node/pkg/vaa/structs.go
- proto/publicrpc/v1/publicrpc.proto
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/830)
> node: add fantom support

- node/hack/repair_eth/repair_eth.go
Change-Id: I2b7b825ab49dad68e7072a4f488bbc411cbaabd6
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/863)
> node/hack/repair: oasis support

- Tiltfile
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/864)
> Tiltfile: remove outdated generate-protos.sh mention

- .github/dependabot.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/859)
> specify dependabot dirs

- node/hack/repair_terra/repair.go
Change-Id: Ie015cb3364c56211ba51550cfae307836071532a
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/871)
> node/hack/repair_terra re-observation

- bridge_ui/src/components/TerraConnectWalletDialog.tsx
- bridge_ui/src/components/TerraWalletKey.tsx
- bridge_ui/src/components/TransactionProgress.tsx
- bridge_ui/src/contexts/TerraWalletContext.tsx
- bridge_ui/src/hooks/useGetTargetParsedTokenAccounts.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/866)
> bridge_ui: xdefi and leap wallet support

- solana/pyth2wormhole/client/src/main.rs
> pyth2wormhole-client: make sure we raise batch errors on exit

- ethereum/1conf.patch
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/906)
> eth: add nft bridge to 1conf

- bridge_ui/src/hooks/useTVL.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/911)
> bridge_ui: tvl chain name fix

- explorer/src/pages/index.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/916)
> explorer: use 2 decimals for TVL

- solana/pyth2wormhole/client/src/cli.rs
- solana/pyth2wormhole/program/src/attest.rs
- solana/pyth2wormhole/program/src/config.rs
- solana/pyth2wormhole/program/src/initialize.rs
- solana/pyth2wormhole/program/src/lib.rs
- solana/pyth2wormhole/program/src/types/mod.rs
- solana/pyth2wormhole/program/src/types/pyth_extensions.rs
- solana/pyth2wormhole/program/src/wasm.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/904)
> pyth2wormhole: rustfmt --config-path solana/rustfmt.toml

- .gitignore
- Dockerfile.proto
- Dockerfile.teal
- Tiltfile
- ethereum/Dockerfile
- node/Dockerfile
- solana/Dockerfile
- solana/Dockerfile.wasm
- terra/Dockerfile
was able to confirm limited success with the containers that support m1 and don't require containers without m1 support
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/923)
> support custom root ca

- node/cmd/guardiand/adminnodes.go
- node/cmd/guardiand/node.go
A few things for fantom mainnet
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/928)
> Fantom updates

- solana/pyth2wormhole/program/src/attest.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/921)
> pyth2wormhole: Fix attestation validation bug

- sdk/js/CHANGELOG.md
- sdk/js/src/token_bridge/transfer.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/939)
> sdk/js: Added relayerFee parameters to transfer functions

- sdk/rust/sdk/src/chains/solana.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/838)
> sdk/solana: post_message: added multiple seeds.

- .github/workflows/build.yml
- DEVELOP.md
- Tiltfile
- devnet/node.yaml
Drive-by reformat the Tiltfile using buildifier.
---
**Stack**:
- #910
- #891
- #890 ⮜
- #892
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/890)
> devnet: add --guardiand_debug flag

- .github/workflows/build.yml
- DEVELOP.md
- Tiltfile
- devnet/node.yaml
- node/pkg/common/guardianset.go
- node/pkg/ethereum/watcher.go
commit-id:e94ce253
---
**Stack**:
- #910 ⮜
- #891
- #890
- #892
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/910)
> node/pkg/ethereum: log blockhash for new message publications

- bridge_ui/src/utils/consts.ts
- sdk/js/CHANGELOG.md
- sdk/js/package.json
- sdk/js/src/nft_bridge/redeem.ts
- sdk/js/src/nft_bridge/transfer.ts
- sdk/js/src/token_bridge/attest.ts
- sdk/js/src/token_bridge/createWrapped.ts
- sdk/js/src/token_bridge/redeem.ts
- sdk/js/src/token_bridge/transfer.ts
- sdk/js/src/token_bridge/updateWrapped.ts
- sdk/js/src/utils/array.ts
- sdk/js/src/utils/consts.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/940)
> Feat add karura acala sdk support

- bridge_ui/src/components/NFT/Source.tsx
- bridge_ui/src/components/OasisNetworkUpgradeWarning.tsx
- bridge_ui/src/components/Transfer/Source.tsx
…essage
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/955)
> bridge_ui: Disable transfers from oasis and display network upgrade warning

- node/pkg/ethereum/by_transaction.go
- node/pkg/ethereum/watcher.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/956)
> pkg/ethereum: check receipt status code

- bridge_ui/src/utils/consts.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/975)
> bridge_ui: remove fantom from beta

- ethereum/package-lock.json
This was missing from https://github.com/certusone/wormhole/pull/836
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/973)
> ethereum: fix package-lock.json

- sdk/js/README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/949)
> sdk/js: update README

- node/hack/repair_eth/repair_eth.go
Also, someone didn't `go fmt` when they previously edited this file, and my IDE insists.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/977)
> node/hack/repair_eth: add max retries to skip over broken entries

- bridge_ui/package-lock.json
- bridge_ui/package.json
- bridge_ui/src/components/Attest/Create.tsx
- bridge_ui/src/hooks/useHandleCreateWrapped.tsx
- bridge_ui/src/icons/acala.svg
- bridge_ui/src/icons/karura.svg
- bridge_ui/src/utils/consts.ts
- bridge_ui/src/utils/karura.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/937)
> Add testnet Karura and Acala support

- node/pkg/vaa/structs_test.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/978)
> Add struct tests2

- bridge_ui/src/hooks/useTransactionFees.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/984)
> bridge_ui: Show terra est. fees in UST, reassessed range (0.05 - 0.15 UST)

- clients/nft_bridge/main.ts
- clients/token_bridge/main.ts
Currently the typescript clients generate a fresh wallet and request airdrop into them. This obviously only works on tiltnet and testnet. Here we add an option to allow specifying a private key, which makes the command work in mainnet.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/929)
> clients: allow passing solana private key

- node/pkg/vaa/payloads_test.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/952)
> Add unit-tests for payloads

- event_database/cloud_functions/process-vaa.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/988)
> cloud_functions: use lowercase emitter addresses

- node/pkg/common/guardianset_test.go
Adds some unit-test coverage for GuardianSet.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/951)
> Add some unit-test coverage for GuardianSet

- sdk/js/src/token_bridge/TmplSig.ts
- sdk/js/src/token_bridge/TmplSigSource.ts
This change will make populate to generate a patched up TEAL code with template parameters and (if its required) compile the new source to obtain a matching LogicSignature.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/992)
> populate using TEAL source.

- bridge_ui/src/components/PolygonNetworkDownWarning.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/994)
> bridge_ui: be more specific about Polygon downtime

- bridge_ui/src/utils/coinGecko.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/991)
> bridge_ui: Added wrapped-fantom logo

- algorand/TmplSig.py
- sdk/js/src/token_bridge/TmplSigSource.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/996)
> Repl assert instead of long conditional for easier debug output

- bridge_ui/src/components/Stats/index.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/1008)
> bridge_ui: stats page null data fix

- bridge_ui/src/components/ChainWarningMessage.tsx
- bridge_ui/src/components/NFT/Source.tsx
- bridge_ui/src/components/NFT/Target.tsx
- bridge_ui/src/components/Transfer/Source.tsx
- bridge_ui/src/config.ts
- bridge_ui/src/utils/consts.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/997)
> bridge_ui: Make transfers to/from chains configurable

- bridge_ui/src/hooks/useTVL.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/1011)
> bridge_ui: fix receiving tvl for unknown chains

- event_database/README.md
- event_database/cloud_functions/README.md
- event_database/cloud_functions/addresses-transferred-to.go
- event_database/cloud_functions/external-data.go
- event_database/cloud_functions/go.sum
- event_database/cloud_functions/notional-transferred-to.go
- event_database/cloud_functions/notional-transferred.go
- event_database/cloud_functions/notional-tvl-cumulative.go
- event_database/cloud_functions/notional-tvl.go
- event_database/cloud_functions/recent.go
- event_database/cloud_functions/shared.go
- event_database/functions_server/.vscode/launch.json
- event_database/initialize_db/README.md
couple things here
- quicker init() by not fetching REST data if not needed by the function
- fixes for 2 digit chainIDs (fantom and beyond)
- rm some noisy logging
- added some basic docs
- added a VSCode launch config for running functions locally
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/1020)
> Cloud functions - misc fixes and improvements

- ethereum/contracts/nft/NFTBridge.sol
- ethereum/scripts/deploy_nft_bridge.js
- ethereum/test/nft.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/1018)
> eth/nft_bridge: burn before transfer

- node/pkg/processor/quorum_test.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/1023)
> Add unit test for 0 case and move to testify

- node/pkg/devnet/deterministic_bridge_key_test.go
- node/pkg/devnet/deterministic_p2p_key_test.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/1032)
> Add unit-tests for deterministic devnet keys

- node/pkg/vaa/structs_test.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/1006)
> Add more comprehensive structs unit-tests

- terra/contracts/cw20-wrapped/src/contract.rs
- terra/contracts/nft-bridge/src/contract.rs
- terra/contracts/nft-bridge/src/state.rs
- terra/contracts/nft-bridge/src/token_id.rs
- terra/contracts/wormhole/src/byte_utils.rs
- terra/contracts/wormhole/src/contract.rs
- terra/contracts/wormhole/src/state.rs
This saves us a bunch of unnecessary copying in various places.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/983)
> terra: contracts: fix clippy warnings

- node/pkg/common/nodekey_test.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/1035)
> Add unit-tests for nodekey

- .github/workflows/build.yml
- ethereum/.gitignore
- ethereum/Dockerfile
- ethereum/Makefile
- ethereum/migrations/6_deploy_bridge_implementation_only.js
- ethereum/package.json
- ethereum/test/bridge.js
- ethereum/test/upgrades/01_tokenbridge_feetoken_support.js
- ethereum/truffle-config.js
The tests currently fail. Ideally we could fix those tests and merge this in, so CI runs these tests for each PR.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/1028)
> Run ethereum tests on CI

- node/cmd/guardiand/node.go
- node/pkg/vaa/structs_test.go
Change-Id: I09b7d2da46507e219bd99d945256e63fefad529c
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/1044)
> Aurora and Fantom handled wrong in a couple cases in guardian

- bridge_ui/src/utils/consts.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/1055)
> bridge_ui: Fixed broken metaplex token-metadata program url

- node/pkg/processor/observation.go
This is dead code `err` is already nil checked in the lines above it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/1056)
> Remove dead code path

- node/hack/README.md
- node/hack/encrypt/encrypt.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/1057)
> Add README and crypto/rand for encrypt.go tool

- bridge_ui/src/utils/consts.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/1067)
> bridge_ui: add aurora to mainnet beta

- node/pkg/publicrpc/publicrpcserver.go
- node/pkg/publicrpc/publicrpcserver_test.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/1069)
> Rpc server unit tests

- .github/workflows/build.yml
This makes sure that the code builds successfully.
---
**Stack**:
- #1060
- #1059
- #1046
- #1045 ⬅
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/1045)
> Add `cargo check` to CI

- ethereum/truffle-verify-constants.patch
Change-Id: Ice6234c339fd59c0337640778559c9af84a3f3d6
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/1074)
> Add aurora to truffle verify patch

- bridge_ui/src/hooks/useRelayerInfo.ts
- bridge_ui/src/hooks/useRelayersAvailable.ts
- bridge_ui/src/utils/consts.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/1076)
> bridge_ui: use relayer fee schedule

- event_database/cloud_functions/notional-tvl-cumulative.go
fake WETH https://bscscan.com/tx/0x6767b7426fd408ee2103534f8cd22553aab98c1194305826933f5f23d2fc7e8d
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/1081)
> cloud functions - blacklist token from TVL calc

- event_database/cloud_functions/notional-tvl-cumulative.go
- event_database/cloud_functions/shared.go
the `init()` function is run by the Functions framework when a container boots up.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/1082)
> cloud functions - make tvl blacklist case insensitive

- bridge_ui/src/utils/consts.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/1084)
> bridge_ui: remove Aurora from beta

- ethereum/README.md
- ethereum/test/wormhole.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/1053)
> Add to ethereum contract integration test coverage

- sdk/js/src/token_bridge/__tests__/consts.ts
- sdk/js/src/token_bridge/__tests__/helpers.ts
- sdk/js/src/token_bridge/__tests__/integration.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/1029)
> sdk/js/src/token_bridge/__tests__: added more tests

- event_database/cloud_functions/notional-transferred.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/1088)
> cloud_functions: notional-transferred skipTokens support

- bridge_ui/src/components/Footer.tsx
Had to tweak the footer background image a bit
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/1080)
> bridge_ui: Added legal disclaimer footer

- bridge_ui/src/hooks/useIsWalletReady.ts
- bridge_ui/src/utils/metaMaskChainParameters.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/1085)
> bridge_ui: MetaMask wallet_addEthereumChain support

- ethereum/contracts/Messages.sol
This PR is only comments, but it aims to provide more eye-bleeding clarity around how this code works and where the really important decisions are being made.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/1025)
> Comment ethereum messages

- bridge_ui/src/hooks/useHandleCreateWrapped.tsx
- bridge_ui/src/hooks/useHandleNFTRedeem.tsx
- bridge_ui/src/hooks/useHandleRedeem.tsx
- bridge_ui/src/utils/postVaa.ts
- sdk/js/CHANGELOG.md
- sdk/js/package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/1096)
> bridge_ui,sdk: postVaa hotfix

- event_database/cloud_functions/shared.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/1103)
> Added fake testWETH on poly to tokensToSkip list

- bridge_ui/src/hooks/useHandleNFTRedeem.tsx
When minting NFT we also need these custom gas params, since the default gas param's storageLimit isn't enough for an NFT, so added gas overrides for it.
Tested locally: 
- before the change: redeeming NFT will throw error: `outOfStorrage`
- after the change: NFT transferring works bidirectionally Karura <=> Goerli
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/1104)
> fix gas for NFT minting with Karura/Acala

- event_database/cloud_functions/shared.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/1105)
> Added fake voxel to tokensToSkip list

- node/hack/repair_eth/repair_eth.go
Change-Id: Ic81b1082b72bb0cd66d9f15e951f6df2b92972ad
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/1109)
> Add fantom to repair script

- node/pkg/ethereum/watcher.go
Change-Id: Ida10e1ab0c056b4ed1ce2317800235843763a7ac
For Karura and Acala, we need to be sure we are connect to the safe mode endpoint. This PR makes the guardian check that on start up.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/1108)
> Add safe mode check

- event_database/cloud_functions/external-data.go
makes the cloud function throw an exception if CoinGecko returns a 401. removed some noisy logs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/1122)
> cloud functions - handle CoinGecko 401s and remove noisy logs

- bridge_ui/public/index.html
- bridge_ui/src/components/Footer.tsx
noticed this was old while I was updating DefiLama
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/1123)
> bridge_ui - update Portal twitter

- bridge_ui/src/components/Stats/Charts/TVLAreaChart.tsx
- bridge_ui/src/components/Stats/Charts/TVLLineChart.tsx
- bridge_ui/src/components/Stats/Charts/TransactionsAreaChart.tsx
- bridge_ui/src/components/Stats/Charts/TransactionsLineChart.tsx
- bridge_ui/src/components/Stats/Charts/VolumeAreaChart.tsx
- bridge_ui/src/components/Stats/Charts/VolumeLineChart.tsx
- bridge_ui/src/components/Stats/Charts/VolumeStackedBarChart.tsx
- bridge_ui/src/components/Stats/Charts/utils.tsx
- bridge_ui/src/components/Stats/VolumeStats.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/1128)
> bridge_ui: daily outbound volume stats, fix chart height

- bridge_ui/src/components/ShowTx.tsx
- bridge_ui/src/components/SmartAddress.tsx
- bridge_ui/src/components/TransactionProgress.tsx
- bridge_ui/src/hooks/useAllowance.ts
- bridge_ui/src/hooks/useGetSourceParsedTokenAccounts.ts
- bridge_ui/src/hooks/useHandleAttest.tsx
- bridge_ui/src/hooks/useHandleCreateWrapped.tsx
- bridge_ui/src/hooks/useHandleNFTRedeem.tsx
- bridge_ui/src/hooks/useHandleNFTTransfer.tsx
- bridge_ui/src/hooks/useHandleRedeem.tsx
- bridge_ui/src/hooks/useHandleTransfer.tsx
- bridge_ui/src/icons/celo.svg
- bridge_ui/src/icons/klaytn.svg
- bridge_ui/src/utils/consts.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/1139)
> bridge_ui: add klaytn and celo testnet support

- algorand/README.md
The `TmplSig` part was outdated as of the most recent changes
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/1138)
> algo: Update README.md

- node/cmd/guardiand/adminclient.go
Accept chain names (i.e. "solana") and base58 tx hashes.
---
**Stack**:
- #1115
- #1114 ⮜
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/1114)
> node/cmd/guardiand: improve send-observation-request arg parser

- Makefile
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/1145)
> guardiand version is always development

- event_database/cloud_functions/notional-transferred-to.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/1146)
> cloud_functions: Skip tokens in notional-transferred-to function

- bridge_ui/src/components/Recovery.tsx
Change-Id: Idffa9a56ba520b3ed5dc4c3dec593db0c0a9bf58
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/1149)
> bridge_ui: add guardianSetIndex to redeem

- event_database/cloud_functions/totals.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/1147)
> cloud_functions: totals cache should be overwritten for skipDates

- event_database/cloud_functions/notional-transferred-from.go
- event_database/functions_server/main.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/1125)
> cloud_functions: Added lightweight notional-transferred-from function

- event_database/cloud_functions/shared.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/1152)
> cloud_functions: Added tokens to skip

- clients/js/evm.ts
- clients/js/networks.ts
- clients/js/package-lock.json
- clients/js/package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/1159)
> CLI changes for klatyn, celo and moonbeam

- algorand/sandbox-algorand/images/algod/Dockerfile
- devnet/algorand-devnet.yaml
Algorand introduced new fields into the block on the master branch that were breaking the indexer that was on master
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/1168)
> algo/tilt: Fix algod validator 

- explorer/src/components/ExplorerSearch/ExplorerMessageSearchForm.tsx
- explorer/src/utils/consts.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/1156)
> explorer: Added Fantom and Aurora chains to message search selection

- node/pkg/algorand/watcher.go
[Josh Siegel]
if I wanted the guardian to be killed and restarted if I restart one of the chains (in Tilt) is there a easy way to do that?
[Leopold Schabel]
no.. the guardian should notice and restart itself
or well... restart the runnable, ideally, not the whole thing
can happen irl with multiple nodes behind a load balancer
--
guardian-0.root.algorandwatch   Algorand next_round set to 80
guardian-0.root.algorandwatch   Algorand next_round set to 80
guardian-0.root.algorandwatch   Algorand next_round set to 80
guardian-0.root.algorandwatch   Algorand next_round set to 80
guardian-0.root.algorandwatch   algodClient.Status: Get "http://algorand:4001/v2/status": dial tcp 10.110.223.73:4001: connect: connection refused
guardian-0.supervisor   Runnable died   {"dn": "root.algorandwatch", …
> algo/rollback: handle rollbacks gracefully

- bridge_ui/src/__tests__/unit.ts
- bridge_ui/src/components/TokenSelectors/TokenPicker.tsx
- bridge_ui/src/utils/balancePretty.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/1165)
> bridge_ui: changed formatting for token picker

- bridge_ui/package-lock.json
- bridge_ui/package.json
- bridge_ui/src/components/NFTOriginVerifier.tsx
- bridge_ui/src/components/Recovery.tsx
- bridge_ui/src/components/TokenOriginVerifier.tsx
- bridge_ui/src/components/TokenSelectors/SourceTokenSelector.tsx
- bridge_ui/src/components/UnwrapNative.tsx
- bridge_ui/src/hooks/useGetSourceParsedTokenAccounts.ts
- bridge_ui/src/utils/consts.ts
- bridge_ui/src/utils/metaMaskChainParameters.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/1173)
> bridge_ui: Add Celo to Mainnet Beta

- node/hack/repair_terra/repair.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/1183)
> node/repair: allow multiple sequences in a tx

- event_database/cloud_functions/shared.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/1194)
> Added fake btc on terra to tokensToSkip list

- sdk/js/CHANGELOG.md
- sdk/js/package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/1195)
> sdkVersionBump: SDK version bump and comments 

- explorer/src/components/Navbar.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/1193)
> explorer: Removed immunefi banner

- explorer/src/utils/consts.ts
- explorer/src/utils/explorer.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/1197)
> explorer: Added Aurora explorer URLs

- bridge_ui/src/utils/consts.ts
- relayer/spy_relayer/package-lock.json
- relayer/spy_relayer/package.json
- relayer/spy_relayer/src/relayer/evm.ts
- relayer/spy_relayer/src/utils/wormhole.ts
Thanks @bruce-riley for the prior art!
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/1196)
> relayer: support celo and klaytn

- bridge_ui/package-lock.json
- bridge_ui/package.json
- bridge_ui/src/contexts/SolanaWalletContext.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/1198)
> bridge_ui: add exodus wallet adapter

- clients/js/evm.ts
- clients/js/package-lock.json
- clients/js/package.json
- clients/js/worm-fetch-governance
- relayer/spy_relayer/src/relayer/evm.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/1199)
> Minor cli tweaks

- event_database/cloud_functions/shared.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/1211)
> cloud_functions: Added fake Dai Stablecoin on BSC to deny list

- node/cmd/guardiand/admintemplate.go
- node/cmd/guardiand/guardiankey.go
- node/pkg/common/nodekey_test.go
- node/pkg/devnet/deterministic_bridge_key.go
- node/pkg/devnet/deterministic_bridge_key_test.go
- node/pkg/devnet/deterministic_p2p_key.go
- node/pkg/devnet/guardianset_vaa.go
- node/pkg/supervisor/supervisor_node.go
- node/pkg/supervisor/supervisor_processor.go
just fix all warnings from gosec. Thinking about adding gosec as a linter to the repo in the future.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/1201)
> gosec fixes

- bridge_ui/src/components/Stats/Charts/TVLAreaChart.tsx
- bridge_ui/src/components/Stats/Charts/TVLLineChart.tsx
- bridge_ui/src/components/Stats/Charts/TransactionsAreaChart.tsx
- bridge_ui/src/components/Stats/Charts/TransactionsLineChart.tsx
- bridge_ui/src/components/Stats/Charts/VolumeAreaChart.tsx
- bridge_ui/src/components/Stats/Charts/VolumeLineChart.tsx
- bridge_ui/src/components/Stats/Charts/VolumeStackedBarChart.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/1212)
> bridge_ui: Added right padding to stats chart x-axis labels

- node/pkg/reporter/attestation_events.go
- node/pkg/reporter/attestation_events_test.go
also added a unit test.
This is my first PR! Please give me all the feedback you can :)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/1127)
> fix getUniqueClientId to actually return unique ID

- scripts/contract-upgrade-governance.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/1218)
> scripts: automate writing contract upgrade governance proposals

- node/pkg/vaa/structs.go
- node/pkg/vaa/structs_test.go
This PR lowers the minVAALength to 57 from 63.  I believe 57 is the true min length and added comments to the implementation on how came to this conclusion.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/1206)
> Add comments on vaa min length

- algorand/sandbox-algorand/images/algod/Dockerfile
- algorand/sandbox-algorand/images/indexer/Dockerfile
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/1225)
> Upgrade algod and indexer golang to 1.18.2

- terra/Makefile
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/1231)
> terra: fix terra test

- algorand/Dockerfile
- algorand/admin.py
- algorand/test/cnNftMetadata.json
- sdk/js/src/algorand/__tests__/testHelpers.ts
- sdk/js/src/algorand/__tests__/unit.ts
- terra/Makefile
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/1230)
> algo - add stuff to tilt

- .github/workflows/build.yml
- algorand/Makefile
- algorand/requirements.txt
- algorand/runPythonUnitTests.sh
- algorand/test/test.py
Allow for calling make test locally in algorand/ and from ci
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/1153)
> algo/make: add Makefile and test script 

- .gitignore
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/1237)
> ignore snyk cache .dccache

- bridge_ui/src/components/Stats/CustodyAddresses.tsx
- bridge_ui/src/utils/consts.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/1236)
> bridge_ui: Renamed Terra to Terra Classic, LUNA to LUNC

- .github/workflows/build.yml
- algorand/sandbox-algorand/images/indexer/disabled.go
- node/pkg/celo/abi/abi.go
- node/pkg/vaa/governance_test.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/1240)
> apply gofmt and enforce it for new commits

- bridge_ui/src/utils/terra.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/1247)
> bridge_ui: Terra Classic token symbols

- bridge_ui/src/utils/consts.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/1252)
> bridge_ui: Removed Karura from beta

- relayer/spy_relayer/README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/1253)
> update relayer readme

- lp_ui/README.md
- lp_ui/package-lock.json
- lp_ui/package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/1255)
> lp_ui: update docs

- bridge_ui/src/contexts/EthereumProviderContext.tsx
- bridge_ui/src/hooks/useGetSourceParsedTokenAccounts.ts
- bridge_ui/src/utils/consts.ts
- bridge_ui/src/utils/metaMaskChainParameters.ts
This PR is mainly a design review to make sure I did things the way they should be done.  So, please focus on design in addition to the code.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/1180)
> blockscout token picker

- node/cmd/guardiand/node.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/1257)
> Only require 64 confs in polygon testnet

- bridge_ui/src/components/TransactionProgress.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/1259)
> bridge_ui: Set Polygon testnet block confs to 64

- ethereum/contracts/Messages.sol
- ethereum/test/wormhole.sol
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/1162)
> Move quorum out of verifyVM

- node/pkg/algorand/watcher.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/1261)
> algo/watcher: Fixes for testnet

- bridge_ui/src/components/TokenSelectors/TokenPicker.tsx
- bridge_ui/src/utils/consts.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/1258)
> bridge_ui: Block transfers of aUSD from Karura

- sdk/js/CHANGELOG.md
- sdk/js/package.json
- sdk/js/src/utils/consts.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/1265)
> sdk/js: add neon testnet

- algorand/runPythonUnitTests.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/1275)
> algoFix: Algod fix so that the PRs pass

- bridge_ui/src/utils/consts.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/1276)
> bridge_ui: remove celo from beta

- node/pkg/vaa/structs.go
- node/pkg/vaa/structs_test.go
Change-Id: I23136807e5101ae823e9d198ac52d3446a94b0f2
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/1232)
> Guardian parse transfer VAA payload

- sdk/js/src/token_bridge/attest.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/1287)
> const is shadowing creator variable for algorand attestation

- devnet/node.yaml
- node/cmd/guardiand/adminnodes.go
- node/cmd/guardiand/node.go
- node/hack/repair_terra/repair.go
- node/pkg/common/readiness.go
- node/pkg/terra/watcher.go
- node/pkg/vaa/structs.go
- node/pkg/vaa/structs_test.go
- proto/publicrpc/v1/publicrpc.proto
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/1282)
> node: terra2 support

- algorand/admin.py
- algorand/test/test.py
- algorand/token_bridge.py
- sdk/js/src/algorand/Algorand.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/1223)
> payload3_xl: add payload3 sender

- node/pkg/common/mainnet_consts.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/1293)
> Add emitter type to guardian mainnet consts

- node/pkg/supervisor/UPSTREAM.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/1251)
> node/pkg/supervisor: document upstream repository

- ethereum/contracts/bridge/Bridge.sol
- ethereum/contracts/bridge/BridgeStructs.sol
- ethereum/contracts/bridge/mock/MockTokenBridgeIntegration.sol
- ethereum/test/bridge.js
- sdk/js/src/token_bridge/transfer.ts
- whitepapers/0003_token_bridge.md
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/1222)
> ethereum: Add fromAddress to payload 3

- node/cmd/guardiand/adminnodes.go
- node/cmd/guardiand/node.go
- node/hack/repair_terra/repair.go
- node/pkg/common/mainnet_consts.go
- node/pkg/processor/processor.go
- relayer/spy_relayer/config/mainnet/emitterAddresses.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/1296)
> Terra2 Mainnet Guardian Changes

- bridge_ui/package-lock.json
- bridge_ui/package.json
- bridge_ui/src/utils/consts.ts
- clients/js/package-lock.json
- clients/js/package.json
- sdk/js/CHANGELOG.md
- sdk/js/package.json
- sdk/js/src/utils/consts.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/1297)
> Terra2 sdk mainnet

- cosmwasm/contracts/token-bridge/src/state.rs
- cosmwasm/test/src/__tests__/bridge.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/1299)
> cosmwasm: fix sequence number in storage

- clients/js/networks.ts
- ethereum/1conf.patch
- ethereum/truffle-config.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/1298)
> Fix truffle-config and 1conf patch

- node/pkg/celo/celoimpl.go
- node/pkg/ethereum/ethimpl.go
- node/pkg/ethereum/getlogsimpl.go
- node/pkg/ethereum/watcher.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/1300)
> Guardian eth nil event check

- bridge_ui/src/components/Recovery.tsx
- bridge_ui/src/hooks/useFetchTargetAsset.ts
- bridge_ui/src/hooks/useOriginalAsset.ts
- bridge_ui/src/utils/terra.ts
- ethereum/scripts/deploy_test_token.js
- sdk/js/src/token_bridge/__tests__/consts.ts
- sdk/js/src/token_bridge/__tests__/helpers.ts
- sdk/js/src/token_bridge/__tests__/integration.ts
- sdk/js/src/token_bridge/__tests__/terra2-integration.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/1303)
> Terra2 UI fixes

- bridge_ui/package-lock.json
- bridge_ui/package.json
- sdk/js/CHANGELOG.md
- sdk/js/package.json
- sdk/js/src/utils/array.test.ts
- sdk/js/src/utils/array.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/1306)
> sdk/js: fix converting native terra2 20-byte addrs

- bridge_ui/src/utils/consts.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/1305)
> bridge_ui: remove acala and terra2 from beta

- ethereum/karura-gas-prices
- ethereum/truffle-config.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/1209)
> Add script to query karura gas prices

- .gitignore
- solana/bridge/program/src/api/governance.rs
- solana/bridge/program/src/instructions.rs
- solana/bridge/program/tests/integration.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/1310)
> solana: transfer fees fix

- node/pkg/solana/client.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/1312)
> node: Allow "msu" in node

- algorand/token_bridge.py
Make algorand more compossible
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/1311)
> algoOptin: optin change

- sdk/js/src/token_bridge/transfer.ts
- solana/Makefile
- solana/modules/token_bridge/program/src/api.rs
- solana/modules/token_bridge/program/src/api/complete_transfer_payload.rs
- solana/modules/token_bridge/program/src/api/transfer_payload.rs
- solana/modules/token_bridge/program/src/instructions.rs
- solana/modules/token_bridge/program/src/messages.rs
- solana/modules/token_bridge/program/src/wasm.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/1279)
> solana: Add "msg.sender" and remove fee from payload3

- bridge_ui/src/components/TokenSelectors/TokenPicker.tsx
- bridge_ui/src/utils/consts.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/1335)
> bridge_ui: disable aUSD transfers from acala to karura

- SECURITY.md
Adds the latest audit report from Kudelski
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/1336)
> Add Kudelski Security Audit Report

- solana/verify
It expected the NETWORK environment variable to be set, which it no longer does.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/1340)
> solana: fix network handling in verify script

- algorand/sandbox-algorand/images/indexer/start.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/1342)
> added arg to algorand startup

- ethereum/scripts/deploy_test_token.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/1341)
> devnet: Fix WETH token address

- .github/workflows/guardiand-docker.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/1347)
> CI: build&publish latest guardiand docker image from dev.v2

- node/pkg/db/db.go
- node/pkg/db/db_test.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/1062)
> Add unit tests for db

- ethereum/truffle-config.js
Also rename chains to be in line with the naming convention used elsewhere
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/1346)
> ethereum: Update truffle config to most recent deploy params

- .github/workflows/build.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/1348)
> Pin build foundry

- solana/modules/token_bridge/program/src/messages.rs
- solana/modules/token_bridge/program/tests/common.rs
- solana/modules/token_bridge/program/tests/integration.rs
fix solana payload3 deserialization and add rust integration & unit tests
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/1354)
> fix solana payload3 deserialization 

- solana/verify
Had a stale reference to the account dump file
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/1356)
> solana: Fix verify script

- node/cmd/guardiand/node.go
- node/pkg/common/readiness.go
- node/pkg/solana/client.go
- node/pkg/vaa/structs.go
- proto/publicrpc/v1/publicrpc.proto
- sdk/js/CHANGELOG.md
- sdk/js/src/utils/array.ts
- sdk/js/src/utils/consts.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/1380)
> node: pythnet testnet support

- SECURITY.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/1393)
> Correct date in SECURITY.md

- .github/workflows/build.yml
- ethereum/anvil_fork
- ethereum/simulate_upgrade
- ethereum/simulate_upgrades
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/1392)
> CI: use working docker image for anvil in upgrade simulation testing

- sdk/js/src/token_bridge/__tests__/consts.ts
- sdk/js/src/token_bridge/__tests__/terra2-integration.ts
- terra/contracts/token-bridge/src/contract.rs
when a native denom is received (complete transfer native),
check if the token chain is terra classic
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/1389)
> fix terra classic native token parsing

- sdk/js/src/utils/consts.ts
- solana/bridge/program/src/api/governance.rs
- solana/bridge/program/src/instructions.rs
- solana/bridge/program/src/lib.rs
Will commit the cli changes once these SDK changes are merged.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/1388)
> Pythnet mainnet deploy

- node/pkg/governor/governor_monitoring.go
- node/pkg/publicrpc/publicrpcserver.go
- proto/publicrpc/v1/publicrpc.proto
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/1395)
> Add is_enqueued_vaa query to governor

- .github/workflows/build.yml
<a href="https://github.com/actions/checkout/issues/354">https://github.com/actions/checkout/issues/354</a>
**Issue references**: 
- https://github.com/actions/checkout/issues/354
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/1413)
> .github/workflows: clean workspace on self-hosted runners

- bridge_ui/src/utils/consts.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/1415)
> bridge_ui: Removed Klaytn from beta

- devnet/node.yaml
- node/pkg/db/governor.go
- node/pkg/governor/devnet_config.go
- node/pkg/governor/governor.go
- node/pkg/governor/governor_monitoring.go
- node/pkg/governor/governor_prices.go
- node/pkg/governor/governor_test.go
- node/pkg/governor/testnet_config.go
- node/pkg/p2p/p2p.go
- proto/gossip/v1/gossip.proto
Change-Id: I0ae094b16a8e0469f83f711e7118936abf70b109
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/1404)
> More governor code review rework

- node/pkg/near/watcher.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/1407)
> near/backwards: RPC jumping causes us to think the chain went backwards

- docs/governor.md
- node/GOVERNOR.md
Opening PR describing the types of admin commands that Guardians would have in relation to the Governor security module.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/1416)
> Governor Guardian admin commands

- node/pkg/governor/mainnet_chains.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/1419)
> Should not govern algorand yet

- terra/Makefile
- terra/contracts/token-bridge/src/contract.rs
- terra/tools/deploy_single.js
See comments in the code for more context.
The upgrade has been tried locally and denying the previous upgrade VAA works as expected.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/1420)
> Terra classic migration attempt 2

- sdk/js-proto-node/package-lock.json
- sdk/js-proto-node/package.json
- sdk/js-proto-web/package-lock.json
- sdk/js-proto-web/package.json
- sdk/js/CHANGELOG.md
- sdk/js/package-lock.json
- sdk/js/package.json
- sdk/js/src/rpc/getGovernorIsVAAEnqueued.ts
- sdk/js/src/rpc/getGovernorIsVAAEnqueuedWithRetry.ts
- sdk/js/src/rpc/index.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/1410)
> sdk/js: Added getGovernorIsVAAEnqueued functions

- CONTRIBUTING.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/1424)
> Switch terra2 to coswasm

- bridge_ui/src/hooks/useGetSourceParsedTokenAccounts.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/1242)
> Algo filter NFT from token selection

- docs/governor.md
- whitepapers/0007_governor.md
Also include a link to the whitepaper from the docs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/1426)
> docs: Clarify objective in governor whitepaper

- algorand/admin.py
- algorand/runPythonUnitTests.sh
- algorand/teal/core_approve.teal
- algorand/teal/token_approve.teal
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/1427)
> algo/prod: prod changes for going live

- Tiltfile
- bridge_ui/package-lock.json
- bridge_ui/package.json
- bridge_ui/src/components/Recovery.tsx
- bridge_ui/src/components/Transfer/PendingVAAWarning.tsx
- bridge_ui/src/components/Transfer/Send.tsx
- bridge_ui/src/components/Transfer/Source.tsx
- bridge_ui/src/components/Transfer/TransferLimitedWarning.tsx
- bridge_ui/src/hooks/useHandleAttest.tsx
- bridge_ui/src/hooks/useHandleNFTTransfer.tsx
- bridge_ui/src/hooks/useHandleTransfer.tsx
- bridge_ui/src/hooks/useIsTransferLimited.ts
- bridge_ui/src/store/selectors.ts
- bridge_ui/src/store/transferSlice.ts
- bridge_ui/src/utils/consts.ts
- bridge_ui/src/utils/getSignedVAAWithRetry.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/1421)
> bridge_ui: Chain Governor support

- algorand/admin.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/1431)
> algo/upgrade: testing upgrades for algorand

- algorand/teal/token_approve.teal
- algorand/token_bridge.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/1439)
> algo/reserve: fix reserve field

- sdk/js/src/utils/consts.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/1440)
> Algorand redeploy (new contract addresses)

- relayer/plugin_relayer/design.md
- relayer/plugin_relayer/relayer_base/pluginInterface.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/1446)
> Design Day 2: scheduling, async/sync actions, config, more types

- clients/js/main.ts
- clients/js/near.ts
- clients/js/networks.ts
- clients/js/package-lock.json
- clients/js/package.json
- clients/js/solana.ts
The original CLI PR #1423 is being broken up into smaller PRs. This PR contains the Near piece, along with the pythnet and wormholechain config pieces.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/1442)
> clients/js - initial near commit

- bridge_ui/package-lock.json
- bridge_ui/package.json
- bridge_ui/src/utils/consts.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/1433)
> bridge_ui: Algorand beta

- clients/js/algorand.ts
- clients/js/main.ts
- clients/js/networks.ts
- clients/js/package-lock.json
- clients/js/package.json
This PR adds algorand functionality to the client.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/1445)
> clients/js - initial algorand commit

- ethereum/contracts/Messages.sol
- ethereum/forge-test/Messages.t.sol
Add a property test (a.k.a. fuzz test) to serve as an example on how to write them
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/1428)
> ethereum: property test quorum

- ethereum/contracts/bridge/Bridge.sol
- ethereum/forge-test/Bridge.t.sol
Some additional sanity checking can't hurt
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/1457)
> ethereum: Check that bytes32 fits into 20 bytes before truncating

- terra/contracts/token-bridge/src/contract.rs
- terra/contracts/wormhole/src/byte_utils.rs
- terra/contracts/wormhole/src/testing/tests.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/1458)
> terra: Check that bytes32 fits into 20 bytes before truncating

- algorand/admin.py
- algorand/token_bridge.py
- algorand/wormhole_core.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/1454)
> algo/patch: wormhole security patches for algorand

- algorand/token_bridge.py
- algorand/wormhole_core.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/1460)
> algo/patch2: optins cannot have arguments

- node/pkg/p2p/p2p.go
Configure the bootstrapping nodes that we will connect to to seed and refresh
the Routing Table if it becomes empty.
Fixes an issue where the spy stops receiving gossiped messages after the node
is restarted, because the Routing Table becomes empty and is never refreshed.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/1455)
> node: configure p2p routing table with bootstrapping nodes

- aptos/contracts/sources/Governance.move
- aptos/contracts/sources/VAA.move
Also cleaned up the `GuardianSetUpgrade` checks a little bit
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/1472)
> aptos: VAA verification failure should revert

- .github/ISSUE_TEMPLATE/wormhole-issue-template.md
- .github/workflows/guardiand-docker.yml
- .github/workflows/relayer-docker.yml
- .spr.yml
- CONTRIBUTING.md
- DEVELOP.md
- Dockerfile.client
- SECURITY.md
- algorand/MEMORY.md
- algorand/test/testlib.ts
- buf.yaml
- docs/assumptions.md
- docs/operations.md
- generate-abi-celo.sh
- generate-abi.sh
- near/Docker.md
- near/Dockerfile
- near/test/testlib.ts
- relayer/spy_relayer/Dockerfile
- relayer/spy_relayer/README.md
- sdk/js/README.md
- sdk/js/src/algorand/testlib.ts
- solana/DOCKER.md
- solana/Dockerfile
- spydk/js/README.md
- testing/contract-integrations/src/consts.ts
- whitepapers/0001_generic_message_passing.md
- whitepapers/0005_data_availability.md
Everything except for the guardiand node and golang code.
> certusone -> wormhole-foundation

- aptos/Makefile
- aptos/contracts/Makefile
- aptos/contracts/Move.toml
- aptos/contracts/sources/contract_upgrade.move
- aptos/contracts/sources/cursor.move
- aptos/contracts/sources/deserialize.move
- aptos/contracts/sources/guardian_pubkey.move
- aptos/contracts/sources/guardian_set_upgrade.move
- aptos/contracts/sources/serialize.move
- aptos/contracts/sources/state.move
- aptos/contracts/sources/structs.move
- aptos/contracts/sources/u32.move
- aptos/contracts/sources/vaa.move
- aptos/contracts/sources/wormhole.move
- aptos/deployer/Makefile
- aptos/deployer/Move.toml
- aptos/deployer/sources/deployer.move
- aptos/scripts/README.md
- aptos/scripts/deploy.ts
- aptos/scripts/init_wormhole.ts
- aptos/scripts/publish_wormhole_message.ts
- aptos/scripts/upgrade.ts
- clients/js/Makefile
- clients/js/aptos.ts
- clients/js/main.ts
- clients/js/networks.ts
- clients/js/package-lock.json
- clients/js/package.json
- clients/js/vaa.ts
- sdk/js/src/utils/consts.ts
Requires https://github.com/aptos-labs/aptos-core/pull/3568 as we need the package metadata for on-chain publishing. Then compilation will need to be run with
```shell
aptos move compile --save-metadata
```
> aptos: upgradeability

- node/pkg/governor/mainnet_chains.go
> Update  dailyLimit / bigTransactionSize

- node/cmd/guardiand/adminnodes.go
Thanks @maiquanghiep
Reported-By: `Quang-Hiep Mai <maiquanghiepdl@gmail.com>`
> Fix guardiand admin list nodes for pythnet

- relayer/spy_relayer/README.md
> node: docs for running a spy against mainnet

- aptos/Dockerfile
- aptos/Makefile
- aptos/README.md
- aptos/contracts/sources/contract_upgrade.move
- aptos/contracts/sources/emitter.move
- aptos/contracts/sources/guardian_set_upgrade.move
- aptos/contracts/sources/state.move
- aptos/contracts/sources/structs.move
- aptos/contracts/sources/u16.move
- aptos/contracts/sources/vaa.move
- aptos/contracts/sources/wormhole.move
- aptos/deployer/sources/deployer.move
- aptos/examples/Makefile
- aptos/examples/core_messages/Makefile
- aptos/examples/core_messages/Move.toml
- aptos/examples/core_messages/sources/sender.move
- aptos/scripts/deploy
- aptos/scripts/publish_wormhole_message.ts
> aptos: finish core bridge

- ethereum/contracts/Messages.sol
- node/pkg/vaa/structs.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/1401)
> comment danger of potential future VM.version increases

- aptos/token_bridge/sources/bridge_implementation.move
- aptos/token_bridge/sources/bridge_state.move
- aptos/token_bridge/sources/token_bridge.move
- aptos/wormhole/sources/serialize.move
Clean up mappings between 32-byte-address, origin_info, and type_info
- origin_info_to_wrapped_assets
- wrapped_assets_to_origin_info
- assets_to_type_info
> aptos: Bridge State Mappings and Tests for Attest Token and Serialize.move

- clients/js/main.ts
adds a command to generate token attestation VAAs. For example:
```
worm generate attestation -c ethereum -a 0xbeefface -d 12 -s BEEF -n "Beef face Token" -e ethereum -f 0x00000000000000000000000000000000000000000000000000000000deadbeef -g cfb12303a19cde580bb4dd771639b0d26bc68353645571a8cff516ab2ee113a0
```
> clients/js: generate attestation VAA

- aptos/README.md
- aptos/scripts/README.md
- aptos/scripts/deploy
- aptos/wormhole/sources/emitter.move
There's more to come, but this is a start
> aptos: Describe capabilities in README.md

- aptos/wormhole/sources/serialize.move
> aptos/wormhole: Simplify serialisation module

- algorand/sandbox-algorand/images/algod/Dockerfile
- algorand/sandbox-algorand/images/indexer/Dockerfile
- algorand/sandbox-algorand/images/indexer/install.sh
- near/contracts/ft/src/lib.rs
- near/contracts/token-bridge/src/lib.rs
- near/test/sdk.ts
near/testing: improve near tests for decimal point shifts
force algorand and indexer to update to what we are about to run in production
add checks for fees being passed for P3 messages
> near/testing: improve near tests for decimal point shifts

- docs/governor.md
- whitepapers/0007_governor.md
reflect new governor auto-release enqueued messages feature
> docs: governor update

- aptos/Docker.md
- aptos/Dockerfile
- aptos/Dockerfile.base
- aptos/README.md
- aptos/coin/Move.toml
- aptos/deployer/Move.toml
- aptos/token_bridge/Move.toml
- aptos/wormhole/Move.toml
> aptos: Use latest stdlib & aptos cli

- aptos/scripts/faucet
- clients/js/cmds/aptos.ts
add support for faucet command with rpc, account, faucet_url as args
> aptos: worm cli faucet

- node/pkg/processor/cleanup.go
When processing pending observations, the `handleCleanup` function
checks if we already have a stored quorum VAA and deletes the in-memory
observation if one is found.  If a stored quorum VAA is not found, then
we're supposed to continue evaluating the other conditions and take
the appropriate action.  This was implemented using a `fallthrough`
statement.
Unfortunately, this is not how `fallthrough` works.  `fallthrough`
simply tells the compiler to execute the body of the next branch in
the switch block, *without evaluating the condition*.  It also doesn't
evaluate the conditions for any of the other branches in the switch.
In practice what this meant is that for local observations that didn't
have quorum we would always take the first branch, fall through to the
second branch, and then …
> node: processor: Fix incorrect fallthrough in `handleCleanup`

- clients/js/networks.ts
- sdk/js/package-lock.json
- sdk/js/package.json
- sdk/js/src/algorand/__tests__/testHelpers.ts
- sdk/js/src/bridge/getEmitterAddress.ts
- sdk/js/src/bridge/parseSequenceFromLog.ts
- sdk/js/src/cosmwasm/address.ts
- sdk/js/src/cosmwasm/index.ts
- sdk/js/src/cosmwasm/query.testnet.test.ts
- sdk/js/src/token_bridge/attest.testnet.test.ts
- sdk/js/src/token_bridge/attest.ts
- sdk/js/src/token_bridge/createWrapped.ts
- sdk/js/src/token_bridge/getForeignAsset.ts
- sdk/js/src/token_bridge/getIsTransferCompleted.ts
- sdk/js/src/token_bridge/getIsWrappedAsset.ts
- sdk/js/src/token_bridge/getOriginalAsset.ts
- sdk/js/src/token_bridge/redeem.ts
- sdk/js/src/token_bridge/transfer.ts
- sdk/js/src/token_bridge/updateWrapped.ts
- sdk/js/src/utils/array.test.ts
- sdk/js/src/utils/array.ts
- sdk/js/src/utils/consts.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/1396)
> Injective sdk

- aptos/scripts/deploy_testnet
- aptos/scripts/faucet
- aptos/token_bridge/Move_testnet.toml
- aptos/wormhole/Move_testnet.toml
- clients/js/aptos.ts
- clients/js/cmds/aptos.ts
- clients/js/main.ts
Some minor adjustments needed to redeploy on devnet.
> aptos: testnet (devnet) deploy

- algorand/package-lock.json
- algorand/package.json
- algorand/test/tvl.ts
- algorand/token_bridge.py
- near/test/sdk.ts
- sdk/js/src/bridge/parseSequenceFromLog.ts
algo/typo: type fix, algorand tests, near tests
> algo/typo: Fix a typo and a round-off

- terra/contracts/token-bridge/src/contract.rs
- terra/contracts/token-bridge/src/msg.rs
- terra/contracts/token-bridge/src/state.rs
- terra/contracts/token-bridge/src/testing/tests.rs
- terra/test/src/__tests__/bridge.ts
backport of #1292 for terra classic
> terra: Add fromAddress to payload 3

- sdk/js/CHANGELOG.md
- sdk/js/package-lock.json
- sdk/js/package.json
- sdk/js/src/utils/consts.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/certusone/wormhole/1451)
> sdk/js: 0.7.0 version bump

- clients/js/terra.ts
This script didn't work properly after "stability fees" were enabled.
> clients/js: fix terra fee

- node/cmd/guardiand/adminnodes.go
- node/cmd/guardiand/node.go
- node/pkg/common/readiness.go
- sdk/js/src/utils/array.ts
- sdk/js/src/utils/consts.ts
- sdk/vaa/structs.go
- sdk/vaa/structs_test.go
This adds watcher capability to the guardian for XPLA
> node: XPLA watcher

- node/cmd/guardiand/node.go
- node/pkg/db/governor.go
- node/pkg/db/governor_test.go
- node/pkg/governor/governor.go
- node/pkg/governor/governor_db.go
- node/pkg/governor/governor_test.go
- node/pkg/processor/observation.go
- node/pkg/processor/observation_test.go
- node/pkg/processor/processor.go
Reverts wormhole-foundation/wormhole#1487 until security review is complete.
> Revert "node: governor listen to quorum gossip"

- cosmwasm/contracts/wormhole/src/byte_utils.rs
You don't need multiple heap allocations just to left-pad or right-pad a buffer.  Also add tests.
> cosmwasm: byte_utils: Clean up padding functions

- Tiltfile
Fixes https://github.com/wormhole-foundation/wormhole/issues/1685
> Tiltfile - add "spy" resource_dep to fix race condition

- clients/js/networks.ts
Also bump the sdk version to pick up new testnet contracts.
> Update client/js for Near testnet

- aptos/coin/sources/Coin.move
- aptos/examples/core_messages/Move.toml
- aptos/token_bridge/Move.toml
- aptos/token_bridge/sources/token_hash.move
- aptos/token_bridge/sources/wrapped.move
- aptos/wormhole/Move.toml
- aptos/wormhole/sources/wormhole.move
- clients/js/aptos.ts
- clients/js/main.ts
- sdk/js/src/utils/consts.ts
this is a recent breaking change in the aptos framework, which we have to adapt to
> aptos: use new resource account derivation logic

- node/pkg/watchers/aptos/watcher.go
Address minor stylistic nits and supervisor usage. Supervisor is not supposed to generally spawn goroutines for it's main worker loop but either spawn new runnables or run the loop in the runnable thread.
I'm already sorry for github not properly rendering the diff.
> node: minor refactoring of aptos watcher

- sui/wormhole/Move.toml
- sui/wormhole/sources/guardian_pubkey.move
- sui/wormhole/sources/keccack256.move
> sui: upgrade stdlib

- node/cmd/guardiand/node.go
- node/cmd/spy/spy.go
- node/pkg/p2p/p2p.go
Trying to do something with the gov cfg & status msgs instead of throwing them in the trash.
> node: Added gov gossip support to p2p

- clients/js/Makefile
- clients/js/algorand.ts
- clients/js/aptos.ts
- clients/js/cmds/aptos.ts
- clients/js/evm.ts
- clients/js/injective.ts
- clients/js/main.ts
- clients/js/near.ts
- clients/js/networks.ts
- clients/js/package-lock.json
- clients/js/solana.ts
- clients/js/terra.ts
- clients/js/xpla.ts
the startup time is now ~300ms (from 2-3s before), which is a lot more acceptable
> worm: speedup

- node/cmd/guardiand/node.go
- node/pkg/watchers/algorand/watcher.go
the diff leaves something to be desired here
> algorand/watcher: Modernize algorand watcher and improve logging

- sdk/js/CHANGELOG.md
- sdk/js/package.json
- sdk/js/src/aptos/api/tokenBridge.ts
- sdk/js/src/token_bridge/__tests__/aptos-integration.ts
- sdk/js/src/token_bridge/attest.ts
- sdk/js/src/token_bridge/createWrapped.ts
- sdk/js/src/token_bridge/getForeignAsset.ts
- sdk/js/src/token_bridge/getIsTransferCompleted.ts
- sdk/js/src/token_bridge/getIsWrappedAsset.ts
- sdk/js/src/token_bridge/getOriginalAsset.ts
- sdk/js/src/token_bridge/redeem.ts
- sdk/js/src/token_bridge/transfer.ts
- sdk/js/src/utils/aptos.ts
- Added documentation to Aptos SDK: docstrings + surfacing some design decisions
- Minor API changes (use fully qualified types instead of module addresses where it makes sense)
> Aptos SDK documentation

- clients/js/package-lock.json
- clients/js/package.json
Like the commit says, resolving some audit warnings. Supersedes #1659 #1449 #1463
> clients/js: npm audit fix --force

- node/pkg/common/chainlock.go
- node/pkg/db/governor.go
- node/pkg/db/governor_test.go
- node/pkg/governor/governor.go
- node/pkg/governor/governor_db.go
- node/pkg/governor/governor_test.go
This implements this github issue: https://github.com/wormhole-foundation/wormhole/issues/1757
> Node: governor not handling duplicates properly

- Dockerfile.const
- clients/js/main.ts
Change-Id: Ib066b21f3c73e3165015d5eddf6b224c26d76cf1
> client/js: Fix emitter lookup for cosmwasm

- sui/token_bridge/sources/attest_token.move
- sui/token_bridge/sources/bridge_state.move
- sui/token_bridge/sources/complete_transfer.move
- sui/token_bridge/sources/transfer_tokens.move
- sui/token_bridge/sources/treasury.move
- sui/token_bridge/sources/vaa.move
- sui/token_bridge/sources/wrapped.move
- sui/wormhole/Move.toml
- sui/wormhole/sources/external_address.move
- sui/wormhole/sources/wormhole.move
- treasury and token bridge `deposit` and `withdraw` (use dynamic fields under the hood)
- implement token bridge `complete_transfer`
- mock out `attest_token` and `transfer_token`
- `init` and `init_and_share` token bridge
> Sui: complete transfer, init bridge, mock functions

- clients/js/aptos.ts
- clients/js/cmds/aptos.ts
- clients/js/networks.ts
This PR fixes the client support for Aptos mainnet.
> clients/js: add aptos network info

- sui/Docker.md
- sui/Dockerfile
- sui/Dockerfile.export
- sui/NOTES.md
- sui/scripts/node_builder.sh
- sui/scripts/start_node.sh
- sui/wormhole/Move.toml
WH-1854: bump to 0.14.0 @ Closes #1854
> WH-1854: bump to 0.14.0 @ Closes #1854

- cosmwasm/contracts/token-bridge/src/contract.rs
- cosmwasm/contracts/token-bridge/src/msg.rs
- cosmwasm/test/src/__tests__/bridge.ts
Add a query to get the registered emitterr address for a given chain id.
This will be used by accounting.
> cosmwasm: tokenbridge: Add chain registration query

- clients/js/main.ts
Needed to upgrade the injective testnet contract
> clients/js: parseCodeAddress should handle CosmWasm chains

- sdk/vaa/structs.go
- sdk/vaa/structs_test.go
Change-Id: Ic86d9ff02c8ab486e8fae077f21c833de156a9d8
> Node: Add Optimism chainID

- node/pkg/reporter/attestation_events.go
This PR addresses issue #1888.
> Node: Increase bigtable writer channel size

- aptos/scripts/wait_for_devnet
- devnet/aptos-localnet.yaml
- sdk/js/src/token_bridge/__tests__/aptos-integration.ts
- sdk/js/src/token_bridge/__tests__/consts.ts
- sdk/js/src/token_bridge/__tests__/terra2-integration.ts
In support of moving to new runners, I had to run the tests a bunch of times on slightly slower machines and ran into these flaky test frustrations. After this is merged, the new runner can be put into circulation.
> ci test improvements

- node/cmd/guardiand/node.go
Simple change to make it easier to test in dev while pointing at testnet chains.
Change-Id: Ieca0f5d2765ee55b716bc4015900fd52f79d1dfe
> Node: Simplify unsafeDevMode testing

- ethereum/contracts/Implementation.sol
- ethereum/contracts/bridge/BridgeImplementation.sol
- ethereum/contracts/nft/NFTBridgeImplementation.sol
These migrations have been performed, so the migration code can now safely be removed.
> ethereum: Remove initialisation code

- wormchain/README.md
- wormchain/mainnet/config.toml
- wormchain/mainnet/genesis.json
This is the genesis and initial network configuration guardians may use to join the network.  We will update the `persistent_peers` later after more guardians have joined.
I'd like to host this in the repo for people to download easily.
> initial wormchain mainnet information

- .github/workflows/build.yml
- Tiltfile
- scripts/check-docker-pin.sh
- sui/Dockerfile
> Run sui tests in CI

- ethereum/contracts/Setup.sol
- ethereum/contracts/bridge/BridgeSetup.sol
- ethereum/contracts/nft/NFTBridgeSetup.sol
See #1930 for more context on this change.
One small step for man, one giant leap for the bug bountry program.
> ethereum: Set impl initialised during setup

- node/pkg/governor/governor_monitoring.go
> node: gov: separate governor config and status message prefix

- sui/token_bridge/sources/bridge_state.move
- sui/token_bridge/sources/complete_transfer.move
This PR fixes two issues in the sui token bridge `complete_transfer` function. Both of these fixes are lifted from the aptos contract, with small modifications.
1. Properly pays the fee recipient.
2. Fixes a critical security bug where the `CoinType` was not verified to match the information in the VAA.
Since 2. is a critical safety check, and we have yet to implement `complete_transfer_with_payload` which will require the same check, I decided to introduce a foolproof mechanism that guarantees that this check is performed. `mint` and `withdraw` now require a witness that ensures that `CoinType` has been verified. See the documentation for `VerifiedCoinType`.
> sui/token_bridge: fix complete_transfer

- cosmwasm/verify
- scripts/contract-upgrade-governance.sh
This PR updates the cosmwasm verify script to handle terra, terra2, injective, and xpla
Fixes #1878
> cosmwasm: update verify script

- cosmwasm/Cargo.lock
- cosmwasm/Cargo.toml
- cosmwasm/Dockerfile
- cosmwasm/packages/wormhole-bindings/Cargo.toml
- cosmwasm/packages/wormhole-bindings/schema/wormhole_query.json
- cosmwasm/packages/wormhole-bindings/src/lib.rs
- cosmwasm/packages/wormhole-bindings/src/query.rs
This package defines the bindings into the native wormhole module on
wormchain.
> cosmwasm: Add wormhole-bindings package

- .github/ISSUE_TEMPLATE/wormhole-issue-template.md
- .github/workflows/build.yml
- .github/workflows/guardiand-docker.yml
- .spr.yml
- CONTRIBUTING.md
- SECURITY.md
- algorand/test/testlib.ts
- aptos/README.md
- near/test/testlib.ts
- node/pkg/readiness/health.go
- relayer/spy_relayer/Dockerfile
- relayer/spy_relayer/docker-compose.yml
- sdk/js-proto-node/package.json
- sdk/js-proto-web/package.json
- sdk/js-wasm/package.json
- sdk/js/README.md
- sdk/js/package.json
- sdk/js/src/algorand/testlib.ts
- sdk/js/src/solana/nftBridge/coder/instruction.ts
- sdk/js/src/solana/tokenBridge/coder/instruction.ts
- sdk/js/src/solana/wormhole/coder/instruction.ts
- sdk/js/src/solana/wormhole/instructions/postVaa.ts
- sdk/js/src/solana/wormhole/instructions/verifySignature.ts
- spydk/js/README.md
- spydk/js/package.json
- whitepapers/0007_governor.md
- whitepapers/0008_batch_messaging.md
Change-Id: Idfc6f88de7ee3c190a01c2196dc0bc4da91cbe4c
> Rename dev.v2 to main

- near/test/sdk.ts
- near/tsconfig.json
WH-2023: light weight near sdk tests needed resolveJsonModule @ Closes #2023
> WH-2023: light weight near sdk tests needed resolveJsonModule

- cosmwasm/Cargo.lock
- cosmwasm/Cargo.toml
- cosmwasm/packages/accounting/Cargo.toml
- cosmwasm/packages/accounting/src/contract.rs
- cosmwasm/packages/accounting/src/lib.rs
- cosmwasm/packages/accounting/src/msg.rs
- cosmwasm/packages/accounting/src/state.rs
- cosmwasm/packages/accounting/src/state/account.rs
- cosmwasm/packages/accounting/src/state/addr.rs
- cosmwasm/packages/accounting/src/state/transfer.rs
The accounting package implements the reusable, chain agnostic part of
tokenbridge accounting.
Part of #1880
> cosmwasm: Add core accounting package

- sdk/js/.prettierrc.json
This is the same config used in the example UI https://github.com/wormhole-foundation/example-token-bridge-ui/blob/main/.prettierrc.json.
> sdk/js: Added .prettierrc.json file

- .github/CODEOWNERS
Ensure that all code is covered by appropriate code owners
> codeowners: full coverage

- clients/js/networks.ts
Change-Id: Icb91807bd3b9c38407246a3ce6df6180f4f87924
> Client: Use testnet key for terra2

- node/cmd/guardiand/node.go
- node/pkg/watchers/evm/finalizers/optimism.go
- node/pkg/watchers/evm/finalizers/optimismctcabi/ctc.go
- node/pkg/watchers/evm/watcher.go
> Optimism finality

- node/pkg/watchers/evm/connectors/polygon.go
Change-Id: I31305812cc784845aa98497ada24b2a2041cad71
> Node: Polygon checkpoint logging

- sui/token_bridge/sources/bridge_state.move
- sui/token_bridge/sources/testing/native_coin.move
- sui/token_bridge/sources/wrapped.move
- use coin metadata
- get tests to pass
> sui: use coin metadata

- sui/wormhole/sources/myvaa.move
- vaa tests for wormhole core bridge ported from Aptos
> sui: wormhole core bridge VAA tests

- node/pkg/governor/mainnet_chains.go
See discussion: https://github.com/wormhole-foundation/wormhole/discussions/2087
> node: Terra Classic Governor Limits Change

- wormchain/go.mod
- wormchain/go.sum
- wormchain/mainnet/genesis.json
Relevant cosmos-sdk change:
https://github.com/wormhole-foundation/cosmos-sdk/pull/156
> Wormchain re-genesis

- cosmwasm/Cargo.lock
- sdk/rust/Cargo.lock
- sdk/rust/core/Cargo.toml
- sdk/rust/core/src/chain.rs
- sdk/rust/core/src/core.rs
- sdk/rust/core/src/lib.rs
- sdk/rust/serde_wormhole/src/lib.rs
This PR addresses comments on #1919 that were added after the PR was merged.
> Rust SDK cleanup

- SECURITY.md
Draft until pdf is uploaded to GCS.
> SECURITY.md: Add Zellic Aptos Audit Report

- ethereum/contracts/Messages.sol
- ethereum/forge-test/Messages.t.sol
Reopening #1897 by @Rassska which got auto closed (and couldn't be reopened) when I pushed the wrong branch to the remote.
> add: safety check against signatory being address(0)

- terra/contracts/cw721-base/README.md
> Fix: minor typo

- clients/js/injective.ts
- clients/js/networks.ts
This PR adds support for submitting injective mainnet VAAs from the client.
> clients/js: handle injective mainnet

- .github/workflows/build.yml
Testing for impoveded consistency / reduced flakiness
> CI: split lint-and-tests

- cosmwasm/packages/accountant/src/contract.rs
While sending tokens to another address on the same chain via wormhole
is quite inefficient, it's not strictly disallowed and we do have some
VAAs on solana that do this.  Explicitly check for this case and allow
it.
There are no restrictions on native tokens sent in this way but wrapped
transfers are still subject to some checks: the wrapped account for
the token must exist and it must have a balance larger than the amount
being transferred.  If either of those checks fails then that means
that the sender acquired some wrapped tokens that did not go through
the accountant and so that transfer should be blocked and require manual
intervention.
> cosmwasm: accountant: Allow transfers on the same chain

- wormchain/contracts/tools/.npmrc
- wormchain/contracts/tools/package-lock.json
- wormchain/contracts/tools/package.json
- wormchain/contracts/tools/tsconfig.json
Setup the contract deploy scaffolding, so that in the next PR the environment varibles and devnet-consts can be configured.
Made this its own PR so that each PR in the stack only has one CODEOWNER dep.
> wormchain - contracts dir

- .gitignore
- Dockerfile.const
- Tiltfile
- scripts/devnet-consts.json
- scripts/distribute-devnet-consts.sh
- scripts/guardian-set-init.sh
- wormchain/.gitignore
- wormchain/contracts/tools/.npmrc
- wormchain/contracts/tools/package-lock.json
- wormchain/contracts/tools/package.json
- wormchain/contracts/tools/tsconfig.json
Add `wormchain/contracts/tools` to the `.env` distribution process.
Add `scripts/distribute-devnet-consts.json` to copy `devnet-consts.json`, similarly to the process for `.env`.
> wormchain - contracts env data

- ethereum/scripts/register_all_chains.js
> ethereum/scripts: reduce register script

- node/pkg/accountant/submit_obs.go
Change-Id: Idb389df44359b77de5c89ce2b15ba44705d86a3d
> Node/Acct: check for malformed response

- Tiltfile
- devnet/wormchain.yaml
Deploys wormchain contracts to devnet.
> wormchain - contracts deploy to Tilt devnet

- sui/scripts/start_node.sh
Quick PR to run Sui faucet in Tilt
> sui: run faucet in Tilt

- node/pkg/watchers/solana/client.go
It looks like the defer wasn't working as intended.
> node: Fix defer

- node/pkg/reporter/attestation_events.go
Change-Id: I93410c3dd9d8e2a2afaa76e5e2c66d2ae1a1e2ae
> Node: Increase size of channel to bigtable

- sui/Docker.md
- sui/Dockerfile
- update Docker image in [Wormhole Foundation GHCR](https://github.com/orgs/wormhole-foundation/packages/container/package/sui) to use the most up-to-date Sui 0.24.0
> sui: update to 0.24.0

- sui/README.md
- Write some docs in Sui README.md by adapting docs for Wormhole Aptos [README.md file](https://github.com/wormhole-foundation/wormhole/blob/main/aptos/README.md)
> sui: docs, README.md comments

- node/cmd/guardiand/adminserver.go
- sdk/rust/core/src/token.rs
- sdk/vaa/payloads.go
Addresses low priority comments in https://github.com/wormhole-foundation/wormhole/pull/2371
> accountant: minor cleanup

- node/pkg/watchers/near/watcher_test.go
The near watcher is running multiple threads for tx processing so results can't be exepcted to be ordered.
> node: fix near watcher tests

- clients/js/networks.ts
- clients/js/package-lock.json
- clients/js/package.json
This PR adds support for Base testnet to the client.
> Client/js: Add Base testnet support

- node/cmd/guardiand/adminserver.go
- node/cmd/guardiand/admintemplate.go
- node/cmd/guardiand/adminverify.go
- node/pkg/proto/node/v1/node.pb.go
- proto/node/v1/node.proto
- sdk/vaa/payloads.go
- sdk/vaa/payloads_test.go
This PR implements the governance actions needed for Circle Integration.
Fixes https://github.com/wormhole-foundation/wormhole-circle-integration/issues/27
Please see the above issue for a detail description of what is implemented here.
```shell
$ build/bin/guardiand template circle-integration-update-wormhole-finality --finality 42
current_set_index:  3
messages:  {
sequence:  14607295174026133158
nonce:  3776518587
circle_integration_update_wormhole_finality:  {
finality:  42
}
}
$ build/bin/guardiand template circle-integration-register-emitter-and-domain --foreign-emitter-chain-id 2 --foreign-emitter-address 0x75Bfa155a9D7A3714b0861c8a8aF0C4633c45b5D --circle-domain 12345
current_set_index:  3
messages:  {
sequence:  17227086764769013959
nonce:  3938568023 …
```
> Node: Circle Integration governance support

- sui/Dockerfile
- sui/scripts/fund_account.sh
- sui/scripts/import_default_account.sh
This PR ensures that we import the same key into Tilt consistently to create a deterministic funded account to use. Resolves #2448.
> sui: import default account to ensure deterministic key

- cosmwasm/contracts/global-accountant/src/contract.rs
- cosmwasm/contracts/global-accountant/tests/query.rs
- cosmwasm/contracts/global-accountant/tests/submit_observations.rs
- cosmwasm/contracts/global-accountant/tests/submit_vaas.rs
Fix handling Token Bridge VAAs (specifically relevant for backfilling transfers) to check against registered Token Bridge emitters. Also ensure that the registered emitter check happens as soon as possible.
> cosmwasm: acct: fix emitter requirements

- node/pkg/watchers/README.md
There is no code associated with this PR.  This only adds documentation.
Thankfully, notion has an export to MD button!😅
fixes #2541
> Add guardian watcher skeleton document

- whitepapers/0010_integrity_checkers.md
- whitepapers/0011_accountant.md
I believe these links will exist once the original PR is merged, eg:
https://github.com/wormhole-foundation/wormhole/blob/main/whitepapers/0010_integrity_checkers.md#pre-observations
> whitepapers: revise accountant whitepaper

- Dockerfile.const
- clients/js/cmds/generate.ts
- clients/js/cmds/submit.ts
- clients/js/consts.ts
- clients/js/sui/consts.ts
- clients/js/sui/utils.ts
- devnet/sui-devnet.yaml
- scripts/devnet-consts.json
- scripts/guardian-set-init.sh
- sui/Docker.md
- sui/Dockerfile
- sui/scripts/register_devnet.sh
This PR takes care of chain registrations for Sui. Resolves #2597.
> scripts: register chains for sui

- Dockerfile.const
- clients/js/cmds/generate.ts
- clients/js/cmds/submit.ts
- clients/js/consts.ts
- clients/js/sui/consts.ts
- clients/js/sui/utils.ts
- devnet/sui-devnet.yaml
- scripts/devnet-consts.json
- scripts/guardian-set-init.sh
- sui/Docker.md
- sui/Dockerfile
- sui/scripts/register_devnet.sh
- sui/scripts/start_node.sh
- sui/scripts/wait_for_devnet.sh
This PR deploys the Sui contracts to the Tilt environment when it starts up.
Resolves #2555
> sui: deploy contracts in tilt

- clients/js/package-lock.json
- clients/js/package.json
- sui/Docker.md
- sui/Dockerfile
- sui/README.md
- sui/coin/Move.devnet.toml
- sui/coin/Move.toml
- sui/examples/core_messages/Move.devnet.toml
- sui/examples/core_messages/Move.lock
- sui/examples/core_messages/Move.toml
- sui/scripts/node_builder.sh
- sui/testing/coin_wrapped_12/Move.toml
- sui/token_bridge/Move.devnet.toml
- sui/token_bridge/Move.lock
- sui/token_bridge/Move.toml
- sui/wormhole/Move.devnet.toml
- sui/wormhole/Move.lock
- sui/wormhole/Move.toml
This PR updates Sui version to 0.30.0 (and publishes a new image) and updates the corresponding Sui SDK version to 0.31.0.
> sui: update to 0.30.0

- wormchain/app/app.go
- wormchain/devnet/base/config/genesis.json
- wormchain/ibc-relayer/Dockerfile
This PR updates wormchain to include IBC functionality.
It also contains minor updates to the wormchain genesis file and the IBC relayer dockerfile.
> wormchain: updates to add ibc

- node/cmd/guardiand/node.go
This PR adds a defense-in-depth security check. 
Currently, the Guardian does not explicitly prevent messages with emitterAddress == 0. Such a message should of course be not possible by the specification of the core protocol and the implementation of the core contracts, but if there was a fault in any of the core contracts or blockchain watching process, this could lead to unintended behavior.
> node: enforce msg.EmitterAddress != 0

- node/pkg/watchers/algorand/watcher.go
This reverts commit 9b8bed4dbf168027d36ae8d1206478ad6b39e153.
Reverting this algorand watcher commit until a better solution is found.
> Revert "node/pkg/watchers: add RunWithScissors"

- .github/workflows/build.yml
Fixes `ethereum-upgrade` CI job.
> Uses `foundry-rs/foundry-toolchain@v1` github action to install foundry.

- node/pkg/watchers/sui/watcher.go
This PR updates the SUI guardian watcher to accommodate for the SUI updates.
> Sui guardian watcher

- sui/scripts/register_devnet.sh
This should speed up the setup script a little bit. Fixes #2643
> sui/scripts: register chains in parallel in devnet

- Tiltfile
- node/cmd/guardiand/node.go
- node/pkg/watchers/sui/watcher.go
- sui/scripts/register_devnet.sh
Use Type for watching, as this should not change with upgrades.
Also revert the parallel register change because it results in wallet sequence conflicts.
> Sui watcher update

- node/cmd/guardiand/adminserver.go
- node/cmd/guardiand/node.go
- node/cmd/spy/spy.go
- node/pkg/common/readiness.go
- node/pkg/p2p/p2p.go
- node/pkg/p2p/watermark_test.go
- node/pkg/watchers/cosmwasm/watcher.go
- node/pkg/watchers/ibc/wasm_attrs.go
- node/pkg/watchers/ibc/watcher.go
- node/pkg/watchers/ibc/watcher_test.go
This PR adds a watcher that listens to the IBC receiver contract on wormchain and publishes wormhole transactions published through it.
> Node: ibc watcher

- Tiltfile
- relayer/generic_relayer/relayer-engine-v2/.prettierrc.json
- relayer/generic_relayer/relayer-engine-v2/package-lock.json
- relayer/generic_relayer/relayer-engine-v2/package.json
- relayer/generic_relayer/relayer-engine-v2/pkgs/sdk/src/main/helpers.ts
- relayer/generic_relayer/relayer-engine-v2/pkgs/sdk/src/main/main.ts
- relayer/generic_relayer/relayer-engine-v2/pkgs/sdk/src/structs.ts
- relayer/generic_relayer/relayer-engine-v2/src/app.ts
- relayer/generic_relayer/relayer-engine-v2/src/env.ts
- relayer/generic_relayer/relayer-engine-v2/src/processor.ts
- sdk/js/src/relayer/structs.ts
Tracked down a bug in the relayer engine 
https://github.com/wormhole-foundation/relayer-engine/pull/123
> Fix `ctx.fetchVaas` 

- sui/README.md
- sui/coin/Move.devnet.toml
- sui/coin/Move.toml
- sui/examples/coins/Move.devnet.toml
- sui/examples/coins/Move.toml
- sui/examples/core_messages/Move.devnet.toml
- sui/examples/core_messages/Move.lock
- sui/examples/core_messages/Move.toml
- sui/token_bridge/Move.devnet.toml
- sui/token_bridge/Move.lock
- sui/token_bridge/Move.toml
- sui/wormhole/Move.devnet.toml
- sui/wormhole/Move.lock
- sui/wormhole/Move.toml
The purpose of this PR is to update the Sui version to the latest testnet build.
> Update Sui to 0.32.0-3a70c4374

- sui/wormhole/sources/governance_message.move
Integrators may want to use the VAA sequence number for downstream applications, e.g. to perform their own checks. As such, we save the sequence number within the `DecreeReceipt` struct.
Pyth for example, needs to enforce that governance VAAs be submitted in order of sequence number.
> sui: add VAA sequence number to `DecreeReceipt`

- sdk/js/src/token_bridge/__tests__/sui-integration.ts
- sdk/js/src/token_bridge/updateWrapped.ts
This PR adds an implementation of updateWrapped on Sui and uses `MockGuardians` and `MockTokenBridge` (h/t @a5-pickle) to test it in the Sui integration tests.
> sdk/js: add updateWrappedOnSui

- clients/js/terra.ts
This updated URL seems to work 🙂
> clients/js: update terra gas url

- node/pkg/governor/governor.go
- node/pkg/governor/governor_db.go
- node/pkg/governor/governor_prices.go
* document usage of mutex (TOB-WORMGUWA-2)
* fix potential nil ptr deref in reloadPendingTransfer (TOB-WORMGUWA-3)
* add type assertion in queryCoinGecko (TOB-WORMGUWA-4)
> node/governor: address ToB findings

- node/pkg/governor/mainnet_chains.go
- node/pkg/governor/mainnet_tokens_test.go
- node/pkg/governor/manual_tokens.go
cherry-picking two commits that we want to include in v2.17.1
> v2.17.1: cherry-pick from main

- node/pkg/governor/mainnet_chains.go
Actioning result of this discussion: https://github.com/wormhole-foundation/wormhole/discussions/2922
> node: lower governor limit for solana

- ethereum/truffle-config.js
- sdk/js/src/relayer/main/main.ts
> relayer: Fix typescript to make PR 2391 Pass

- node/pkg/governor/mainnet_chains.go
- node/pkg/governor/mainnet_tokens_test.go
- node/pkg/governor/manual_tokens.go
- sdk/js/CHANGELOG.md
- sdk/js/package.json
- sdk/js/src/utils/consts.ts
- sdk/mainnet_consts.go
This PR enables mainnet support for Sei.
> Node/SDK: Mainnet Sei deploy

- aptos/coin/Move.toml
- aptos/deployer/Move.toml
- aptos/nft_bridge/Move.toml
- aptos/token_bridge/Move.toml
- aptos/wormhole/Move.toml
This is the commit hash of tag `aptos-node-mainnet_20221115.0`
> aptos: pin tag instead of deleted branch

- node/pkg/watchers/evm/connectors/poller_test.go
There seems to be a race condition in one of the EVM poller tests. The test simulates an RPC error and verifies that if the error clears, the watcher can resume processing events. The problem is that the poller may post multiple errors before the condition clears, so the test fails intermittently. This PR changes the test to see if the error eventually clears before giving up. 
Fixes #2979 (Hopefully!)
> Node/Watcher: Fix intermittent poller test failure

- sdk/vaa/payloads_test.go
This PR adds a simple unit-test case for leftpadbytes and also adds a fuzzing harness for it.
> sdk: Add unit-testing and fuzz-testing for leftpadbytes

- whitepapers/0012_ibc_generic_messaging.md
Update IBC Generic Message whitepaper to be consistent with latest version of the implementation.
> whitepapers: Update ibc generic messaging whitepaper

- algorand/runPythonUnitTests.sh
If this works, should close https://github.com/wormhole-foundation/wormhole/issues/3061
This is _not_ the best way to fix this, just a short term patch to allow CI to complete
> CI: check out specific Algorand sandbox version

- ethereum/contracts/relayer/wormholeRelayer/WormholeRelayerDelivery.sol
- ethereum/forge-test/relayer/WormholeRelayer.t.sol
Diff of PR 3043 + this PR:
[https://github.com/wormhole-foundation/wormhole/compare/c3b7bdcbd972ab54b42c2bd79c68c1f0efbb5cb7...30addd7da4b32a7bc68ceffa863a25108277b9c1#di[…]5a7](https://github.com/wormhole-foundation/wormhole/compare/c3b7bdcbd972ab54b42c2bd79c68c1f0efbb5cb7...30addd7da4b32a7bc68ceffa863a25108277b9c1#diff-8edd9a59f5dfb42c1503d5d7b95fa3f21fc97a283fec7e7e03d4cf873eb555a7)
> Fix to PR 3043

- cosmwasm/deployment/terra2/Makefile
> cosmwasm: fix terra2 test

- node/cmd/guardiand/admintemplate.go
The original plan for shutdown switch was to have the guardians submit requests to the contract to vote to shutdown or not. This required them being able to authorize a wallet to do so. Since that feature ended up being implemented another way, this command that generated the auth keys is no longer needed. This PR removes that obsolete code.
> Node: Remove unused shutdown switch auth cmd

- node/pkg/watchers/algorand/watcher.go
- node/pkg/watchers/aptos/watcher.go
- node/pkg/watchers/cosmwasm/watcher.go
- node/pkg/watchers/evm/watcher.go
- node/pkg/watchers/ibc/watcher.go
- node/pkg/watchers/near/watcher.go
- node/pkg/watchers/solana/client.go
- node/pkg/watchers/sui/watcher.go
This PR is part of the testing strategy for https://github.com/wormhole-foundation/wormhole/pull/3024
> node/watchers: Log each watcher's config on startup

- ethereum/contracts/relayer/deliveryProvider/DeliveryProviderGetters.sol
- ethereum/contracts/relayer/deliveryProvider/DeliveryProviderGovernance.sol
- ethereum/contracts/relayer/deliveryProvider/DeliveryProviderSetters.sol
- ethereum/contracts/relayer/deliveryProvider/DeliveryProviderSetup.sol
- ethereum/contracts/relayer/deliveryProvider/DeliveryProviderState.sol
- ethereum/forge-test/relayer/RelayProvider.t.sol
Adds a new role 'pricingWallet' who can perform price related updates 
Things needing feedback:
- Which governance actions should be for pricingWallet, which for the owner?
- should it be named 'pricingWallet'
> Relayer new delivery provider implementation

- wormchain/contracts/tools/deploy_wormchain.ts
Deploy core and token bridge contracts in tilt
> tilt: deploy core and token bridge to wormchain

- node/hack/query/send_req.go
- node/pkg/query/request.go
- node/pkg/query/response.go
Minor tweaks to the message spec to facilitate on-chain parsing.
> CCQ: Message tweaks

- node/cmd/spy/spy.go
Added the "sendTimeout" flag that specifies the timeout duration for sending messages to subscribers.
> spy: fixed deadlock on subscriber disconnects

- node/pkg/watchers/cosmwasm/watcher.go
Terra classic release [v2.1.2](https://github.com/classic-terra/core/releases/tag/v2.1.2) fixed the issue introduced in v2.1.1 that broke the ability to reobserve blocks from before the upgrade. This PR modifies the watcher to support that.
> Node: Make Terra Class watcher handle old blocks

- node/pkg/common/chainlock.go
- node/pkg/p2p/p2p.go
- node/pkg/processor/message.go
- node/pkg/processor/observation.go
- node/pkg/processor/vaa.go
- node/pkg/watchers/solana/client.go
Change some more high runner info logs into debugs
> Node: Remove more info logging

- wormchain/x/wormhole/client/cli/tx.go
- wormchain/x/wormhole/client/cli/tx_instantiate_allowlist.go
- wormchain/x/wormhole/keeper/msg_server_instantiate_allowlist.go
and fix vaa.BodyWormchainAllowlistInstantiateContract deserialization
> Add cli for instantiate allowlist

- node/cmd/guardiand/node.go
- node/pkg/node/node.go
- node/pkg/node/node_test.go
- node/pkg/watchers/mock/config.go
- node/pkg/watchers/mock/watcher.go
Best to review commit-by-commit. They are all related, hence in the same PR but if you'd like me to split them up into separate PRs that can easily be done. Just let me know.
> node/node: increase test coverage and other improvements

- node/pkg/db/db.go
- node/pkg/db/open.go
- node/pkg/node/node.go
- node/pkg/node/node_test.go
- node/pkg/node/options.go
- node/pkg/node/publicrpcRunnable.go
- node/pkg/p2p/p2p.go
This helps with the benchmarking (next PR on the stack) if there are multiple different benchmarks in a row.
> node: graceful shutdown

- .github/CODEOWNERS
This is an attempt at cleaning up the CODEOWNERS file to reflect those who are performing active reviews on relevant modules.  If I got something wrong or I missed an obvious replacement, please let me know and I can fix it.
> codeowners: audit of active code owners

- wormchain/x/ibc-hooks/README.md
- wormchain/x/ibc-hooks/client/cli/query.go
- wormchain/x/ibc-hooks/hooks.go
- wormchain/x/ibc-hooks/ibc_module.go
- wormchain/x/ibc-hooks/ics4_middleware.go
- wormchain/x/ibc-hooks/keeper/keeper.go
- wormchain/x/ibc-hooks/sdkmodule.go
- wormchain/x/ibc-hooks/types/errors.go
- wormchain/x/ibc-hooks/types/keys.go
- wormchain/x/ibc-hooks/wasm_hook.go
x/ibc-hooks is pulled from https://github.com/osmosis-labs/osmosis/tree/v15.2.0/x/ibc-hooks
New PR against main, includes updates from https://github.com/wormhole-foundation/wormhole/pull/3232
> Add x/ibc-hooks to wormchain repo

- node/go.mod
- node/go.sum
- wormchain/app/app.go
- wormchain/go.mod
- wormchain/go.sum
This is a stacked PR containing PFM and its integration.
> Add PFM to wormchain

- node/pkg/node/node_test.go
This PR adds tests for the injection of governance VAAs through a Guardian's adminRPC
> node/node_test: Test governance vaa injection

- Tiltfile
- devnet/query-server.yaml
- node/cmd/ccq/http.go
- node/cmd/ccq/p2p.go
- node/cmd/ccq/pending_request.go
- node/cmd/ccq/query_server.go
- node/cmd/ccq/utils.go
- node/cmd/root.go
The CCQ Query Server is an HTTP server / RESTful service that handles query requests, publishes them to the gossip network, waits for the responses to reach quorum, and then returns the response.
> ccq: query server

- aptos/token_bridge/sources/complete_transfer.move
This allows transferring coins to accounts that don't exist, or exist but haven't opted in to the coins yet.
https://github.com/aptos-labs/aptos-core/blob/e71a5169217a2ebe23f39838ee3099981ed2d560/aptos-move/framework/aptos-framework/sources/aptos_account.move#L98-L115
In the tests, I removed all the code that creates accounts and registers them for the coins to ensure these are now done by the complete transfer function.
> aptos: use aptos_account::deposit_coins

- node/pkg/watchers/sui/watcher.go
- node/pkg/watchers/sui/watcher_test.go
This is the proposed change.  Still working on tests.
> node/pkg/watcher: sui json parsing fix

- ethereum/contracts/interfaces/relayer/IWormholeRelayer.sol
- ethereum/contracts/interfaces/relayer/IWormholeRelayerTyped.sol
- ethereum/contracts/relayer/wormholeRelayer/WormholeRelayerBase.sol
- ethereum/contracts/relayer/wormholeRelayer/WormholeRelayerDelivery.sol
- ethereum/contracts/relayer/wormholeRelayer/WormholeRelayerStorage.sol
- ethereum/forge-test/relayer/WormholeRelayer.t.sol
- sdk/js/src/relayer/__tests__/wormhole_relayer.ts
- sdk/js/src/relayer/structs.ts
> AutoRelayer: reintroduce reentrancy guard, revert when replay protection triggered

- whitepapers/0007_governor.md
* expand section explaining the reasons for defense-in-depth
* add clarity around limit vs. delay
* add FAQ section
> whitepapers: Update Governor whitepaper

- Tiltfile
- devnet/node.yaml
- node/pkg/gwrelayer/gwrelayer.go
- node/pkg/gwrelayer/gwrelayer_test.go
- sdk/devnet_consts.go
- wormchain/devnet/base/config/genesis.json
This PR adds the ability for the gateway relayer to forward attestation VAAs to the token bridge contract on Gateway / Wormchain.
> Node/Gateway: Relay attestations

- ethereum/forge-test/Governance.t.sol
- ethereum/forge-test/MessagesRV.t.sol
- ethereum/forge-test/TokenImplementation.t.sol
- ethereum/forge-test/rv-helpers/TestUtils.sol
Fix the assumptions to match the storage layout correctly. This fixes some fallout from #2956
> ethereum: fix some intermittently failing tests

- sdk/js/package.json
- sdk/js/src/cosmwasm/address.ts
- sdk/js/src/utils/array.ts
- sdk/js/src/utils/consts.ts
Use `4002` as its chain id since it's another cosmos chain
> [sdk/js] Add Kujira chain id

- sdk/js/src/algorand/Algorand.ts
> sdk/js: Redeem on Algorand dynamic cost budget fix

- ethereum/slither.config.json
* Ignore external stuff and mocks
* Add solc remappings so it can find the dependencies
> ethereum: add default slither config

- node/cmd/ccq/http.go
- sdk/js-query/src/query/ethCall.test.ts
The CCQ server should make sure the API key is valid before decoding the request body. Also it should limit the request body to 5MB.
There are two new integration tests for this PR that can't be merged until PR #3421 lands:
`valid api key but payload too large should fail based on size`
`invalid api key with payload too large should fail based on api key`
> CCQ: Server should check api key first

- algorand/sandbox-algorand/images/indexer/Dockerfile
More fallout from https://github.com/wormhole-foundation/wormhole/pull/3389
> CI: Change branch for Algorand Indexer

- sdk/js-query/CHANGELOG.md
- sdk/js-query/package-lock.json
- sdk/js-query/package.json
- sdk/js-query/src/query/BinaryWriter.ts
- sdk/js-query/src/query/ethCall.ts
- sdk/js-query/src/query/ethCallByTimestamp.ts
- sdk/js-query/src/query/request.ts
- sdk/js-query/src/query/utils.ts
Had to make some refinements based on use in a CRA app
> sdk/ccq: refine dependencies

- .github/workflows/build.yml
- Dockerfile.proto
- node/Dockerfile
- scripts/Dockerfile.lint
- scripts/dev-setup.sh
This feature release mitigates CVE-2023-39325
> Update golang version to 1.20.10

- aptos/Dockerfile
- solana/Dockerfile.client
- sui/Dockerfile.base
This is the recommended installation procedure following https://github.com/nodesource/distributions/tree/4f746d991e099f9494b12e275abe1aab21f1ddf0#installation-instructions
This updates the installers in the aptos, solana, and sui Docker images.
> aptos/Dockerfile: update nodesource installer

- sdk/js/package.json
- sdk/js/src/cosmwasm/address.ts
- sdk/js/src/utils/array.ts
- sdk/js/src/utils/consts.ts
A new cosmos gateway chain. Use `4004` as its chain id.
> sdk/js: Add Celestia chain id

- node/cmd/ccq/utils.go
This small PR addresses a code review comment from PR #3468.
> CCQ: Query server code cleanup

- near/Dockerfile.build
- near/Makefile
- near/contracts/nft-bridge/src/lib.rs
- near/contracts/token-bridge/src/lib.rs
- near/contracts/wormhole/src/lib.rs
This ensures that the refund amount is at most the attached deposit when upgrading the contracts.
> near/contracts: clamp upgrade repayment delta to 0

- node/pkg/adminrpc/adminserver.go
This PR fixes the JSON unmarshalling error.
> node/pkg: fix json unmarshalling

- node/pkg/watchers/evm/connectors/batch_poller.go
- node/pkg/watchers/evm/watcher.go
Scroll supports polling for finalized but not safe. This PR add support for that.
Note that the Scroll public RPC has not been updated to support these changes, so this should not be enabled in testnet yet.
> Node/EVM: Scroll finality

- node/pkg/adminrpc/adminserver.go
This PR fixes a bug where the txhash passed into the reobserve function wasn't decode correctly.
> node/pkg/adminrpc: Need to decode hex string.

- node/pkg/p2p/p2p.go
This is useful for tweaking the gossip sub params for lower network egress for example
> node/pkg/p2p: Add GossipSub configuration to Components struct

- node/hack/solana/account_lookup.go
- node/pkg/watchers/solana/client.go
> Node/Solana: Process multiple wormhole instructions

- sdk/js/src/solana/wormhole/accounts/sequence.ts
Based on https://github.com/wormhole-foundation/wormhole/blob/wen/solana-rewrite/solana/tests/helpers/coreBridge/legacy/state/EmitterSequence.ts#L61-L74
> JS SDK: Update SequenceTracker deserialization

- SECURITY.md
> fix: typos in SECURITY.md

- terra/contracts/token-bridge/src/contract.rs
This migration code has been performed already, so it's no longer necessary. Moved some of the commentary over to https://github.com/wormhole-foundation/wormhole/pull/3597
> terra: delete migration

- terra/contracts/token-bridge/src/contract.rs
- terra/docs/README.md
- terra/docs/token_id.md
- terra/docs/token_upgrades.md
Additional docs following #3138
> terra/doc: add some implementation notes

- node/pkg/p2p/ccq_p2p.go
In testnet the filter used to limit subscriptions to the CCQ topic is breaking down because multiple guardians use the same guardian key with different peer IDs. Since all of the guardians in testnet are listed as bootstrap peers, this PR adds an additional check to allow subscriptions from bootstrap peers.
> Node/CCQ: Allow subscribes from bootstrap peers

- node/pkg/governor/mainnet_chains.go
As discussed in https://github.com/wormhole-foundation/wormhole/discussions/3734
> Node: Update governor limit for Polygon

- node/pkg/governor/mainnet_chains.go
From Governance discussion: https://github.com/wormhole-foundation/wormhole/discussions/3745
> governor: update base limits

- sdk/rust/core/src/chain.rs
```
cosmoshub: 4000
evmos: 4001
kujira: 4002
neutron: 4003
celestia: 4004
stargaze: 4005
seda: 4006
```
> Rust ibc ids

- wormchain/contracts/tools/accountant_register_mainnet.ts
- wormchain/contracts/tools/deploy_wormchain_testnet.ts
- wormchain/contracts/tools/upgrade_wormchain_testnet.ts
This was the script used to upload the ibc receiver to wormchain testnet.
```
deployed contract wormchainIbcReceiver, codeID: 2, address: wormhole1nc5tatafv6eyq7llkr2gv50ff9e22mnf70qgjlv737ktmt4eswrq0kdhcj, txHash: 723DCEAA0EB46DC0E76D8B6F958DCA982982B33B4A073B758E522C03B0824C2D
```
> wormchain: deploy scripts

- sdk/rust/core/src/chain.rs
As requested https://github.com/wormhole-foundation/wormhole/pull/3763#pullrequestreview-1857079769
> Consts: Add Dymension to rust sdk consts

- sdk/js-query/CHANGELOG.md
- sdk/js-query/package-lock.json
- sdk/js-query/package.json
- sdk/js-query/src/mock/index.ts
this fixes the issue due to the Solana RPC returning numbers that are greater than `Number.MAX_SAFE_INTEGER`
```
RangeError [ERR_OUT_OF_RANGE]: The value of "value" is out of range. It must be >= 0n and < 2n ** 64n. Received 18_446_744_073_709_551_616n
```
> sdk/js-query: solana mock band-aid

- sdk/js/src/utils/consts.ts
Verify correctness on the Explorer link -- https://neutron.celat.one/pion-1/accounts/neutron1enf63k37nnv9cugggpm06mg70emcnxgj9p64v2s8yx7a2yhhzk2q6xesk4
> Update Neutron testnet core bridge

- clients/js/README.md
- clients/js/package-lock.json
- clients/js/package.json
- clients/js/src/chains/generic/getOriginalAsset.ts
- clients/js/src/chains/generic/getWrappedAssetAddress.ts
- clients/js/src/chains/generic/provider.ts
- clients/js/src/cmds/submit.ts
- clients/js/src/cmds/transfer.ts
- clients/js/src/consts/networks.ts
Since the last time the SDK version was bumped, the following new chains have been added:
- Stargaze
- Seda
- Dymension
- Polygon Sepolia
> Client/JS: Add new changes

- node/pkg/accountant/ntt.go
- node/pkg/accountant/ntt_test.go
This PR adds a defense in depth check to the guardian NTT accountant to the code that parses an AR payload, to make sure that the entire payload is as expected, not just up through what we need.
> Node/NTT/Acct: Defense in depth

- sdk/js/src/token_bridge/__tests__/aptos-integration.ts
Apparently one was missed in #3815
> sdk/js: uniform test timeouts

- node/pkg/query/query.go
- node/pkg/query/query_test.go
- node/pkg/watchers/evm/ccq.go
- node/pkg/watchers/evm/watcher.go
- node/pkg/watchers/solana/ccq.go
- node/pkg/watchers/solana/client.go
- sdk/js-query/src/query/ethCall.test.ts
- sdk/js-query/src/query/solana.test.ts
This PR allows a configurable (but hard coded) number of concurrent queries per chain.
TODO: We need to come up with a reasonable number of workers per chain!
> Node/CCQ: Concurrent queries

- node/pkg/p2p/p2p.go
This runs validity checks on the gossip address override only once and avoids spamming the log.
> fix: lifted gossip address override our of AddrsFactory hook

- SECURITY.md
Preemptively getting this in place, just waiting on https://github.com/wormhole-foundation/wormhole-audits/pull/9 to be approved and merged.
> docs: Add latest audit reports

- node/pkg/accountant/ntt_config.go
- node/pkg/accountant/ntt_test.go
Please double check that these are addresses that point to valid and verified NTT contracts!
> node: add emitters to ntt allowlist

- clients/js/src/chains/sui/submit.ts
This patch fixes the guardian set upgrade handler for sui in `worm`. It looks like the old code path was written before the transaction block refactor.
A nicer solution would be to abstract out this governance VAA logic into a utility function as the same pattern is done in a few other places, but this PR is not that ambitious.
> clients/js: fix sui guardian set upgrade handler

- clients/js/README.md
- clients/js/package-lock.json
- clients/js/package.json
- clients/js/src/chains/generic/getOriginalAsset.ts
- clients/js/src/chains/generic/getWrappedAssetAddress.ts
- clients/js/src/chains/generic/provider.ts
- clients/js/src/cmds/submit.ts
- clients/js/src/cmds/transfer.ts
- clients/js/src/consts/networks.ts
- clients/js/src/evm.ts
- cspell-custom-words.txt
This PR upgrades the version of the SDK used by the worm client to pick up the recently added chains.
> Client/js: Add new chains

- SECURITY.md
Associated with https://github.com/wormhole-foundation/wormhole-audits/pull/10
> docs: Update security.md with Cantina NTT audit report

- node/cmd/guardiand/admintemplate.go
- node/pkg/adminrpc/adminserver.go
- node/pkg/adminrpc/prototext_test.go
- sdk/vaa/payloads.go
Somehow this governance action got added without a command to generate the prototext. This PR adds that command.
Fixes #3902.
> Node: Add adminserver command to generate template for accountant modify balance

- node/cmd/guardiand/node.go
Rather than checking `*unsafeDevMode` and `*testnetMode`, we can use the `env` variable, which is much cleaner.
Fixes #3920.
> Node: Use the env variable for run mode checks

- ethereum/env/.env.acala.testnet
- ethereum/env/.env.karura.testnet
acala/karura: update testnet environments
Related with https://github.com/AcalaNetwork/Acala/discussions/2769#discussioncomment-9844505
> acala/karura: update testnet environments

- node/Makefile
See also #4031 for more context.
> node: Add Makefile test target for arm64

- clients/js/package-lock.json
- clients/js/package.json
- clients/js/src/chains/generic/getOriginalAsset.ts
- clients/js/src/chains/generic/getWrappedAssetAddress.ts
- clients/js/src/chains/generic/provider.ts
- clients/js/src/consts/networks.ts
client/js: update wormhole-foundation/sdk (0.9.0) and certusone/wormhole-sdk (0.10.17)
> client/js: update wormhole-foundation/sdk (0.9.0) and certusone/wormhole-sdk (0.10.17)

- node/hack/repair_solana/repair.go
- node/pkg/watchers/solana/client.go
- sdk/mainnet_consts.go
This PR does some simple clean up / performance improvements in the Solana watcher.
> Node: Solana watcher cleanup

- .github/CODEOWNERS
Add @johnsaigle @mdulin2 @jtieri as additional codeowners for wormchain
> Update wormchain CODEOWNERS

- clients/js/src/cmds/aptos.ts
This PR includes changes required to the `worm` cli in order to deploy to another aptos network and/or with another deployer key.
> clients/js: support alternative aptos networks

- node/pkg/watchers/aptos/watcher.go
> Node/Aptos: Don't replay old observation on startup

- .github/CODEOWNERS
Update the governor codeowners to folks with the best technical understanding of the governor and the token generation script.
Feel free to reach out to me directly to confirm the GitHub usernames
> CI: Update Governor codeowners

- node/hack/governor/src/index.ts
- node/pkg/governor/mainnet_tokens_test.go
- node/pkg/governor/manual_tokens.go
Also make a small fix to the token generation script where `newTokenSymbol` will not exist so indexing into the array will fail
> governor: Add initial token list for Unichain and Berachain

- svm/wormhole-core-shims/Cargo.lock
- svm/wormhole-core-shims/Makefile
- svm/wormhole-core-shims/README.md
```sh
NETWORK=mainnet SVM=solana make build-artifacts
```
You should see the following output at the end:
```
solana-verify get-executable-hash target/deploy/wormhole_post_message_shim.so
e724f0159914ff64d83ebceadc4c90c5b2df4883935b91b140d651ff207bf4f3
solana-verify get-executable-hash target/deploy/wormhole_verify_vaa_shim.so
b3e5ee398c5cb4ac14f71c5311babdb2e043bff3e825160885235dafb121255e
```
> svm: use solana-verify to build

- .github/CODEOWNERS
Proposal to add `djb15` as a second root reviewer
> github: Add djb15 as root reviewer

- node/pkg/governor/mainnet_tokens_test.go
- node/pkg/governor/manual_tokens.go
INK tokens collated from: https://www.coingecko.com/en/categories/ink-ecosystem
SeiEVM tokens collated from: https://www.coingecko.com/en/categories/sei-v2-ecosystem
> node: Add initial tokens for SeiEVM and Ink

- node/pkg/watchers/evm/chain_config.go
```
verify_chain_config (main *)$ go run verify.go --chainId 47
Verifying prod hyperevm...
Verifying EVM chain ID for prod hyperevm ✓
Verifying finality values for prod hyperevm ✓
Verifying contract address for prod hyperevm ✓
Verifying test hyperevm...
Verifying EVM chain ID for test hyperevm ✓
Verifying finality values for test hyperevm ✓
Verifying contract address for test hyperevm ✓
verify_chain_config (main *)$
```
> Deploy HyperEVM in mainnet

- whitepapers/0011_accountant.md
https://github.com/wormhole-foundation/wormhole/pull/3815 added support for NTT in the Accountant. This PR adds relevant information to the Accountant whitepaper.
> docs: Add NTT-related information to Accountant whitepaper

- wormchain/x/tokenfactory/README.md
- Add information about tokenfactory restrictions. These can be confirmed by reading through 5255e933d68629f0643207b0f9d3fa797af5cbf7 where the module was added originally.
- Remove documentation for unsupported message.
- Add link to upstream tokenfactory documentation.
> docs: Clarify tokenfactory restrictions

- .github/workflows/build.yml
- .golangci.yml
- cosmwasm/contracts/cw20-wrapped/src/state.rs
- cosmwasm/contracts/global-accountant/tests/missing_observations.rs
- cosmwasm/contracts/ibc-translator/tests/contract_test.rs
- cosmwasm/contracts/ibc-translator/tests/execute_test.rs
- cosmwasm/contracts/mock-bridge-integration/src/state.rs
- cosmwasm/contracts/token-bridge/src/state.rs
- cosmwasm/contracts/wormhole/src/state.rs
- cosmwasm/packages/accountant/src/contract.rs
- cosmwasm/packages/accountant/src/state/account.rs
- cosmwasm/packages/accountant/src/state/addr.rs
- cosmwasm/packages/accountant/src/state/transfer.rs
- node/cmd/guardiand/node.go
- node/cmd/spy/spy.go
- node/pkg/node/publicrpcRunnable.go
- node/pkg/node/publicwebRunnable.go
- terra/contracts/cw20-wrapped/src/state.rs
- terra/contracts/mock-bridge-integration/src/state.rs
- terra/contracts/token-bridge/src/state.rs
- terra/contracts/wormhole/src/state.rs
- Suppress golangci-lint issues
- Fix clippy lints
> ci: Fix lint issues raised by new golangci-lint and clippy versions

- guardianset/README.md
- guardianset/mainnetv1/v1.prototxt
- guardianset/mainnetv2/v1.prototxt
- guardianset/mainnetv2/v2.prototxt
- guardianset/mainnetv2/v3.prototxt
- guardianset/mainnetv2/v4.prototxt
Moved over from https://github.com/wormhole-foundation/wormhole-networks so that we can archive that repository
> Add guardian set prototxt files and short readme

- .golangci.yml
https://staticcheck.dev/docs/checks/#SA9003
> ci: lint: Empty body in an if or else branch

- .golangci.yml
- node/pkg/watchers/evm/ccq_backfill.go
- node/pkg/watchers/evm/reobserve.go
- node/pkg/watchers/ibc/watcher.go
- node/pkg/watchers/near/poll.go
- node/pkg/watchers/sui/watcher.go
> Find the code that returns nil even if it checks that the error is not nil.
https://golangci-lint.run/docs/linters/configuration/#nilerr
> Checks that there is no simultaneous return of nil error and an invalid value.
https://golangci-lint.run/docs/linters/configuration/#nilnil
> ci: Add `nilnil` and `nilnesserr` lints 
